package:
  name: apko
  version: "1.2.7"
  epoch: 0 # GHSA-3xc5-wrhm-f963
  description: Build OCI images using APK directly without Dockerfile
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
  resources:
    cpu: "2"
    memory: 7Gi

environment:
  contents:
    packages:
      - go-1.26

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/apko
      tag: v${{package.version}}
      expected-commit: a118c3d604107532b5525bd4bee2fb369a6228aa

  - uses: go/build
    with:
      go-package: go-1.26
      output: apko
      packages: .
      ldflags: |
        -buildid= \
        -X sigs.k8s.io/release-utils/version.gitVersion=$(git describe --dirty --tags --always) \
        -X sigs.k8s.io/release-utils/version.gitCommit=$(git rev-parse HEAD) \
        -X sigs.k8s.io/release-utils/version.gitTreeState=$(shell git diff --quiet >/dev/null 2>&1 || echo "dirty" || echo "clean") \
        -X sigs.k8s.io/release-utils/version.buildDate=$(date -u -d "@$SOURCE_DATE_EPOCH" +'%Y-%m-%dT%H:%M:%SZ')

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: apko
        version: ${{package.version}}
    - uses: test/tw/help-check
      with:
        bins: apko
    - runs: |
        cat <<'EOF' >> /tmp/wolfi-base.yaml
        contents:
          keyring:
            - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
          repositories:
            - https://packages.wolfi.dev/os
          packages:
            - wolfi-base

        cmd: /bin/sh -l

        archs:
        - x86_64
        - aarch64
        EOF

        apko build  /tmp/wolfi-base.yaml test test.tar

update:
  enabled: true
  github:
    identifier: chainguard-dev/apko
    strip-prefix: v
    use-tag: true
