package:
  name: aws-load-balancer-controller
  version: "3.2.0"
  epoch: 1 # use go-1.25, fix ldflags, fix symlink, add RBAC
  description: A Kubernetes controller for Elastic Load Balancers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/aws-load-balancer-controller
      tag: v${{package.version}}
      expected-commit: 0fb5e3b7d70421a9a2a144d78b2c384d1e77600f

  - runs: |
      # https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/Dockerfile#L18-L27
      VERSION_PKG=sigs.k8s.io/aws-load-balancer-controller/pkg/version
      GIT_VERSION=$(git describe --tags --dirty --always) && \
      GIT_COMMIT=$(git rev-parse HEAD) && \
      BUILD_DATE=$(date -d@"${SOURCE_DATE_EPOCH}" +%Y-%m-%dT%H:%M:%S%z) && \
      GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) GO111MODULE=on \
      CGO_CPPFLAGS="-D_FORTIFY_SOURCE=2" \
      CGO_LDFLAGS="-Wl,-z,relro,-z,now" \
      go build -buildmode=pie -tags 'osusergo,netgo,static_build' -ldflags="-linkmode=external -extldflags '-static-pie' -X ${VERSION_PKG}.GitVersion=${GIT_VERSION} -X ${VERSION_PKG}.GitCommit=${GIT_COMMIT} -X ${VERSION_PKG}.BuildDate=${BUILD_DATE}" -mod=readonly -a -o /home/build/out/controller main.go

  - runs: |
      install -Dm755 /home/build/out/controller "${{targets.destdir}}"/usr/bin/controller

subpackages:
  - name: "aws-load-balancer-controller-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf ./usr/bin/controller ${{targets.subpkgdir}}/controller
    # test added by a robot (compat)
    test:
      pipeline:
        - runs: |
            readlink -v /controller

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/aws-load-balancer-controller
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/kwok/cluster
      with:
        serviceaccount: true
    - name: Launch controller with kwok cluster
      uses: test/daemon-check-output
      with:
        setup: |
          kubectl create clusterrolebinding test-admin \
            --clusterrole=cluster-admin \
            --serviceaccount=default:default
          kubectl config view --minify --raw > /tmp/kubeconfig.yaml
        start: controller --cluster-name=test-cluster --aws-region=us-east-1 --metrics-bind-addr ":8080" --health-probe-bind-addr ":8081"
        timeout: 30
        expected_output: |
          unable to initialize AWS cloud
