package:
  name: bmake
  version: "20260704"
  epoch: 0
  description: Portable version of the NetBSD make build tool
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - tzdata

pipeline:
  - uses: fetch
    with:
      expected-sha256: 1ad2620cb58addcfbd25d80d21bad9139e3a672b8f08c5f7e57f84119ecef3e3
      uri: https://www.crufty.net/ftp/pub/sjg/bmake-${{package.version}}.tar.gz
      strip-components: 0

  - runs: |
      ./bmake/boot-strap \
        --prefix=/usr \
        --install-destdir=${{targets.destdir}} \
        --install

subpackages:
  - name: bmake-doc
    pipeline:
      - uses: split/manpages
    description: bmake manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  release-monitor:
    identifier: 208

test:
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        # bmake uses '-V VARIABLE' to print variable values; MAKE_VERSION holds the version string
        bmake -r -f /dev/null -V MAKE_VERSION | grep -F "${{package.version}}"
    - uses: test/no-docs
