package:
  name: boring-registry
  version: "0.17.0"
  epoch: 7 # go/wolfi-rsc/boring-registry
  description: Terraform Provider and Module Registry
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
  resources:
    cpu: "1"
    memory: 6Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8704f795ce2a60704b94a341d2d8e54cb18f737c
      repository: https://github.com/TierMobility/boring-registry
      tag: v${{package.version}}

  - uses: bump
    with:
      deps: |-
        github.com/cloudflare/circl@v1.6.3
        google.golang.org/grpc@v1.79.3
        github.com/go-jose/go-jose/v4@v4.1.4
        go.opentelemetry.io/otel/sdk@v1.43.0
        github.com/aws/aws-sdk-go-v2/service/s3@v1.97.3

  - uses: go/build
    with:
      ldflags: |
        -X github.com/TierMobility/boring-registry/version.Version="${{package.version}}"
        -X github.com/TierMobility/boring-registry/version.Commit="$(git rev-parse --verify HEAD --short)"
        -X github.com/TierMobility/boring-registry/version.Date="$(date -u -d "@$SOURCE_DATE_EPOCH" +'%FT%T%z')"
      output: boring-registry
      packages: .

update:
  enabled: true
  manual: false
  github:
    identifier: TierMobility/boring-registry
    strip-prefix: v

test:
  pipeline:
    - name: "Check boring-registry version"
      runs: |
        boring-registry version
    - name: "Test boring-registry help command"
      runs: |
        boring-registry --help
