package:
  name: byobu
  version: "7.9"
  epoch: 1
  description: "open source text-based window manager and terminal multiplexer"
  copyright:
    - license: GPL-3.0-or-later
  dependencies:
    runtime:
      - gawk
      - iproute2
      - openssl
      - posix-libc-utils
      - py${{vars.python-version}}-tornado
      - python-${{vars.python-version}}
      - tmux

vars:
  python-version: '3.13'

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dustinkirkland/byobu
      expected-commit: 49bb0015eeaf438d9f267853435a63069af8dace
      tag: ${{package.version}}

  - runs: autoreconf -vif

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: dustinkirkland/byobu
    use-tag: true

test:
  environment:
    contents:
      packages:
        - man-db
        - ${{package.name}}-doc
  pipeline:
    - runs: |
        byobu -h
        byobu-enable
        byobu-disable
        byobu-janitor -f
        trustmux --help
        trustmux-ctl --help
    - uses: test/no-docs

subpackages:
  - name: byobu-doc
    description: byobu documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs
