package:
  name: checksec
  version: "3.2.0"
  epoch: 0 # toolchain rebuild for  go-1.25-1.25.11
  description: Binary security checker
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - bash
      - binutils
      - file
      - grep
      - openssl
      - posix-libc-utils
  resources:
    cpu: "1"
    memory: 5Gi
  test-resources:
    cpu: "1"
    memory: 6Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/slimm609/checksec.sh
      expected-commit: c8afc72b017a693c94a64cde0955b143502c3f40
      tag: ${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: checksec

update:
  enabled: true
  github:
    identifier: slimm609/checksec.sh

test:
  pipeline:
    - runs: |
        checksec file /bin/ls --output=yaml | grep -i "Canary Found"
        checksec --version
        checksec --help

environment:
  contents:
    packages:
      - go-1.25
