package:
  name: check
  version: 0.15.2
  epoch: 5
  description: A unit test framework for C
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - pkgconf-dev
      - texinfo

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libcheck/check
      tag: ${{package.version}}
      expected-commit: 11970a7e112dfe243a2e68773f014687df2900e8

  - uses: patch
    with:
      patches: fix-missing-end-verbatim.patch

  - uses: autoconf/configure
    with:
      opts: |
        --disable-static \
        --enable-build-docs

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: check-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    description: check manpages
    test:
      pipeline:
        - uses: test/docs

  - name: check-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - check
    description: check dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

update:
  enabled: true
  github:
    identifier: libcheck/check

test:
  pipeline:
    - uses: test/tw/ldd-check
