package:
  name: cli11
  version: "2.7.0"
  epoch: 0 # go/wolfi-rsc/cli11
  description: command line parser for C++11
  copyright:
    - license: BSD-3-Clause
  resources:
    cpu: "13"
    memory: 25Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2d8705619780fde5888c7d598ed889963a7c55dd
      repository: https://github.com/CLIUtils/CLI11
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=True \

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: CLIUtils/CLI11
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - uses: test/pkgconf
