package:
  name: cluster-api-aws-controller
  version: "2.11.0"
  epoch: 0 # GHSA-xmrv-pmrh-hhx2
  description: Kubernetes Cluster API Provider AWS provides consistent deployment and day 2 operations of "self-managed" and EKS Kubernetes clusters on AWS
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
  resources:
    cpu: "7"
    memory: 16Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/cluster-api-provider-aws
      tag: v${{package.version}}
      expected-commit: 815a1b02310be2e6ad23cdafb62bf08b0b44f98a

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.43.0
        github.com/aws/aws-sdk-go-v2/service/s3@v1.97.3
      modroot: hack/tools
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        google.golang.org/grpc@v1.79.3
        github.com/go-jose/go-jose/v4@v4.1.4
        go.opentelemetry.io/otel/sdk@v1.43.0
        github.com/aws/aws-sdk-go-v2/service/s3@v1.97.3

  - uses: go/build
    with:
      packages: .
      output: cluster-api-aws-controller
      go-package: go-1.25
      ldflags: |
        -buildid= ""
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.buildDate=$(date -u -d "@$SOURCE_DATE_EPOCH" +'%Y-%m-%dT%H:%M:%SZ')
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.gitCommit=$(git rev-parse HEAD)
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.gitVersion=$(git describe --dirty --tags --always)
        -X sigs.k8s.io/cluster-api-provider-aws/v2/version.gitTreeState=$(git diff --quiet >/dev/null 2>&1 && echo "clean" || echo "dirty")

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package for cluster-api-aws-controller"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/
          ln -s ./usr/bin/cluster-api-aws-controller ${{targets.subpkgdir}}/manager
    dependencies:
      provides:
        - ${{package.name}}-entrypoint=${{package.full-version}}
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check
        - uses: test/tw/help-check
          with:
            bins: /manager

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-api-provider-aws
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
        - git
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/kwok/cluster
    - runs: |
        git clone --branch v${{package.version}} --depth 1 https://github.com/kubernetes-sigs/cluster-api-provider-aws.git
        kubectl apply -f cluster-api-provider-aws/config/crd/bases/
    - name: Launch controller with kwok cluster
      uses: test/daemon-check-output
      with:
        start: cluster-api-aws-controller --diagnostics-address ":8080" --health-addr ":8081"
        timeout: 30
        expected_output: |
          starting manager
          problem running manager

environment:
  contents:
    packages:
      - go-1.25
