package:
  name: conftest
  version: "0.68.2"
  epoch: 3 # CVE-2026-33814
  description: Write tests against structured configuration data using the Open Policy Agent Rego query language
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - cue

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 36f23bf930b808c73c4e41c6a4eeac5b620b2225
      repository: https://github.com/open-policy-agent/conftest
      tag: v${{package.version}}

  - uses: bump
    with:
      deps: |-
        github.com/go-jose/go-jose/v4@v4.1.4
        go.opentelemetry.io/otel/sdk@v1.43.0
        github.com/aws/aws-sdk-go-v2/service/s3@v1.97.3
        github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.7.8
        golang.org/x/net@v0.53.0

  - uses: go/build
    with:
      ldflags: -X github.com/open-policy-agent/conftest/internal/commands.version=${{package.version}}
      modroot: .
      output: conftest
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: open-policy-agent/conftest
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: conftest
    - name: Verify a simple Rego policy
      runs: |
        echo 'package main' > test.rego
        conftest verify -p test.rego
