#nolint:git-checkout-must-use-github-updates
package:
  name: confluent-docker-utils
  version: "0.0.170"
  epoch: 0
  description: This package provides Docker Utility Belt (dub) and Confluent Platform Utility Belt (cub).
  copyright:
    - license: Apache-2.0
  options:
    no-provides: true

vars:
  # This will compile with py3.13, however tests will fail with errors:
  # 'ModuleNotFoundError: No module named 'pipes'
  # - https://github.com/jupyter/nbclassic/issues/308
  # Upstream may have to make some code changes to be compatible with py3.13.
  python-version: "3.12"
  venv-home: /opt/chainguard/confluent-docker-utils

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python-${{vars.python-version}}-dev
      - uv

pipeline:
  - uses: auth/uv
    with:
      allow-fallback-indexes: true

  - uses: git-checkout
    with:
      expected-commit: 88f250e13da8e81d3ecf8d4fa75f43539c13f32f
      repository: https://github.com/confluentinc/confluent-docker-utils
      tag: v${{package.version}}

  - runs: |
      sed -i 's/requests~=2.32.0/requests~=2.33.0/' requirements.txt

  - uses: uv/venv
    with:
      venv: ${{vars.venv-home}}
      python: ${{vars.python-version}}

  - runs: |
      source "${{vars.venv-home}}/bin/activate"

      uv pip install --no-compile -r requirements.txt .

      uv pip check

      chmod 644 "${{vars.venv-home}}/.lock"

      # Stage venv to package
      mkdir -p "${{targets.contextdir}}/opt/chainguard"
      cp -a "${{vars.venv-home}}" "${{targets.contextdir}}/opt/chainguard/"

      # Symlink binaries to /usr/bin
      mkdir -p "${{targets.contextdir}}/usr/bin"
      for bin in cub dub normalizer; do
        ln -sf "${{vars.venv-home}}/bin/$bin" "${{targets.contextdir}}/usr/bin/$bin"
      done

  - uses: uv/bump
    with:
      venv: ${{targets.contextdir}}${{vars.venv-home}}
      packages: |
        urllib3==2.6.3  # CVE-2025-50182 GHSA-48p4-8xcf-vxj5, CVE-2025-50181 GHSA-pq67-6m6q-mj2v, GHSA-2xpw-w6gg-jr37, GHSA-gm62-xv2j-4w53, GHSA-38jv-5279-wg99

  - uses: strip

update:
  enabled: true
  # It is necessary to use release monitor
  # because it is required to be included
  # in the allowed IP list to use Github
  release-monitor:
    identifier: 371723

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/pip-check
      with:
        python: ${{vars.venv-home}}/bin/python
    - uses: test/tw/help-check
      with:
        bins: |
          cub
          dub
          normalizer
