package:
  name: conftest
  version: "0.69.0"
  epoch: 1 # toolchain rebuild for  go-1.26-1.26.6
  description: Write tests against structured configuration data using the Open Policy Agent Rego query language
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - cue

vars:
  go-version: "1.26"

environment:
  contents:
    packages:
      - go-${{vars.go-version}}

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4130398ce1505a13585d9141bfec9e601995466b
      repository: https://github.com/open-policy-agent/conftest
      tag: v${{package.version}}

  - uses: bump
    with:
      deps: |-
        github.com/aws/aws-sdk-go-v2/service/s3@v1.97.3

  - uses: go/build
    with:
      ldflags: -X github.com/open-policy-agent/conftest/internal/commands.version=${{package.version}}
      modroot: .
      output: conftest
      packages: .
      go-package: go-1.26

  - uses: strip

update:
  enabled: true
  github:
    identifier: open-policy-agent/conftest
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: conftest
    - name: Verify a simple Rego policy
      runs: |
        echo 'package main' > test.rego
        conftest verify -p test.rego
