#nolint:git-checkout-must-use-github-updates
package:
  name: confluent-kafka-images
  version: "8.4.0.47"
  epoch: 0 # go/wolfi-rsc/confluent-kafka-images
  description: Provides build files for Apache Kafka and Confluent Docker images
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

var-transforms:
  - from: ${{package.version}}
    match: '\.(\d+)$'
    replace: '-$1'
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 97b5a7ecca10c4060cc71c9c9488ed79a6f30040
      repository: https://github.com/confluentinc/kafka-images
      tag: v${{vars.mangled-package-version}}

data:
  - name: files
    items:
      # https://github.com/confluentinc/kafka-images/tree/master/kafka
      kafka: Files for deploying and running the Community Version of Kafka.
      # https://github.com/confluentinc/kafka-images/tree/master/kafka-connect
      kafka-connect: Files for for deploying and running Kafka Connect.
      # https://github.com/confluentinc/kafka-images/tree/master/local
      local: Files for quickly start Apache Kafka® in KRaft mode with zero configuration setup.
      # https://github.com/confluentinc/kafka-images/tree/master/server-connect
      server-connect: Files for deploying and running Kafka Connect.
      # https://github.com/confluentinc/kafka-images/tree/master/server
      server: Files for deploying and running Confluent Server.

subpackages:
  - range: files
    name: ${{package.name}}-${{range.key}}
    description: ${{range.value}}
    pipeline:
      - runs: |
          mkdir -m 0755 -p "${{targets.subpkgdir}}"/etc/confluent/docker
          install -Dm644 ${{range.key}}/include/etc/confluent/docker/* "${{targets.subpkgdir}}"/etc/confluent/docker/
          chmod -R a+rX ${{targets.subpkgdir}}/etc/confluent/docker
    test:
      environment:
        contents:
          packages:
            - acl
      pipeline:
        - runs: |
            installed_file_count=$(ls -1 /etc/confluent/docker | wc -l)
            [ $installed_file_count != 0 ]

            for f in $(find /etc/confluent/docker -type f); do
              # Files should be user-writeable, group-/world-readable
              getfacl $f | grep -F user::rw-
              getfacl $f | grep -F group::r--
              getfacl $f | grep -F other::r--
            done

            for d in $(find /etc/confluent/docker -type d); do
              # Directories should be user-writeable, group-/world-readable, executable by all
              getfacl $d | grep -F user::rwx
              getfacl $d | grep -F group::r-x
              getfacl $d | grep -F other::r-x
            done

update:
  enabled: true
  version-transform:
    - match: "-"
      replace: "."
  git:
    tag-filter-prefix: v
    strip-prefix: v

# Based on package size if was determined that this origin package is empty apart from its own SBOM and this test was added to confirm it is empty and will fail if the package is not longer empty (contains more than an SBOM)
test:
  pipeline:
    - uses: test/emptypackage
