package:
  name: croc
  version: "10.4.3"
  epoch: 0 # CVE-2026-32280
  description: Easily and securely send things from one computer to another
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/schollz/croc
      expected-commit: f662ab719808bffeb9ec09f758a67876e532ce84
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: croc

update:
  enabled: true
  github:
    identifier: schollz/croc
    strip-prefix: v

test:
  environment:
    environment:
      CROC_SECRET: wolfi-test
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: croc
    - uses: test/tw/help-check
      with:
        bins: croc
    - name: Test croc send and receive
      runs: |
        # Set up environment variables
        port=9009

        # Start the croc relay in the background
        croc relay --port=$port > croc.log 2>&1 &
        relay_pid=$!
        sleep 3

        # Send a test message in the background
        croc --relay=localhost:$port send --text "test message" > croc_send.log 2>&1 &
        send_pid=$!
        sleep 3

        # Receive the test message
        received_message=$(timeout 20 croc --relay=localhost:$port --overwrite --yes)

        # Check if the received message matches the sent message
        [ "$received_message" = "test message" ]
