package:
  name: crossplane-2.2
  version: "2.2.2"
  epoch: 1 # CVE-2026-39821
  description: Cloud Native Control Planes
  dependencies:
    provides:
      - crossplane=${{package.full-version}}
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 32300d8ac6b01bb66702187eea8dee208511c75b
      repository: https://github.com/crossplane/crossplane
      tag: v${{package.version}}

  - uses: bump
    with:
      deps: golang.org/x/net@v0.55.0

  - runs: |
      mkdir -p ${{targets.destdir}}/crds
      cp cluster/crds/* ${{targets.destdir}}/crds

      mkdir -p ${{targets.destdir}}/webhookconfigurations
      cp cluster/webhookconfigurations/* ${{targets.destdir}}/webhookconfigurations

  - uses: go/build
    with:
      output: crossplane
      packages: ./cmd/crossplane
      ldflags: -X github.com/crossplane/crossplane/v2/internal/version.version=v${{package.version}}

subpackages:
  - name: ${{package.name}}-crank
    dependencies:
      provides:
        - crossplane-crank=${{package.full-version}}
    pipeline:
      - uses: go/build
        with:
          output: crank
          packages: ./cmd/crank
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: crank

update:
  enabled: true
  github:
    identifier: crossplane/crossplane
    strip-prefix: v
    tag-filter-prefix: v2.2

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: crossplane
        version: ${{package.version}}
    - uses: test/tw/help-check
      with:
        bins: crossplane
