package:
  name: dagger
  version: "0.20.4"
  epoch: 0 # GHSA-78h2-9frx-2jm8
  description: Application Delivery as Code that Runs Anywhere
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "1"
    memory: 5Gi

environment:
  environment:
    CGO_ENABLED: 0
  contents:
    packages:
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dagger/dagger
      tag: v${{package.version}}
      expected-commit: 660afa89fa097dc540170849033dc32c3a4b0280

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/reference/best-practices/snippets/modules/testing/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/introduction/features/snippets/services-2/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/introduction/features/snippets/services-1/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/introduction/features/snippets/secrets/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/introduction/features/snippets/programmability-2/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/introduction/features/snippets/programmability-1/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/introduction/features/snippets/debugging-2/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/introduction/features/snippets/debugging-1/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/getting-started/types/snippets/fs-filters/pre-call/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/getting-started/types/snippets/fs-filters/post-call/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/getting-started/types/snippets/default-paths/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/getting-started/quickstarts/ci/snippets/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/getting-started/quickstarts/agent/snippets/part2/workspace/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/getting-started/quickstarts/agent/snippets/part1/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/getting-started/ci-integrations/snippets/php/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/getting-started/ci-integrations/snippets/java/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/getting-started/ci-integrations/snippets/google-cloud-run/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/state-functions/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/use-endpoint/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/test-against-db-service/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/start-stop-services/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/service-lifecycle-3/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/service-lifecycle-2/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/service-lifecycle-1/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/persist-service-state/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/expose-host-services-to-dagger/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/expose-dagger-services-to-host/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/create-interdependent-services/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/services/bind-services/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/secrets/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/interfaces/usages/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/interfaces/implementations/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/interfaces/declarations/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/return-values-file/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/return-values-directory/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/return-values-container/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/return-values-chaining/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/functions-complex/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/arguments-string/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/arguments-return-values-integer/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/arguments-return-values-float/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/arguments-optional/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/arguments-file/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/arguments-directory/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/functions/arguments-container/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/enums/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/documentation/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/dependencies/chaining/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/custom-types/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/constructors/go/default-object
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/chaining/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/extending/modules/snippets/cache-volumes/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/terminal-directory-2/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/terminal-directory-1/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/terminal-container/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/tag-publish-image/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/set-env-vars/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/set-env-var/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/set-common-default-path/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/secret-variable/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/secret-file/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/secret-dockerfile/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/read-file-http/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/publish-image/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/mount-file/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/mount-dir/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/handle-errors/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/export-file-dir/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/export-container/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/execute-concurrently/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/env-use-strings/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/env-use-multiple-types/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/env-use-directories/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/env-use-containers/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/custom-spans/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/copy-modify-dir/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/copy-filter-dir-pre/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/copy-filter-dir-post/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/copy-file/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/copy-file-runtime/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/copy-dir/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/continue-after-errors/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/clone-git-repository/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/clone-git-repository-ssh/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/cache-dependencies/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/builds/oci-labels/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/builds/oci-annotations/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/builds/multi-stage-build/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/builds/multi-arch/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/builds/multi-arch-cc/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/builds/matrix-build/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/builds/dockerfile/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/builds/dockerfile-context/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: docs/current_docs/cookbook/snippets/builds/cache/go
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
      modroot: core/integration/testdata/sdks/only-runtime/src
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        github.com/go-jose/go-jose/v4@v4.1.4

  - uses: go/build
    with:
      ldflags: |
        -X github.com/dagger/dagger/engine.Version=v${{package.version}}
        -X github.com/dagger/dagger/engine.Tag=v${{package.version}}
      output: dagger
      packages: ./cmd/dagger

update:
  enabled: true
  ignore-regex-patterns:
    - 'sdk'
    - 'helm'
    - 'llm'
  github:
    identifier: dagger/dagger
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        dagger version
        dagger --help
