package:
  name: deno
  version: "2.7.14"
  epoch: 3 # go/wolfi-rsc/deno
  description: "A modern runtime for JavaScript and TypeScript."
  copyright:
    - license: MIT
  resources:
    cpu: "22"
    memory: 36Gi
  test-resources:
    cpu: "1"

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - clang-${{vars.clang-version}}
      - cmake
      - glibc-dev
      - posix-libc-utils
      - protobuf-dev
      - protoc
      - python3
      - rust-1.95
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/denoland/deno
      tag: v${{package.version}}
      expected-commit: 2d674b25625bcc367853d00fe86f6e84390f88cb

  - uses: patch
    with:
      patches: rand-pin-bump.patch

  - uses: rust/cargobump

  - runs: |
      cargo update rand@0.9.2 --precise 0.9.3

  - uses: cargo/build
    with:
      output: deno

  - uses: strip

update:
  enabled: true
  github:
    identifier: denoland/deno
    strip-prefix: v

test:
  pipeline:
    - runs: |
        deno --version
        echo 'console.log("Hello, World!");' > hello_world.js
        output=$(deno run hello_world.js)
        if [ "$output" = "Hello, World!" ]; then
          echo "Test passed!"
        else
          echo "Test failed!"
          exit 1
        fi
        deno --help

vars:
  clang-version: 22
