package:
  name: docker-compose
  version: "5.1.3"
  epoch: 1 # GHSA-w8rr-5gcm-pp58
  description: Define and run multi-container applications with Docker
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - btrfs-progs-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - containerd
      - coreutils
      - go
      - libseccomp-dev
      - libtool
      - linux-headers
      - lvm2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/docker/compose
      tag: v${{package.version}}
      expected-commit: 977a4310f9f6d89d4b176fee01a5b7c109c1816a

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.43.0
        go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp@v1.43.0
        go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp@v1.43.0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      DESTDIR=${{targets.destdir}}/usr/bin/ make build

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: docker-compose
    - uses: test/tw/ver-check
      with:
        bins: docker-compose
        version: ${{package.version}}

update:
  enabled: true
  github:
    identifier: docker/compose
    strip-prefix: v
    tag-filter: v
