package:
  name: docker-cli-buildx
  version: "0.34.1"
  epoch: 0
  description: buildx is a Docker CLI plugin for extended build capabilities with BuildKit.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "3"
    memory: 7Gi

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-1.26
  # this explicit environment is required else we run into build failures.
  environment:
    CGO_ENABLED: 1

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/docker/buildx
      tag: v${{package.version}}
      expected-commit: e0b0e77d18d3379bc1e0d55f3b37de288d36fe47

  - uses: go/build
    with:
      go-package: go-1.26
      packages: ./cmd/buildx
      install-dir: libexec/docker/cli-plugins/
      output: docker-buildx
      ldflags: -X github.com/docker/buildx/version.Version=${{package.version}}

test:
  pipeline:
    - runs: |
        set -euo pipefail
        /usr/libexec/docker/cli-plugins/docker-buildx version | grep -F "${{package.version}}"

update:
  enabled: true
  github:
    identifier: docker/buildx
    strip-prefix: v
    tag-filter: v
