package:
  name: docker-machine-driver-harvester
  version: "1.0.8"
  epoch: 2 # toolchain rebuild for  go-1.26-1.26.7
  description: The Harvester machine driver for Docker.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7eb5f5403b1ff5d0d3268162530e5657dc1da1b6
      repository: https://github.com/harvester/docker-machine-driver-harvester
      tag: v${{package.version}}

  - uses: bump
    with:
      language: go
      packages: |-
        go.opentelemetry.io/otel@v1.44.0
        go.opentelemetry.io/otel/trace@v1.44.0
      replaces: |-
        github.com/golang/glog=github.com/golang/glog@v1.2.4

  - uses: go/build
    with:
      go-package: go-1.26
      ldflags: -X main.VERSION={{package.version}}
      output: docker-machine-driver-harvester
      packages: .

test:
  environment:
    contents:
      packages:
        - rancher-machine
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        # This is a negative test to check if the driver is working. We can't have a proper test
        # because the driver requires a harvesterhci.io cluster to be up and running.
        output=$(rancher-machine create --driver harvester --harvester-image-name=rancher/harvester:latest --harvester-disk-size=1 --harvester-network-name=test TEST 2>&1 || true)
        echo "$output" | grep -q "connect: connection refused"

update:
  enabled: true
  github:
    identifier: harvester/docker-machine-driver-harvester
    strip-prefix: v
    use-tag: true

environment:
  contents:
    packages:
      - go-1.26
