package:
  name: eksctl
  version: "0.225.0"
  epoch: 6 # GHSA-mh2q-q3fh-2475
  description:
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
  resources:
    cpu: "9"
    memory: 17Gi

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/weaveworks/eksctl
      expected-commit: 02674beb75c9346abcef72f9c1e755115f85db29
      tag: v${{package.version}}

  - uses: bump
    with:
      language: go
      packages: |-
        github.com/containerd/containerd@v1.7.29
        golang.org/x/crypto@v0.45.0
        github.com/docker/cli@v29.2.0
        google.golang.org/grpc@v1.79.3
        github.com/buger/jsonparser@v1.1.2
        helm.sh/helm/v3@v3.20.2
        github.com/moby/spdystream@v0.5.1
        go.opentelemetry.io/otel@v1.41.0

  - uses: go/build
    with:
      packages: ./cmd/eksctl
      output: eksctl
      go-package: go-1.25
      ldflags: |
        -X github.com/weaveworks/eksctl/pkg/version.gitCommit=$(git rev-parse --short HEAD)
        -X github.com/weaveworks/eksctl/pkg/version.buildDate=$(date -d@$SOURCE_DATE_EPOCH +%Y-%m-%dT%H:%M:%SZ)

update:
  enabled: true
  github:
    identifier: weaveworks/eksctl
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: eksctl
    - uses: test/tw/ver-check
      with:
        bins: eksctl
    - name: Verify eksctl generates shell completion scripts
      runs: |
        set -euo pipefail
        eksctl completion bash > /tmp/eksctl_completion.sh
        grep -F "eksctl" /tmp/eksctl_completion.sh
