package:
  name: falcosidekick
  version: "2.34.0"
  epoch: 0 # GHSA-wf45-q9ch-q8gh
  description: Connect Falco to your ecosystem
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-1.26

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0eb49b80a12b27a71d36814fa5f443bd5523448b
      repository: https://github.com/falcosecurity/falcosidekick
      tag: ${{package.version}}

  - uses: bump
    with:
      deps: |-
        github.com/apache/thrift@v0.23.0

  - runs: |
      make falcosidekick RELEASE=${{package.version}}
      mkdir -p ${{targets.destdir}}/usr/bin
      mv falcosidekick ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  manual: false
  github:
    identifier: falcosecurity/falcosidekick
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: falcosidekick
    - uses: test/tw/help-check
      with:
        bins: falcosidekick
    - name: Test falcosidekick HTTP server starts and responds
      uses: test/daemon-check-output
      with:
        start: /usr/bin/falcosidekick
        expected_output: "listening"
        timeout: "30"
        error_strings: ""
        post: |
          wait-for-it localhost:2801 -t 15
          curl -f http://localhost:2801/healthz
