package:
  name: flux-image-automation-controller
  version: "1.1.2"
  epoch: 0 # GHSA-3xc5-wrhm-f963
  description: GitOps Toolkit controller that patches container image tags in Git
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "9"
    memory: 17Gi

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+).*
    replace: $1
    to: major-version

environment:
  environment:
    CGO_ENABLED: "1"
    CGO_LDFLAGS: -static -fuse-ld=lld
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - clang-16
      - gcc
      - lld-16

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c2d9853b0df5f008e3e4768c8901e01818f74272
      repository: https://github.com/fluxcd/image-automation-controller
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        google.golang.org/grpc@v1.79.3

  - uses: go/build
    with:
      packages: .
      output: image-automation-controller
      tags: netgo,osusergo,static_build
      go-package: go-1.26

subpackages:
  - name: flux-image-automation-controller-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          # The upstream helm chart assumes the binary is in /.
          ln -sf ../../bin/image-automation-controller ${{targets.subpkgdir}}/usr/local/bin/image-automation-controller
          ln -sf ./usr/bin/image-automation-controller ${{targets.subpkgdir}}/image-automation-controller
    dependencies:
      runtime:
        - flux-image-automation-controller
    test:
      pipeline:
        - uses: test/tw/symlink-check

  - name: ${{package.name}}-iamguarded-compat
    description: "compat package for iamguarded"
    pipeline:
      - uses: iamguarded/build-compat
        with:
          package: flux-image-automation-controller
          version: ${{vars.major-version}}
      - runs: |
          mkdir -p ${{targets.contextdir}}/opt/iamguarded/fluxcd-image-automation-controller/bin/
          ln -sf ../../../../usr/bin/image-automation-controller ${{targets.contextdir}}/opt/iamguarded/fluxcd-image-automation-controller/bin/image-automation-controller
      - uses: iamguarded/finalize-compat
        with:
          package: flux-image-automation-controller
          version: ${{vars.major-version}}
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check
        - uses: iamguarded/test-compat
          with:
            package: flux-image-automation-controller
            version: ${{vars.major-version}}

update:
  enabled: true
  ignore-regex-patterns:
    - api/
  github:
    identifier: fluxcd/image-automation-controller
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
        - curl
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: image-automation-controller
    - uses: test/kwok/cluster
    - name: Launch controller with kwok cluster
      uses: test/daemon-check-output
      with:
        setup: |
          kubectl apply -f https://github.com/fluxcd/flux2/releases/latest/download/install.yaml
          kubectl wait --for=condition=Ready nodes --all
        start: image-automation-controller --metrics-addr :8080 --health-addr :8081
        timeout: 30
        expected_output: |
          Starting Controller
          Starting workers
        post: |
          curl --silent --fail localhost:8080/metrics
          curl --silent --fail localhost:8081/healthz
