package:
  name: flyte
  version: "1.16.7"
  epoch: 1 # toolchain rebuild for  go-1.26-1.26.4
  description: Scalable and flexible workflow orchestration platform that seamlessly unifies data, ML and analytics stacks.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-1.26
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/flyteorg/flyte
      tag: v${{package.version}}
      expected-commit: 7dc8c662cf169e24a0d739dbea11a1d1c522714f

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd
      output: flyte
      go-package: go-1.26

update:
  enabled: true
  github:
    identifier: flyteorg/flyte
    strip-prefix: v
  ignore-regex-patterns:
    - flytectl/.* # Not relevant tags
    # v2 is a different product branch that may need to be package separately
    - ^2

test:
  pipeline:
    - runs: |
        flyte --help
