package:
  name: font-takao
  version: 0.1.0
  epoch: 2
  description: takao fonts
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - py3-pip
      - python3

# seems to miss the P variants, as it doesnt build them by repo
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hidekatsu-izuno/takaoka-fonts
      tag: v${{package.version}}
      expected-commit: 806b09b684deaeb6dba667670f965e7d27391a52

  - runs: |
      pip install -r requirements.txt
      python build.py
      pkgname=${{package.name}}
      destfontdir="${{targets.destdir}}/usr/share/fonts/${pkgname#font-}"
      mkdir -p "$destfontdir"
      install -Dm644 ./build/dest/*.ttf "$destfontdir/"

update:
  enabled: false
  exclude-reason: Upstream repository has not had a release in several years and version tracking is not feasible

test:
  pipeline:
    - uses: test/fonts
