package:
  name: fulcio
  version: "1.8.6"
  epoch: 1 # CVE-2026-39829
  description: Sigstore OIDC PKI
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "1"
    memory: 6Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  environment:
    CGO_ENABLED: "0"
  contents:
    packages:
      - go-1.26

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 378c654f48c3bafdced04ead7010aab2cb4c6ca1
      repository: https://github.com/sigstore/fulcio
      tag: v${{package.version}}

  - uses: bump
    with:
      deps: |-
        golang.org/x/net@v0.55.0
      modroot: hack/tools
      tidy: false

  - uses: bump
    with:
      deps: |-
        golang.org/x/net@v0.55.0
        golang.org/x/crypto@v0.52.0

  - uses: go/build
    with:
      modroot: .
      output: fulcio
      packages: ./
      go-package: go-1.26

update:
  enabled: true
  github:
    identifier: sigstore/fulcio
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
        - wait-for-it
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: fulcio
    - uses: test/tw/help-check
      with:
        bins: fulcio
    - name: Run fulcio server
      runs: |
        fulcio serve --ca=ephemeralca > /dev/null 2>&1 &
        wait-for-it localhost:8080 -t 30
        curl localhost:8080/api/v1/rootCert
