package:
  name: goreleaser
  version: "2.14.3"
  epoch: 2 # GHSA-p77j-4mvh-x3m3
  description: Deliver Go binaries as fast and easily as possible
  copyright:
    - license: MIT
  resources:
    cpu: "10"
    memory: 12Gi

environment:
  environment:
    GOTOOLCHAIN: local+auto
  contents:
    packages:
      - git
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/goreleaser/goreleaser
      tag: v${{package.version}}
      expected-commit: 7cc45095d4e0bebd44c8d2bbf97823856405cfd7

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.51.0
        google.golang.org/grpc@v1.79.3

  - uses: go/build
    with:
      packages: .
      modroot: .
      output: goreleaser
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

update:
  enabled: true
  github:
    identifier: goreleaser/goreleaser
    strip-prefix: v

test:
  pipeline:
    - name: version check
      runs: |
        goreleaser --version
        goreleaser --help
