package:
  name: harbor-cli
  version: "0.0.22"
  epoch: 1 # toolchain rebuild for  go-1.26-1.26.4
  description: Official Harbor CLI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
  resources:
    cpu: "1"
    memory: 4Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ffc1762eaee4d6c19774359c9ef7792ec1d7d365
      repository: https://github.com/goharbor/harbor-cli
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/harbor
      output: harbor
      go-package: go-1.26

  - uses: strip

test:
  pipeline:
    - runs: |
        harbor version
        harbor help
        harbor --help

update:
  enabled: true
  github:
    identifier: goharbor/harbor-cli
    strip-prefix: v

environment:
  contents:
    packages:
      - go-1.26
