package:
  name: harbor-cli
  version: "0.0.18"
  epoch: 2 # CVE-2026-32280
  description: Official Harbor CLI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
  resources:
    cpu: "2"
    memory: 4Gi

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 03ce614891616c6587ad6da1b5e3c0d51c0deaf2
      repository: https://github.com/goharbor/harbor-cli
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/harbor
      output: harbor

  - uses: strip

test:
  pipeline:
    - runs: |
        harbor version
        harbor help
        harbor --help

update:
  enabled: true
  github:
    identifier: goharbor/harbor-cli
    strip-prefix: v

environment:
  contents:
    packages:
      - go-1.25
