package:
  name: hcloud
  version: "1.64.1"
  epoch: 0 # CVE-2026-32280
  description: A command-line interface for Hetzner Cloud
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.25
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hetznercloud/cli
      tag: v${{package.version}}
      expected-commit: fbfa512ee92a876c839357a01b9b49849eca8c74

  - uses: go/build
    with:
      packages: ./cmd/hcloud/main.go
      output: hcloud
      go-package: go-1.25
      ldflags: |
        -X main.version=internal/version.version=${{package.version}}

update:
  enabled: true
  github:
    identifier: hetznercloud/cli
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        hcloud version
        hcloud completion bash | grep -F "hcloud"
        hcloud context list
