package:
  name: hcloud
  version: "1.65.0"
  epoch: 4 # CVE-2026-39821
  description: A command-line interface for Hetzner Cloud
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 1Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.26
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hetznercloud/cli
      tag: v${{package.version}}
      expected-commit: a9f3077b036d9145ef75e17b51483fa4481c0a9f

  - uses: bump
    with:
      deps: |-
        golang.org/x/crypto@v0.52.0
        golang.org/x/net@v0.55.0

  - uses: go/build
    with:
      packages: ./cmd/hcloud/main.go
      output: hcloud
      go-package: go-1.26
      ldflags: |
        -X main.version=internal/version.version=${{package.version}}

update:
  enabled: true
  github:
    identifier: hetznercloud/cli
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        hcloud version
        hcloud completion bash | grep -F "hcloud"
        hcloud context list
