package:
  name: jenkins-plugin-manager
  version: "2.15.0"
  epoch: 2 # go/wolfi-rsc/jenkins-plugin-manager
  description: Plugin Manager CLI tool for Jenkins
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - maven
      - openjdk-17-default-jdk
      - wolfi-base
      - wolfi-baselayout
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jenkinsci/plugin-installation-manager-tool
      tag: ${{package.version}}
      expected-commit: f14436c0d6174ee7203d20e54a5b3d945b1be4ff

  - uses: bump
    with:
      manifest: plugin-management-library/pom.xml

  - runs: |
      mvn clean package -DskipTests

      mkdir -p ${{targets.destdir}}/usr/share/java/jenkins-plugin-manager
      cp plugin-management-cli/target/jenkins-plugin-manager*.jar ${{targets.destdir}}/usr/share/java/${{package.name}}/jenkins-plugin-manager.jar

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt
          ln -s /usr/share/java/${{package.name}}/jenkins-plugin-manager.jar ${{targets.subpkgdir}}/opt/jenkins-plugin-manager.jar
    # test added by a robot (compat)
    test:
      pipeline:
        - runs: |
            readlink -v /opt/jenkins-plugin-manager.jar

update:
  enabled: true
  github:
    identifier: jenkinsci/plugin-installation-manager-tool

test:
  environment:
    contents:
      packages:
        - openjdk-17-default-jvm
  pipeline:
    - name: "Check jenkins-plugin-manager Installation"
      runs: |
        if [ -f "/usr/share/java/jenkins-plugin-manager/jenkins-plugin-manager.jar" ]; then
          echo "jenkins-plugin-manager JAR found."
        else
          echo "jenkins-plugin-manager JAR not found!" && exit 1
        fi
    - name: "Test jenkins-plugin-manager Basic Functionality"
      runs: |
        java -jar /usr/share/java/jenkins-plugin-manager/jenkins-plugin-manager.jar --help || (echo "jenkins-plugin-manager test failed!" && exit 1)
        java -jar /usr/share/java/jenkins-plugin-manager/jenkins-plugin-manager.jar --list || (echo "Plugin list test failed!" && exit 1)
