package:
  name: k3d
  version: "5.9.0"
  epoch: 3 # GHSA-hrxh-6v49-42gf
  description: Little helper to run CNCF's k3s in Docker
  copyright:
    - license: MIT
  resources:
    cpu: "6"
    memory: 10Gi
  test-resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - git
      - go-1.26

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k3d-io/k3d
      tag: v${{package.version}}
      expected-commit: 15dd1e2dbd62c53ed990fce9b7332335e8cb053c

  - uses: bump
    with:
      language: go
      deps: |-
        golang.org/x/crypto@v0.52.0
        github.com/docker/cli@v29.2.1
        golang.org/x/oauth2@v0.27.0
        github.com/containerd/containerd@v1.7.27
        golang.org/x/net@v0.55.0
        github.com/docker/docker@v28.0.0
        github.com/moby/moby/api@v1.53.0
        github.com/moby/moby/client@v0.2.2
        github.com/moby/go-archive@v0.1.0
        github.com/moby/sys/atomicwriter@v0.1.0
        google.golang.org/grpc@v1.82.1
        github.com/go-jose/go-jose/v3@v3.0.5
        github.com/google/go-containerregistry@v0.20.8
      modroot: |-
        tools
        docgen
        .

  - uses: patch
    with:
      patches: fix-moby-imports.patch

  - runs: |
      make build
      install -Dm755 ./bin/k3d ${{targets.destdir}}/usr/bin/k3d

subpackages:
  - name: k3d-tools
    description: ""
    pipeline:
      - uses: go/build
        with:
          modroot: ./tools
          packages: .
          output: k3d-tools
          ldflags: "-X 'github.com/k3d-io/k3d/v5/tools/version.Version=v${{package.version}}'"
          go-package: go-1.26
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: k3d-tools

  - name: k3d-proxy
    description: ""
    dependencies:
      runtime:
        - nginx
    pipeline:
      - working-directory: proxy
        runs: |
          install -Dm755 nginx-proxy "${{targets.subpkgdir}}"/usr/bin/nginx-proxy

          mkdir -p "${{targets.subpkgdir}}"/etc/confd
          cp -ar templates "${{targets.subpkgdir}}"/etc/confd/
          cp -ar conf.d "${{targets.subpkgdir}}"/etc/confd/
      - uses: git-checkout
        with:
          repository: https://github.com/kelseyhightower/confd.git
          expected-commit: 919444eb6cf721d198b2bb18581d0f0b3734d107
          destination: ../confd
      # we dont want upstream vendor directories.
      # We have no idea what code is in there and
      # would prefer to use our own if available
      - working-directory: ../confd
        runs: rm -rf vendor
      - uses: bump
        with:
          language: go
          modroot: ../confd
          deps: |-
            github.com/go-jose/go-jose/v3@v3.0.5
            github.com/golang/protobuf@v1.5.4
            github.com/hashicorp/go-retryablehttp@v0.7.7
            golang.org/x/crypto@v0.52.0
            google.golang.org/protobuf@v1.33.0
            google.golang.org/grpc@v1.82.1
            golang.org/x/net@v0.55.0
      - uses: go/build
        with:
          modroot: ../confd
          packages: .
          output: confd
          ldflags: "-X main.GitSHA=$(git rev-parse --short HEAD)"
          go-package: go-1.26
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: confd

update:
  enabled: true
  github:
    identifier: k3d-io/k3d
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: k3d
    - uses: test/tw/help-check
      with:
        bins: k3d
