package:
  name: k6
  version: "1.7.1"
  epoch: 1 # go/wolfi-rsc/k6
  description: A modern load testing tool, using Go and JavaScript
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - bash-binsh
      - coreutils
      - curl
      - grep
  resources:
    cpu: "1"
    memory: 6Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/k6
      tag: v${{package.version}}
      expected-commit: 9f82e6f1fc5e806b93459b6189fbd81e4fd6b2ee

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
        google.golang.org/grpc@v1.79.3
      modroot: .github/workflows/xk6-tests/xk6-output-test
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
        google.golang.org/grpc@v1.79.3
      modroot: .github/workflows/xk6-tests/xk6-js-test
      tidy: false

  - uses: go/build
    with:
      packages: .
      output: k6

update:
  enabled: true
  github:
    identifier: grafana/k6
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: k6
    - uses: test/tw/help-check
      with:
        bins: k6
    - name: "run a demo test"
      runs: |
        k6 new
        k6 run script.js --duration=1.5s

environment:
  contents:
    packages:
      - go-1.25
