package:
  name: k6
  version: "1.6.1"
  epoch: 3 # GHSA-p77j-4mvh-x3m3
  description: A modern load testing tool, using Go and JavaScript
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - bash-binsh
      - coreutils
      - curl
      - grep
  resources:
    cpu: "1"
    memory: 6Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/k6
      tag: v${{package.version}}
      expected-commit: 2ac2bb560e70b33735692642231c8bd53acbe4fd

  - uses: go/bump
    with:
      deps: |-
        google.golang.org/grpc@v1.79.3
      modroot: examples/grpc_server
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
        google.golang.org/grpc@v1.79.3

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
        google.golang.org/grpc@v1.79.3
      modroot: .github/workflows/xk6-tests/xk6-output-test
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.40.0
        google.golang.org/grpc@v1.79.3
      modroot: .github/workflows/xk6-tests/xk6-js-test
      tidy: false

  - uses: go/build
    with:
      packages: .
      output: k6

update:
  enabled: true
  github:
    identifier: grafana/k6
    strip-prefix: v

test:
  pipeline:
    - name: "test out k6 version"
      runs: |
        k6 version
        k6 --version
        k6 --help
    - name: "run a demo test"
      runs: |
        k6 new
        k6 run script.js --duration=1.5s

environment:
  contents:
    packages:
      - go-1.25
