package:
  name: k9s
  version: "0.51.0"
  epoch: 5 # GHSA-jxpm-75mh-9fp7
  description: Kubernetes CLI To Manage Your Clusters In Style!
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "5"
    memory: 8Gi
  test-resources:
    memory: 4Gi
    disk: 8Gi
    cpu: "1"

environment:
  contents:
    packages:
      - go-1.26

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 558caafe7ba067467de46b320cc22ef11fef9c34
      repository: https://github.com/derailed/k9s
      tag: v${{package.version}}

  - uses: bump
    with:
      deps: |-
        github.com/aws/aws-sdk-go-v2/service/s3@v1.97.3
        github.com/containerd/containerd@v1.7.33
        github.com/containerd/containerd/v2@v2.2.5
        go.opentelemetry.io/otel@v1.44.0
        go.opentelemetry.io/otel/metric@v1.44.0
        go.opentelemetry.io/otel/sdk@v1.44.0
        go.opentelemetry.io/otel/sdk/metric@v1.44.0
        go.opentelemetry.io/otel/trace@v1.44.0
        golang.org/x/crypto@v0.52.0
        golang.org/x/net@v0.55.0
        oras.land/oras-go/v2@v2.6.1

  - uses: go/build
    with:
      packages: .
      go-package: go-1.26
      ldflags: |
        -X github.com/derailed/k9s/cmd.version=v${{package.version}}
        -X github.com/derailed/k9s/cmd.commit=$(git rev-parse HEAD)
        -X github.com/derailed/k9s/cmd.date=$(date -u -d "@$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ")
      output: k9s

update:
  enabled: true
  github:
    identifier: derailed/k9s
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: k9s
    - uses: test/tw/ver-check
      with:
        bins: k9s
    - uses: test/kwok/cluster
    - runs: |
        k9s info
