package:
  name: kbld
  version: "0.48.0"
  epoch: 0 # CVE-2026-33814
  description: kbld seamlessly incorporates image building and image pushing into your development and deployment workflows
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 17b1c6aec060cda75d265125f1ac6d34e79b2cde
      repository: https://github.com/carvel-dev/kbld
      tag: v${{package.version}}

  - uses: bump
    with:
      deps: |-
        golang.org/x/net@v0.53.0

  - uses: go/build
    with:
      packages: ./cmd/kbld
      output: kbld
      ldflags: -X carvel.dev/kbld/pkg/kbld/version.Version=v${{package.version}}
      go-package: go-1.26

update:
  enabled: true
  github:
    identifier: carvel-dev/kbld
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: kbld
    - uses: test/tw/help-check
      with:
        bins: kbld
    - name: write config
      runs: |
        cat <<EOF > build.yml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: test
        spec:
          selector:
            matchLabels:
              app: test
          template:
            metadata:
              labels:
                app: test
            spec:
              containers:
              - name: my-app
                image: cgr.dev/chainguard/static
        EOF
    - name: run kbld
      # We do a very simple resolve here based on https://carvel.dev/kbld/docs/v0.44.x/resolving/
      # We don't do a full resolve+build, since this requires a Docker daemon.
      runs: |
        kbld -f build.yml

environment:
  contents:
    packages:
      - go-1.26
