package:
  name: kdash
  version: "2.1.1"
  epoch: 0
  description: "A simple and fast dashboard for Kubernetes"
  copyright:
    - license: MIT
  resources:
    cpu: "5"
    memory: 9Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

vars:
  rust-version: "1.94"

environment:
  environment:
    OPENSSL_NO_VENDOR: "true"
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - libxcb
      - libxcb-dev
      - openssl
      - openssl-hardened-dev
      - pkgconf
      - pkgconf-dev
      - python3
      - rust-${{vars.rust-version}}
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kdash-rs/kdash
      tag: v${{package.version}}
      expected-commit: c9ae9dcaa96fb92547b87286b99bffb4286d0e50

  - uses: bump
    with:
      deps: |-
        eyre@0.6.12
        anstream@1.0.0
        url@2.5.4
        signal-hook-mio@0.2.5
        mio@1.2.2
        ring@0.17.14
        tokio@1.52.3
        tracing-subscriber@0.3.23
        bytes@1.12.1
        time@0.3.53
        rustls@0.23.42
        rand@0.9.5
        async-compression@0.4.42
        flate2@1.1.9
        http@1.4.2
        http-body@1.1.0
        http-body-util@0.1.4
        hyper@1.10.1
        hyper-rustls@0.27.9
        hyper-timeout@0.5.2
        plist@1.10.0
        quick-xml@0.41.0
        sync_wrapper@1.0.2
        tokio-rustls@0.26.4
        tokio-util@0.7.18
        tower@0.5.3
        tower-http@0.6.11
        tracing-error@0.2.1

  - uses: cargo/build
    with:
      output: kdash

  - uses: strip

update:
  enabled: true
  github:
    identifier: kdash-rs/kdash
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
