package:
  name: kdash
  version: "1.1.1"
  epoch: 1
  description: "A simple and fast dashboard for Kubernetes"
  copyright:
    - license: MIT
  resources:
    cpu: "9"
    memory: 13Gi

vars:
  rust-version: "1.94"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - libxcb
      - libxcb-dev
      - openssl
      - openssl-hardened-dev
      - pkgconf
      - pkgconf-dev
      - python3
      - rust-${{vars.rust-version}}
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kdash-rs/kdash
      tag: v${{package.version}}
      expected-commit: 07c6b19a5cf17fced56f4ea50a7c442f863fdf3c

  - uses: rust/cargobump

  - runs: |
      OPENSSL_NO_VENDOR=true cargo auditable build --release
      install -Dm755 target/release/kdash "${{targets.destdir}}"/usr/bin/kdash

  - uses: strip

update:
  enabled: true
  github:
    identifier: kdash-rs/kdash
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        kdash --version
        kdash --help
