package:
  name: kind
  version: "0.31.0"
  epoch: 10 # go/wolfi-rsc/kind
  description: Kubernetes IN Docker - local clusters for testing Kubernetes
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "1"
    memory: 5Gi
  test-resources:
    cpu: "1"
    memory: 5Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/kind
      tag: v${{package.version}}
      expected-commit: a323333ff9efd8099f95a8a6b5c86c75a210d00f

  - uses: go/build
    with:
      packages: ./cmd/kind
      ldflags: -X sigs.k8s.io/kind/pkg/version.Version=${{package.version}}
      output: ./kind
      go-package: go-1.25

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/kind
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: kind
    - uses: test/tw/ver-check
      with:
        bins: kind
        version: ${{package.version}}
    - runs: |
        set -euo pipefail
        kind completion bash | grep -F "kind"
        kind completion zsh | grep -F "kind"
