package:
  name: kitty-terminfo
  version: "0.47.2"
  epoch: 0
  description: Terminfo for the kitty terminal emulator
  copyright:
    - license: GPL-3.0-only

environment:
  contents:
    packages:
      - busybox
      - ncurses

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kovidgoyal/kitty
      tag: v${{package.version}}
      expected-commit: d20fe4d4b5860b77f507317ac0bf39242725d1ae

  - runs: |
      mkdir -p "${{targets.destdir}}/etc/terminfo"
      tic -x -o "${{targets.destdir}}/etc/terminfo" terminfo/kitty.terminfo

update:
  enabled: true
  github:
    identifier: kovidgoyal/kitty
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/contains-files
      with:
        dir: /etc/terminfo/x/
        name: xterm-kitty
