package:
  name: kitty-terminfo
  version: "0.49.0"
  epoch: 0 # go/wolfi-rsc/kitty-terminfo
  description: Terminfo for the kitty terminal emulator
  copyright:
    - license: GPL-3.0-only
  resources:
    cpu: "1"
    memory: 1Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - busybox
      - ncurses

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kovidgoyal/kitty
      tag: v${{package.version}}
      expected-commit: 07ed6aa3de28af2a01e521f18c56ed292aa34cfc

  - runs: |
      mkdir -p "${{targets.destdir}}/etc/terminfo"
      tic -x -o "${{targets.destdir}}/etc/terminfo" terminfo/kitty.terminfo

update:
  enabled: true
  github:
    identifier: kovidgoyal/kitty
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/contains-files
      with:
        dir: /etc/terminfo/x/
        name: xterm-kitty
