package:
  name: kubescape
  version: "4.0.5"
  epoch: 2 # GHSA-3xc5-wrhm-f963
  description: Kubescape is an open-source Kubernetes security platform for your IDE, CI/CD pipelines, and clusters. It includes risk analysis, security, compliance, and misconfiguration scanning, saving Kubernetes users and administrators precious time, effort, and resources.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "17"
    memory: 19Gi

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1d5520f7293f418dff829bfd7ed75b1f1867ea07
      recurse-submodules: "true"
      repository: https://github.com/kubescape/kubescape
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        github.com/anchore/grype@v0.104.1
        github.com/anchore/syft@v1.42.3
        github.com/go-git/go-git/v5@v5.18.0
      modroot: httphandler
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        github.com/anchore/grype@v0.104.1
        github.com/anchore/syft@v1.42.3
        github.com/go-git/go-git/v5@v5.18.0

  - uses: go/build
    with:
      packages: .
      output: kubescape
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

update:
  enabled: true
  github:
    identifier: kubescape/kubescape
    strip-prefix: v
  ignore-regex-patterns:
    - ".*rc.*"

test:
  pipeline:
    - uses: test/tw/help-check
      with:
        bins: kubescape
    - uses: test/tw/ver-check
      with:
        bins: kubescape
    - uses: test/kwok/cluster
    - name: Verify kubescape scan
      runs: |
        kubescape scan | grep -qi "Compliance Score"
