package:
  name: kyverno-policy-reporter-ui
  version: "2.5.2"
  epoch: 0 # CVE-2026-32280
  description: Policy Reporter UI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - kodata-compat

environment:
  contents:
    packages:
      - bun
      - go-1.25
      - node-gyp

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kyverno/policy-reporter-ui
      tag: v${{package.version}}
      expected-commit: ee15078f75f86f4ac9b1cf38bea4742e6453d1c6

  - working-directory: frontend
    runs: |
      bun install
      bun run generate
      # Consumers expect /var/run/ko; the kodata-compat package provides a symlink.
      mkdir -p ${{targets.contextdir}}/usr/share/ko/templates
      cp -R ./dist ${{targets.contextdir}}/usr/share/ko/ui

  - uses: go/build
    with:
      modroot: backend
      packages: .
      output: policyreporter-ui

  - name: copy more frontend requirements
    runs: |
      cp -R backend/templates ${{targets.contextdir}}/usr/share/ko/

subpackages:
  - name: kyverno-policy-reporter-ui-compat
    description: compatibility symlinks package for policyreporter-ui Dockerfile
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /ko-app/
          mkdir -p ${{targets.contextdir}}/ko-app
          mkdir -p ${{targets.contextdir}}/app
          ln -sf ../usr/bin/policyreporter-ui ${{targets.subpkgdir}}/app/policyreporter-ui
          ln -sf ../usr/bin/policyreporter-ui ${{targets.contextdir}}/ko-app/policyreporter-ui
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check

update:
  enabled: true
  # There are tags with alpha and helm charts that break our update block.
  ignore-regex-patterns:
    - 'alpha'
    - .*-dev.*
    - 'policy-reporter-ui-chart-'
    - 'dev'
  git:
    strip-prefix: v
    tag-filter-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
    environment:
      KO_DATA_PATH: "/var/run/ko"
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/systemd-tmpfiles
    - uses: test/tw/help-check
      with:
        bins: policyreporter-ui
    - name: Run and test ${{package.name}}
      uses: test/daemon-check-output
      with:
        setup: |
          curl -sLO https://raw.githubusercontent.com/kyverno/policy-reporter-ui/refs/heads/main/backend/config.example.yaml
        start: /usr/bin/policyreporter-ui run --config config.example.yaml
        timeout: 30
        expected_output: |
          register UI
          /var/run/ko/ui
          Server starts
        post: |
          set -euo pipefail
          curl -s localhost:8080 | grep -F "Policy Reporter UI"
          curl -s localhost:8080 | grep -F "html"
