package:
  name: libmd
  version: "1.2.0"
  epoch: 0
  description: Message Digest functions from BSD systems
  copyright:
    - license: CC-PDDC

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/libbsd/libmd.git
      tag: ${{package.version}}
      expected-commit: 90c4f432134c608c7e2b4dd0a1d7ca5c40b92c7a

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libmd-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmd
    description: libmd dev
    test:
      pipeline:
        - uses: test/tw/devpackage
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

  - name: libmd-doc
    pipeline:
      - uses: split/manpages
    description: libmd manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  git: {}

test:
  environment:
    contents:
      packages:
        - libmd-dev
        - build-base
        - pkgconf
  pipeline:
    - uses: test/tw/ldd-check
    - name: Test libmd compile and link
      runs: |
        set -euo pipefail

        tee test.c <<'EOF'
        #include <md5.h>
        #include <sha2.h>
        int main() {
            MD5_CTX md5ctx;
            MD5Init(&md5ctx);

            SHA2_CTX sha256ctx;
            SHA256Init(&sha256ctx);

            return 0;
        }
        EOF

        gcc $(pkg-config --cflags libmd) test.c -o test $(pkg-config --libs libmd)
        ./test
