package:
  name: libnetfilter_conntrack
  version: "1.1.1"
  epoch: 1
  description: programming interface (API) to the in-kernel connection tracking state table
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - libmnl-dev
      - libnfnetlink-dev
      - libtool
      - pkgconf-dev

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.netfilter.org/libnetfilter_conntrack
      tag: libnetfilter_conntrack-${{package.version}}
      expected-commit: cf50fa4dd12f8b7e3567ec944ab61a51f9408311

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

subpackages:
  - name: libnetfilter_conntrack-dev
    description: libnetfilter_conntrack development files
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/devpackage
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

update:
  enabled: true
  release-monitor:
    identifier: 1675

test:
  environment:
    contents:
      packages:
        - libnetfilter_conntrack-dev
        - libmnl-dev
        - libnfnetlink-dev
        - build-base
        - pkgconf
  pipeline:
    - uses: test/tw/ldd-check
    - name: Test library compile and link
      runs: |
        set -euo pipefail

        tee test.c <<'EOF'
        #include <libnetfilter_conntrack/libnetfilter_conntrack.h>
        #include <stdlib.h>
        int main() {
            struct nf_conntrack *ct = nfct_new();
            if (!ct) {
                return 1;
            }
            nfct_destroy(ct);
            return 0;
        }
        EOF

        gcc $(pkg-config --cflags libnetfilter_conntrack) test.c -o test $(pkg-config --libs libnetfilter_conntrack)
        ./test
