package:
  name: libpathrs
  version: "0.2.5"
  epoch: 1 # rust: 1.96->1.97
  description: C-friendly API to make path resolution safer on Linux.
  copyright:
    - license: MPL-2.0 OR LGPL-3.0-or-later
    - license: MPL-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - clang-${{vars.llvm-version}}
      - coreutils # for install
      - lld-${{vars.llvm-version}}
      - rust-${{vars.rust-version}}

vars:
  llvm-version: 22
  rust-version: 1.97

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cyphar/libpathrs
      tag: v${{package.version}}
      expected-commit: 080908395e75a32a5c4dbe9b318bf93643429f9f

  - runs: |
      make release

  - runs: |
      DESTDIR="${{targets.contextdir}}" ./install.sh \
        --prefix=/usr \
        --libdir=/usr/lib

subpackages:
  - name: ${{package.name}}-static
    description: ${{package.name}} static libraries
    pipeline:
      - uses: split/static
    test:
      pipeline:
        - uses: test/tw/staticpackage

  - name: ${{package.name}}-dev
    description: ${{package.name}} development headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    test:
      pipeline:
        - uses: test/tw/devpackage
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-dev
        - build-base
  pipeline:
    - uses: git-checkout
      with:
        repository: https://github.com/cyphar/libpathrs
        tag: v${{package.version}}
        expected-commit: 080908395e75a32a5c4dbe9b318bf93643429f9f
    - working-directory: examples/c
      runs: |
        make smoke-test
    - uses: test/tw/ldd-check

update:
  git: {}
