package:
  name: libpfm
  version: 4.13.0
  epoch: 4 # switch to git-checkout
  description: "perfmon libraries"
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base
  environment:
    CFLAGS: -Wno-discarded-qualifiers

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.code.sf.net/p/perfmon2/libpfm4
      tag: v${{package.version}}
      expected-commit: 3d77461cb966259c51f3b3e322564187f4bef7fb

  - uses: autoconf/make
    with:
      opts: DBG="-g -Wall -Wextra -Wno-unused-parameter"

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "libpfm-dev"
    description: "headers for libpfm"
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/devpackage

test:
  pipeline:
    - uses: test/tw/ldd-check

update:
  enabled: true
  git:
    strip-prefix: v
