package:
  name: librelp
  version: "1.13"
  epoch: 1
  description: librelp is an easy-to-use library for the RELP (Reliable Event Logging Protocol)
  copyright:
    - license: GPL-3.0-or-later

vars:
  python-version: "3.13"

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - glibc-2.43-dev
      - gnutls-dev
      - grep
      - libtool
      - openssl-dev
      - pkgconf
      - pkgconf-dev
      - py${{vars.python-version}}-docutils-bin
      - python-${{vars.python-version}}
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: bedc657e519568b25f611c8efc83eab6ac1068e9
      repository: https://github.com/rsyslog/librelp
      tag: v${{package.version}}

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      make check

  - uses: strip

subpackages:
  - name: librelp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - librelp
    description: librelp dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

update:
  enabled: true
  github:
    identifier: rsyslog/librelp
    strip-prefix: v
    tag-filter: v
    use-tag: true
  ignore-regex-patterns:
    - .1.2.18 # Bad tag

test:
  environment:
    contents:
      packages:
        - librelp-dev
        - build-base
        - pkgconf
  pipeline:
    - uses: test/tw/ldd-check
    - name: Verify librelp compile and link
      runs: |
        cat > test.c << 'EOF'
        #include <stddef.h>
        #include <librelp.h>
        int main(void) {
            relpEngine_t *pRelpEngine = NULL;
            relpRetVal r;
            r = relpEngineConstruct(&pRelpEngine);
            if (r != RELP_RET_OK) return 1;
            r = relpEngineDestruct(&pRelpEngine);
            if (r != RELP_RET_OK) return 1;
            return 0;
        }
        EOF
        gcc $(pkg-config --cflags relp) test.c -o test $(pkg-config --libs relp)
        ./test
