package:
  name: libtermkey
  version: "0.22"
  epoch: 8 # go/wolfi-rsc/libtermkey
  description: "Library for easy processing of keyboard entry from terminal-based programs"
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - ncurses-dev
      - unibilium-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neovim/libtermkey
      tag: v${{package.version}}
      expected-commit: c97f926ddcd1ade551162272bd4c8cf69e0b7de2

  - uses: autoconf/make

  - runs: |
      make PREFIX=/usr DESTDIR="${{targets.destdir}}" install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libtermkey
    description: ${{package.name}} dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check
          with:
            packages: libtermkey-dev

  - name: libtermkey-doc
    description: libtermkey documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: neovim/libtermkey
    strip-prefix: v
    tag-filter-prefix: v
    use-tag: true

test:
  pipeline:
    - uses: test/tw/ldd-check
