package:
  name: libzip
  version: "1.11.4"
  epoch: 3
  description: "A C library for reading, creating, and modifying zip archives."
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - bzip2
      - zlib
  resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - openssl
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nih-at/libzip
      tag: v${{package.version}}
      expected-commit: 6f8a0cdd24a0dc6cce9dac4a7679da784ab124ea

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: libzip-doc
    description: libzip documentation
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/doc
          mv "${{targets.destdir}}"/usr/share/doc/libzip/* "${{targets.subpkgdir}}"/usr/share/doc/
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: nih-at/libzip
    tag-filter-prefix: v
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        zipcmp -h
        zipmerge -h
        ziptool -h
    - uses: test/pkgconf
    - uses: test/tw/ldd-check
