package:
  name: luit
  version: "20250912"
  epoch: 3 # go/wolfi-rsc/luit
  description: Filter that can be run between an arbitrary application and a UTF-8 terminal emulator
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 5Gi

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libfontenc-dev
      - libx11-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 75068466d60a985c658fd8aa7583c141619d7b4e
      repository: https://github.com/ThomasDickey/luit-snapshots
      tag: v2_0_${{package.version}}

  - uses: autoconf/configure
    with:
      opts: |
        --enable-fontenc

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: luit-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - luit
    description: luit dev
    # test added by a robot. The APK was empty when it was checked,
    # which may not be true forever. If this test fails in the future, please
    # replace it with a more accurate test.
    test:
      pipeline:
        - uses: test/emptypackage

  - name: luit-doc
    description: luit docs
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: ThomasDickey/luit-snapshots
    strip-prefix: v2_0_
    tag-filter-prefix: v2_0_
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        luit -h
    - uses: test/no-docs
