package:
  name: mcp-grafana
  version: "0.11.3"
  epoch: 5 # GHSA-6g7g-w4f8-9c9x
  description: MCP server for grafana
  dependencies:
    runtime:
      - ca-certificates # ca-certificates for HTTPS requests
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "1"
    memory: 4Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/mcp-grafana
      tag: v${{package.version}}
      expected-commit: 64f9d26fafca67ce3443bea82932b370d92c4bd1

  - uses: go/bump
    with:
      deps: |-
        google.golang.org/grpc@v1.79.3
        github.com/buger/jsonparser@v1.1.2

  - uses: go/build
    with:
      packages: ./cmd/mcp-grafana/main.go
      output: mcp-grafana

subpackages:
  - name: ${{package.name}}-compat
    description: compat package for ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/app
          ln -sf /usr/bin/mcp-grafana ${{targets.contextdir}}/app/mcp-grafana
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check
          with:
            allow-absolute: true

update:
  enabled: true
  git:
    tag-filter-prefix: v
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: mcp-grafana
    - uses: test/daemon-check-output
      with:
        start: /usr/bin/mcp-grafana -log-level=debug --disable-proxied
        timeout: 30
        expected_output: |
          Starting Grafana MCP server

environment:
  contents:
    packages:
      - go-1.25
