package:
  name: metacontroller
  version: "4.15.0"
  epoch: 1 # add ldd-check test
  description: Writing kubernetes controllers can be simple
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - goreleaser
      - make
  environment:
    GOTOOLCHAIN: local+auto

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/metacontroller/metacontroller
      tag: v${{package.version}}
      expected-commit: 334d82d95988766396e46b2d64d47c7c375b38b4

  - uses: go/build
    with:
      packages: ./pkg/cmd/metacontroller
      ldflags: |
        -X main.version=${{package.version}}
        -X main.commit=$(git rev-parse HEAD)
        -X main.date=$(date -u -d "@$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ")
        -X main.builtBy=melange
      output: metacontroller
      go-package: go-1.26

test:
  environment:
    contents:
      packages:
        - git
        - curl
        - kustomize
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/kwok/cluster
    - runs: |
        metacontroller --help
    - name: Fetch the testdata from the source repo
      runs: |
        git clone --depth=1 https://github.com/metacontroller/metacontroller
    - name: Run a simple test of the operator against the testdata
      working-directory: metacontroller/deploy/helm/metacontroller
      runs: |
        kubectl apply -f crds/
        metacontroller > /dev/null 2>&1 &
        sleep 10

        curl localhost:9999/metrics

update:
  enabled: true
  github:
    identifier: metacontroller/metacontroller
    strip-prefix: v
