package:
  name: metrics-agent
  version: "2.14.12"
  epoch: 4 # CVE-2026-32280
  description: Kubernetes metrics collection agent for Cloudability that collects allocation metrics from a Kubernetes cluster system and sends the metrics to Cloudability.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "2"
    memory: 6Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cloudability/metrics-agent
      tag: metrics-agent-${{package.version}}
      expected-commit: 11f7ff2b4f54199902ca527a71cb22c2e18972c5

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.38.0

  - uses: go/build
    with:
      packages: .
      output: metrics-agent

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package for usage with standard deployments."
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf ./usr/bin/metrics-agent ${{targets.contextdir}}/metrics-agent
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check

update:
  enabled: true
  github:
    identifier: cloudability/metrics-agent
    tag-filter: metrics-agent-
    strip-prefix: metrics-agent-

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: metrics-agent
    - uses: test/tw/ver-check
      with:
        bins: metrics-agent
    - uses: test/kwok/cluster
      with:
        serviceaccount: "true"
    - name: Run and test ${{package.name}}
      uses: test/daemon-check-output
      with:
        start: /usr/bin/metrics-agent kubernetes --cluster_name kwok-kwok
        timeout: 30
        expected_output: |
          Starting Cloudability Kubernetes Metric Agent version:

environment:
  contents:
    packages:
      - go-1.25
