package:
  name: mockery
  version: "3.7.4"
  epoch: 1 # toolchain rebuild for  go-1.27-1.27.1
  description: A mock code autogenerator for Go
  copyright:
    - license: BSD-3-Clause
  resources:
    cpu: "1"
    memory: 5Gi
  test-resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - go-1.27
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vektra/mockery
      expected-commit: 98b9b173a4b4c8c65f8f9d3eb1b485defa1b9b31
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      ldflags: -X github.com/vektra/mockery/v3/internal/logging.SemVer=v${{package.version}}
      output: mockery

update:
  enabled: true
  ignore-regex-patterns:
    - '^\d$'
  github:
    identifier: vektra/mockery
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - posix-libc-utils
  pipeline:
    - runs: |
        mockery version
        mockery --help
