package:
  name: mockery
  version: "3.7.0"
  epoch: 3 # go/wolfi-rsc/mockery
  description: A mock code autogenerator for Go
  copyright:
    - license: BSD-3-Clause
  resources:
    cpu: "1"
    memory: 5Gi
  test-resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - go-1.25
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vektra/mockery
      expected-commit: 61b1a4512604843293e2b3201c158029d052a73d
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      ldflags: -X github.com/vektra/mockery/v3/internal/logging.SemVer=v${{package.version}}
      output: mockery

update:
  enabled: true
  ignore-regex-patterns:
    - '^\d$'
  github:
    identifier: vektra/mockery
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - posix-libc-utils
  pipeline:
    - runs: |
        mockery version
        mockery --help
