package:
  name: nerdctl
  version: "2.2.2"
  epoch: 0 # go/wolfi-rsc/nerdctl
  description: Docker-compatible CLI for containerd, with support for Compose, Rootless, eStargz, OCIcrypt, IPFS, ...
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "1"
    memory: 4Gi
  test-resources:
    memory: 1Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containerd/nerdctl
      tag: v${{package.version}}
      expected-commit: 20bbfaa940ddc532b8587ac6aeef88e76c8abf77

  - runs: |
      make
      install -Dm755 ./_output/nerdctl ${{targets.destdir}}/usr/bin/nerdctl

  - uses: strip

update:
  enabled: true
  github:
    identifier: containerd/nerdctl
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - containerd
        - iptables-nft
        - curl
        - coreutils
  pipeline:
    - name: "Start containerd and verify nerdctl"
      uses: test/daemon-check-output
      with:
        setup: |
          mkdir -p /etc/containerd
          cat > /etc/containerd/config.toml << EOF
          version = 2
          [plugins."io.containerd.grpc.v1.cri"]
            snapshotter = ""
          EOF
        start: containerd
        timeout: 30
        expected_output: |
          containerd successfully booted
        post: |
          nerdctl info
          # don't unpack, we're using a fake containerd
          nerdctl pull --unpack=false cgr.dev/chainguard/wolfi-base:latest
