package:
  name: neuvector-sigstore-interface
  version: "4.264"
  epoch: 0
  description: NeuVector sigstore interface for the SUSE NeuVector Container Security Platform
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "4"
    memory: 8Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - busybox
      - go-1.27

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neuvector/scanner
      tag: v${{package.version}}
      expected-commit: 382723bbec7a651f4c2658939c72f85a6dd27ac7

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/sigstore-interface
      output: sigstore-interface
      prefix: usr/local
      vendor: true
      go-package: go-1.27

  - uses: strip

test:
  pipeline:
    - runs: |
        sigstore-interface --help

update:
  enabled: true
  github:
    identifier: neuvector/scanner
    strip-prefix: v
    use-tag: true
