package:
  name: neuvector-scanner
  version: "4.123"
  epoch: 0 # GHSA-78h2-9frx-2jm8
  description: NeuVector vulnerability scanner for the SUSE NeuVector Container Security Platform
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates
      - neuvector-db
      - neuvector-scanner-monitor
      - neuvector-scanner-task
      - neuvector-sigstore-interface
  resources:
    cpu: "3"
    memory: 5Gi
  test-resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - busybox
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neuvector/scanner
      tag: v${{package.version}}
      expected-commit: ac97f7a2d68eecef1d8170e46fd9accc0e02cb8e

  - uses: go/bump
    with:
      deps: |-
        github.com/go-jose/go-jose/v4@v4.1.4

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: scanner
      prefix: usr/local
      vendor: true

  # Empty file that tells NV that the scanner is running in a container
  - runs: touch ${{targets.contextdir}}/usr/local/bin/.nvcontainer

  - uses: strip

subpackages:
  - name: ${{package.name}}-task
    description: NeuVector Scanner Task
    pipeline:
      - uses: go/build
        with:
          modroot: .
          packages: .
          output: scannerTask
          prefix: usr/local
          vendor: true
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: scannerTask

  # Need a separate monitor subpackage for neuvector/scanner/monitor different from neuvector/neuvector/monitor
  - name: ${{package.name}}-monitor
    description: NeuVector Scanner Monitor
    pipeline:
      - runs: |
          make -C monitor
          mkdir -p ${{targets.contextdir}}/usr/local/bin
          install -Dm755 monitor/monitor ${{targets.contextdir}}/usr/local/bin/monitor
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: monitor

test:
  pipeline:
    - runs: |
        if scanner --help | grep -q "usage: scan [OPTIONS]"; then
            exit 0
        fi

update:
  enabled: true
  git:
    tag-filter-prefix: v
    strip-prefix: v
