package:
  name: ngtcp2
  version: "1.21.0"
  epoch: 0
  description: ngtcp2 project is an effort to implement IETF QUIC protocol
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - libtool
      - openssl-dev
      - pkgconf-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ngtcp2/ngtcp2.git
      tag: v${{package.version}}
      expected-commit: 9e32add590fc74707b62f61aa5e0aa5c6f8a2c60
      recurse-submodules: true

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: Development dependencies and libraries for ${{package.name}}
    pipeline:
      - uses: split/dev
    test:
      environment:
        contents:
          packages:
            - build-base
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf
        - runs: |
            tee ver-check.c <<'EOF'
            #include <stdio.h>
            #include <ngtcp2/version.h>

            int main() {
              printf("%s", NGTCP2_VERSION);
              return 0;
            }
            EOF

            gcc -lngtcp2 ./ver-check.c -o ngtcp2-vercheck
        - uses: test/tw/ver-check
          with:
            bins: ./ngtcp2-vercheck

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
