package:
  name: nri-discovery-kubernetes
  version: "1.15.3"
  epoch: 1 # CVE-2026-78659
  description: New Relic Kubernetes Auto-Discovery
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.27

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-discovery-kubernetes
      expected-commit: 9cde66182d7114c9828386964ac7b7dab0ac9932
      tag: v${{package.version}}

  - uses: bump
    with:
      language: go
      deps: golang.org/x/net@v0.60.0

  - uses: go/build
    with:
      go-package: go-1.27
      modroot: .
      packages: ./cmd/discovery/
      output: nri-discovery-kubernetes

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/${{package.name}}
    # test added by a robot (compat)
    test:
      pipeline:
        - runs: |
            readlink -v /var/db/newrelic-infra/nri-discovery-kubernetes

update:
  enabled: true
  github:
    identifier: newrelic/nri-discovery-kubernetes
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        # We need a k8s cluster to do any more testing than this
        nri-discovery-kubernetes --help 2>&1 | grep -F "Usage of nri-discovery-kubernetes"
