package:
  name: ocaml-findlib
  version: "1.9.8"
  epoch: 0
  description: "OCaml library manager"
  copyright:
    - license: MIT
  resources:
    cpu: "2"
    memory: 4Gi
  dependencies:
    runtime:
      - ocaml

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ocaml
      - ocaml-compiler-libs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ocaml/ocamlfind
      tag: findlib-${{package.version}}
      expected-commit: bd9aad183f0d1c2caf3ec29e4f52bc69361f266d

  # This doesn't accept all of autoconf's standard options, so we can't use
  # the autoconf/configure pipeline.
  - runs: |
      ./configure \
        -config /etc/ocamlfind.conf \
        -bindir /usr/bin \
        -mandir /usr/share/man \
        -sitelib "$(ocamlc -where)" \
        -with-toolbox \
        -no-camlp4

  - uses: autoconf/make
    with:
      opts: all

  - uses: autoconf/make
    with:
      opts: opt

  - uses: autoconf/make-install

  - name: Remove package already provided by stdlib
    runs: rm -rf "${{targets.contextdir}}/usr/lib/ocaml/bytes"

  - uses: strip

subpackages:
  - name: ocamlfind
    dependencies:
      runtime:
        - ocaml-findlib
    pipeline:
      - uses: split/bin
    test:
      pipeline:
        # No --version flag or equivalent.
        - uses: test/tw/help-check
          with:
            bins: ocamlfind
            help-flag: ocamlc --help
        - uses: test/tw/ldd-check
        - uses: test/no-docs
        - name: Functional test
          runs: |
            ocamlfind list
            stdlib_path="$(ocamlfind query stdlib)"
            if [ "$stdlib_path" = /usr/lib/ocaml ]; then
              echo "PASS: 'ocamlfind query stdlib' produced sensible output"
            else
              echo "FAIL: 'ocamlfind query stdlib' produced '$stdlib_path', not '/usr/lib/ocaml'" >&2
              exit 1
            fi

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/no-docs
