package:
  name: openjph
  version: "0.27.3"
  epoch: 0 # go/wolfi-rsc/openjph
  description: Open source implementation of High-throughput JPEG2000 (HTJ2K)
  copyright:
    - license: BSD-2-Clause
  resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - build-base
      - tiff-dev

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+).*
    replace: $1
    to: soversion

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aous72/OpenJPH.git
      expected-commit: 2526a9203d6121ab318f557584fa53f7cd7affb0
      tag: ${{package.version}}

  - name: Configure shared build
    uses: cmake/configure
    with:
      output-dir: build-shared
      opts: |
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON

  - name: Build shared build
    uses: cmake/build
    with:
      output-dir: build-shared

  - name: Configure static build
    uses: cmake/configure
    with:
      output-dir: build-static
      opts: |
        -DBUILD_SHARED_LIBS=OFF \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON

  - name: Build static build
    uses: cmake/build
    with:
      output-dir: build-static

  - name: Install static build
    uses: cmake/install
    with:
      output-dir: build-static

  - name: Install shared build
    uses: cmake/install
    with:
      output-dir: build-shared

  - uses: strip

update:
  enabled: true
  github:
    identifier: aous72/OpenJPH

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

  - name: ${{package.name}}-static
    description: ${{package.name}} static libraries
    dependencies:
      runtime:
        - ${{package.name}}-dev=${{package.full-version}}
    pipeline:
      - uses: split/static
        with:
          package: "openjph-dev"
    test:
      pipeline:
        - uses: test/tw/staticpackage

  - name: lib${{package.name}}${{vars.soversion}}
    description: ${{package.name} libraries
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/*.so.* ${{targets.contextdir}}/usr/lib/
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check
    - name: Smoke tests
      runs: |
        set -o pipefail
        {
          ojph_compress || true
        } | grep -F -e "The following arguments are necessary"
        {
          ojph_expand || true
        } | grep -F -e "The following arguments are necessary"
