package:
  name: opentofu-1.11
  version: "1.11.6"
  epoch: 4 # GHSA-w8rr-5gcm-pp58
  copyright:
    - license: MPL-2.0
  dependencies:
    provides:
      - opentofu=${{package.full-version}}
  resources:
    cpu: "3"
    memory: 8Gi
  test-resources:
    cpu: "1"
    memory: 2Gi

environment:
  environment:
    CGO_ENABLED: 0
  contents:
    packages:
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 698e5e5204756963ffb28107fb61d77970e47f66
      repository: https://github.com/opentofu/opentofu
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        github.com/cloudflare/circl@v1.6.3
        google.golang.org/grpc@v1.79.3
        github.com/go-jose/go-jose/v4@v4.1.4
        go.opentelemetry.io/otel/sdk@v1.43.0
        github.com/hashicorp/go-getter@v1.8.6
        github.com/Azure/go-ntlmssp@v0.1.1
        github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.7.8
        github.com/aws/aws-sdk-go-v2/service/s3@v1.97.3
        go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp@v0.19.0
        go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp@v1.43.0
        go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp@v1.43.0

  - uses: go/build
    with:
      go-package: go-1.25
      ldflags: -X 'github.com/opentofu/opentofu/version.dev=no'
      modroot: .
      output: tofu
      packages: ./cmd/tofu

subpackages:
  - name: ${{package.name}}-compat
    description: Compat package for opentofu
    dependencies:
      provides:
        - opentofu-compat=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf ../../bin/tofu "${{targets.subpkgdir}}"/usr/local/bin/tofu
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/ver-check
          with:
            bins: tofu
            version: ${{package.version}}
        - uses: test/tw/help-check
          with:
            bins: tofu

  - name: ${{package.name}}-local-provider-config
    description: Configure opentofu to use local providers
    dependencies:
      provides:
        - opentofu-local-provider-config=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/opentofu/provider-mirror
          cat > "${{targets.subpkgdir}}"/opentofu/.opentofurc <<EOF
          provider_installation {
            filesystem_mirror {
              path    = "/opentofu/provider-mirror"
              include = ["*/*"]
            }
            direct {
              exclude = ["*/*"]
            }
          }
          EOF
    test:
      pipeline:
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: opentofu-local-provider-config
            real-pkg-name: ${{subpkg.name}}

update:
  enabled: true
  ignore-regex-patterns:
    - 'rc'
    - 'beta'
  github:
    identifier: opentofu/opentofu
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v1.11

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: tofu
        version: ${{package.version}}
    - uses: test/tw/help-check
      with:
        bins: tofu
    - name: tofu Initialization
      runs: |
        set -euo pipefail
        tee example.tf <<'EOF'
        provider "local" {}
        EOF
        tofu init -input=false
    - name: tofu Plan Creation
      runs: |
        set -euo pipefail
        tofu plan -input=false -out=tfplan
    - name: tofu Apply Execution
      runs: |
        set -euo pipefail
        tofu apply -input=false tfplan
