package:
  name: openpmix
  version: "6.1.0"
  epoch: 5
  description: Reference Implementation of the Process Management Interface Exascale (PMIx) standard
  copyright:
    - license: BSD-3-Clause-Open-MPI
  resources:
    cpu: "2"
    memory: 4Gi
  test-resources:
    cpu: "1"
    memory: 3Gi

vars:
  python-version: 3.13

environment:
  contents:
    packages:
      - build-base
      - busybox
      - flex
      - hwloc-dev
      - libevent-dev
      - libtool
      - libxml2-dev
      - perl
      - py${{vars.python-version}}-docutils
      - py${{vars.python-version}}-recommonmark
      - py${{vars.python-version}}-sphinx-bin
      - py${{vars.python-version}}-sphinx-rtd-theme

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openpmix/openpmix
      tag: v${{package.version}}
      expected-commit: ad8d0b75757819175b8d864114bcc65048bce4c3
      recurse-submodules: true
      cherry-picks: |
        master/03e066fbf2f002f167904f7bed4a54cd4b26f17b: Fix reporting of help from pmixcc

  - runs: |
      perl autogen.pl
      # Use release version
      # apk breaks with rc1 in version pc:pmix=5.0.3rc1
      sed -i 's/greek=.*/greek=/' VERSION
      chmod +x configure

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: openpmix-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    description: openpmix dev
    test:
      pipeline:
        - uses: test/tw/devpackage
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

  - name: openpmix-doc
    description: openpmix manpages
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/doc/
          cp LICENSE ${{targets.subpkgdir}}/usr/share/doc/${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  environment:
    contents:
      packages:
        - build-base
        - hwloc-dev
        - openpmix-dev
  pipeline:
    - uses: git-checkout
      with:
        repository: https://github.com/openpmix/openpmix
        tag: v${{package.version}}
        expected-commit: ad8d0b75757819175b8d864114bcc65048bce4c3
        recurse-submodules: true
    - uses: test/tw/ver-check
      with:
        bins: |
          palloc
          pattrs
          pevent
          plookup
          pmix_info
          pps
          pquery
    - uses: test/tw/help-check
      with:
        bins: |
          palloc
          pattrs
          pevent
          plookup
          pmix_info
          pps
          pquery
    - runs: |
        cd examples
        gcc hello.c $(pkg-config pmix --libs) -o hello
        ./hello
    - uses: test/tw/ldd-check

update:
  enabled: true
  github:
    identifier: openpmix/openpmix
    strip-prefix: v
    use-tag: true
