package:
  name: openssl-hardened-4.0-dev
  version: "4.0.2"
  epoch: 0
  description: the OpenSSL cryptography suite
  commit: 6b577e6bf909f4874694aa16659beae6778f42a4
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - openssl-4.0-dev
    replaces:
      - openssl-4.0-dev

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openssl/openssl
      tag: openssl-${{package.version}}
      expected-commit: f089acdf4bc7ba94a79f4bf6eb7362c3e7d14aa9

  - name: Configure and build
    runs: |
      perl ./Configure \
         --prefix=/usr \
         --libdir=lib \
         --openssldir=/etc/ssl \
         enable-brotli \
         enable-ec_nistp_64_gcc_128 \
         enable-ktls \
         enable-pie \
         no-aria \
         no-bf \
         no-camellia \
         no-cast \
         no-dtls1 \
         no-ec_explicit_curves \
         no-ec2m \
         no-gost \
         no-idea \
         no-integrity-only-ciphers \
         no-mdc2 \
         no-ocb \
         no-psk \
         no-pvkkdf \
         no-rc2 \
         no-rc4 \
         no-rc5 \
         no-rmd160 \
         no-seed \
         no-sm2 \
         no-sm2-precomp \
         no-sm3 \
         no-sm4 \
         no-srp \
         no-tls1 \
         no-tls1_1 \
         no-weak-ssl-ciphers \
         no-whirlpool \
         no-deprecated \
         -Wa,--noexecstack
      perl configdata.pm --dump

      mkdir -p ${{targets.destdir}}/usr/include/openssl
      # Configure as closely to the stock build as possible
      # And install just the configuration header
      cp include/openssl/configuration.h ${{targets.destdir}}/usr/include/openssl

update:
  enabled: true
  github:
    identifier: openssl/openssl
    strip-prefix: openssl-
    tag-filter-prefix: openssl-4.0.

test:
  pipeline:
    - uses: test/tw/contains-files
      with:
        files: /usr/include/openssl/configuration.h
