package:
  name: oras
  version: "1.3.2"
  epoch: 0 # CVE-2026-32280
  description: OCI registry client - managing content like artifacts, images, packages.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates
  resources:
    cpu: "2"
    memory: 4Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/oras-project/oras
      tag: v${{package.version}}
      expected-commit: fe425992fdfdf300a1cfb380bc4271b3e1a3d3db

  - uses: go/build
    with:
      go-package: go-1.26
      packages: ./cmd/oras/main.go
      output: oras
      ldflags: |
        -X oras.land/oras/internal/version.BuildMetadata=${{package.version}}
        -X oras.land/oras/internal/version.GitCommit=$(git rev-parse HEAD)
        -X oras.land/oras/internal/version.GitTreeState=$(git diff --quiet && echo clean || echo dirty)

update:
  enabled: true
  github:
    identifier: oras-project/oras
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: oras
    - uses: test/tw/ver-check
      with:
        bins: oras
    - name: some test commands
      runs: |
        oras manifest fetch cgr.dev/chainguard/wolfi-base:latest

environment:
  contents:
    packages:
      - go-1.26
