package:
  name: osv-scanner
  version: "2.3.3"
  epoch: 7 # GHSA-89xv-2j6f-qhc8
  description: Vulnerability scanner written in Go which uses the data provided by https://osv.dev
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "2"
    memory: 8Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b97d1de7d8c3c7de8c11308b3d9cb5bbf3f7a0e9
      tag: v${{package.version}}
      repository: https://github.com/google/osv-scanner

  - uses: go/bump
    with:
      deps: |-
        github.com/cloudflare/circl@v1.6.3
        github.com/docker/cli@v29.2.0
        google.golang.org/grpc@v1.79.3
        github.com/modelcontextprotocol/go-sdk@v1.4.1

  - uses: go/build
    with:
      packages: ./cmd/osv-scanner/
      output: osv-scanner

  - uses: go/build
    with:
      packages: ./cmd/osv-reporter/
      output: osv-reporter

update:
  enabled: true
  github:
    identifier: google/osv-scanner
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        osv-reporter --version
        osv-scanner --version
        osv-reporter --help
        osv-scanner --help | grep USAGE:
