package:
  name: perl-data-optlist
  version: "0.114"
  epoch: 2
  description: "Parse and validate simple name/value option pairs"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-params-util
      - perl-sub-install
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-dist-zilla
      - perl-params-util
      - perl-sub-install

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rjbs/Data-OptList
      tag: ${{package.version}}
      expected-commit: 070dad7013b66c81119899a8ae746a004f0a1930

  - uses: perl/dzil

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Data::OptList

update:
  enabled: true
  github:
    identifier: rjbs/Data-OptList
    use-tag: true
