package:
  name: perl-app-cmd
  version: "0.340"
  epoch: 2
  description: "Write command line apps with less suffering"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-capture-tiny
      - perl-class-load
      - perl-data-optlist
      - perl-getopt-long-descriptive
      - perl-io-tiecombine
      - perl-module-pluggable
      - perl-string-rewriteprefix
      - perl-sub-exporter
      - perl-sub-install
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-capture-tiny
      - perl-class-load
      - perl-data-optlist
      - perl-dist-zilla
      - perl-getopt-long-descriptive
      - perl-io-tiecombine
      - perl-module-pluggable
      - perl-string-rewriteprefix
      - perl-sub-exporter
      - perl-sub-install
      - perl-test-fatal

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rjbs/App-Cmd
      tag: ${{package.version}}
      expected-commit: 2587b6f18991899f0133826275931bd501765e4f

  - uses: perl/dzil

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: App::Cmd

update:
  enabled: true
  github:
    identifier: rjbs/App-Cmd
    use-tag: true
