package:
  name: perl-sub-exporter-globexporter
  version: "0.006"
  epoch: 0
  description: "Export shared globs with Sub::Exporter collectors"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-sub-exporter
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-sub-exporter

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Sub-Exporter-GlobExporter-${{package.version}}.tar.gz
      expected-sha256: de743f08026701c2a6a222a8b41c4cdc254b1a4afe7ef98987cd3aba4ce52696

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Sub::Exporter::GlobExporter

update:
  enabled: true
  release-monitor:
    identifier: 12556
