package:
  name: perl-type-tiny
  version: "2.010001"
  epoch: 0
  description: "Tiny, yet Moo(se)-compatible type constraint"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-exporter-tiny
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-exporter-tiny

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/Type-Tiny-${{package.version}}.tar.gz
      expected-sha256: cd583e4983039f35052d490f0c4439124ba667d4f09c4e3aec47de5200f9921a

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Type::Tiny Types::Standard

update:
  enabled: true
  release-monitor:
    identifier: 14406
