package:
  name: perl-sub-exporter-formethods
  version: "0.100055"
  epoch: 0
  description: "Helper routines for using Sub::Exporter to build methods"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-sub-exporter
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-namespace-autoclean
      - perl-sub-exporter

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Sub-Exporter-ForMethods-${{package.version}}.tar.gz
      expected-sha256: 791f4203ba7c0f7d8380bc01bec20215f7c8bc70d7ed03e552eee44541abe94e

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Sub::Exporter::ForMethods

update:
  enabled: true
  release-monitor:
    identifier: 14334
