package:
  name: perl-test-warnings
  version: "0.038"
  epoch: 0
  description: "Test for warnings and the lack of them"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - build-base
      - perl

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-Warnings-${{package.version}}.tar.gz
      expected-sha256: 3da27e003a3c3cafed3c09b42be05cf9bdbff0bee5c8590a731b02853880a273

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Test::Warnings

update:
  enabled: true
  release-monitor:
    identifier: 9157
