package:
  name: perl-string-errf
  version: "0.009"
  epoch: 0
  description: "A simple sprintf-like dialect"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-params-util
      - perl-string-formatter
      - perl-sub-exporter
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-date-format
      - perl-json-maybexs
      - perl-params-util
      - perl-string-formatter
      - perl-sub-exporter

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/String-Errf-${{package.version}}.tar.gz
      expected-sha256: e1fedbf9b4fd64b64ea81038ddb76a4c6cd85f5db15bc21f10656a298349dc1f

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: String::Errf

update:
  enabled: true
  release-monitor:
    identifier: 11607
