package:
  name: perl-class-inspector
  version: "1.36"
  epoch: 7 # go/wolfi-rsc/perl-class-inspector
  description: Class::Inspector perl module
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-module-install
  resources:
    cpu: "2"
    memory: 1Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev
      - perl-dist-zilla
      - perl-module-install

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/uperl/Class-Inspector
      tag: v${{package.version}}
      expected-commit: fab3613dfbc077b0289ec993084f323d364ce424

  - uses: perl/dzil

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-class-inspector-doc
    pipeline:
      - uses: split/manpages
    description: perl-class-inspector manpages
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/perl-module-check
      with:
        modules: Class::Inspector
    - uses: test/no-docs

update:
  enabled: true
  github:
    identifier: uperl/Class-Inspector
    strip-prefix: v
    tag-filter-prefix: v
    use-tag: true
