package:
  name: perl-moose
  version: "2.4000"
  epoch: 0
  description: "A postmodern object system for Perl 5"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-class-load
      - perl-class-load-xs
      - perl-data-optlist
      - perl-devel-globaldestruction
      - perl-devel-overloadinfo
      - perl-devel-stacktrace
      - perl-dist-checkconflicts
      - perl-eval-closure
      - perl-module-runtime
      - perl-module-runtime-conflicts
      - perl-mro-compat
      - perl-package-deprecationmanager
      - perl-package-stash
      - perl-package-stash-xs
      - perl-params-util
      - perl-sub-exporter
      - perl-try-tiny
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl-class-load
      - perl-class-load-xs
      - perl-cpan-meta-check
      - perl-data-optlist
      - perl-dev
      - perl-devel-globaldestruction
      - perl-devel-overloadinfo
      - perl-devel-stacktrace
      - perl-dist-checkconflicts
      - perl-eval-closure
      - perl-module-runtime
      - perl-module-runtime-conflicts
      - perl-mro-compat
      - perl-package-deprecationmanager
      - perl-package-stash
      - perl-package-stash-xs
      - perl-params-util
      - perl-sub-exporter
      - perl-test-fatal
      - perl-test-needs
      - perl-try-tiny

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Moose-${{package.version}}.tar.gz
      expected-sha256: c4bdcbe4daaeb50dcf40ea17dfb1483db22cb8832287abd8762a44ab98fb561f

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Moose

update:
  enabled: true
  release-monitor:
    identifier: 6197
