package:
  name: perl-mozilla-ca
  version: "20250602"
  epoch: 2 # go/wolfi-rsc/perl-mozilla-ca
  description: Mozilla's CA cert bundle in PEM format
  copyright:
    - license: MPL-2.0
  resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - ca-certificates-bundle
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libwww-perl/Mozilla-CA
      tag: v${{package.version}}
      expected-commit: d243d7c0c22e087882105d7e454343f49ffa58c8

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-mozilla-ca-doc
    pipeline:
      - uses: split/manpages
    description: perl-mozilla-ca manpages
    test:
      pipeline:
        - uses: test/docs

test:
  environment:
    contents:
      packages:
        - perl
  pipeline:
    - name: Test
      runs: |
        cat <<EOF > mozilla-ca.pl
        use strict;
        use warnings;

        eval {
            require Mozilla::CA;
            Mozilla::CA->import();
        };
        if (\$@) {
            print "Failed to load Mozilla::CA\n";
            exit 1;
        }
        EOF

        perl mozilla-ca.pl

update:
  enabled: true
  github:
    identifier: libwww-perl/Mozilla-CA
    strip-prefix: v
    tag-filter-prefix: v
