package:
  name: perl-class-load-xs
  version: "0.10"
  epoch: 1
  description: "XS implementation of parts of Class::Load"
  copyright:
    - license: Artistic-2.0
  dependencies:
    runtime:
      - perl
      - perl-class-load
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl-class-load
      - perl-dev
      - perl-module-implementation
      - perl-test-fatal
      - perl-test-needs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/moose/Class-Load-XS
      tag: v${{package.version}}
      expected-commit: db5348a07c7c5236d7e0db5ed7edb00206cf20d5

  - uses: perl/dzil

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Class::Load Class::Load::XS

update:
  enabled: true
  github:
    identifier: moose/Class-Load-XS
    use-tag: true
    tag-filter-prefix: v
    strip-prefix: v
