package:
  name: perl-class-method-modifiers
  version: "2.15"
  epoch: 0
  description: "Provides Moose-like method modifiers"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - build-base
      - perl

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Class-Method-Modifiers-${{package.version}}.tar.gz
      expected-sha256: 65cd85bfe475d066e9186f7a8cc636070985b30b0ebb1cde8681cf062c2e15fc

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Class::Method::Modifiers

update:
  enabled: true
  release-monitor:
    identifier: 6735
