#nolint:valid-pipeline-git-checkout-tag
package:
  name: perl-http-cookies
  version: "6.11"
  epoch: 6 # go/wolfi-rsc/perl-http-cookies
  description: HTTP cookie jars
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl-http-date
      - perl-http-message
  resources:
    cpu: "2"
    memory: 1Gi

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-http-date
      - perl-http-message

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libwww-perl/HTTP-Cookies
      branch: master
      expected-commit: be4df9f24ab117a98a6af0c7a27c42c59f2992d0

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-http-cookies-doc
    pipeline:
      - uses: split/manpages
    description: perl-http-cookies manpages
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs

update:
  enabled: true
  github:
    identifier: libwww-perl/HTTP-Cookies
    strip-prefix: v
    tag-filter-prefix: v
    use-tag: true
