package:
  name: perl-role-hasmessage
  version: "0.007"
  epoch: 0
  description: "A thing with a message method"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-moose
      - perl-moosex-role-parameterized
      - perl-namespace-clean
      - perl-string-errf
      - perl-try-tiny
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - perl
      - perl-moose
      - perl-moosex-role-parameterized
      - perl-namespace-clean
      - perl-string-errf
      - perl-try-tiny

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Role-HasMessage-${{package.version}}.tar.gz
      expected-sha256: 5e267a4d7620b368481204c88ea2044b8b2a58ff8b05577f2717b2754c0414ce

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Role::HasMessage

update:
  enabled: true
  release-monitor:
    identifier: 12554
