package:
  name: perl-string-errf
  version: "0.009"
  epoch: 1
  description: "A simple sprintf-like dialect"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-params-util
      - perl-string-formatter
      - perl-sub-exporter
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-date-format
      - perl-dist-zilla
      - perl-json-maybexs
      - perl-params-util
      - perl-string-formatter
      - perl-sub-exporter

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rjbs/String-Errf
      tag: ${{package.version}}
      expected-commit: e0a38b8ef9adb881d2e25a25f896bc4856a25bb4

  - uses: perl/dzil

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: String::Errf

update:
  enabled: true
  github:
    identifier: rjbs/String-Errf
    use-tag: true
