package:
  name: perl-net-snmp
  version: 6.0.1
  epoch: 6 # go/wolfi-rsc/perl-net-snmp
  description: Object oriented interface to SNMP
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  resources:
    cpu: "1"
    memory: 3Gi

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev
      - perl-module-build

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gitpan/Net-SNMP
      tag: gitpan_version/${{package.version}}
      expected-commit: 24e011863a38f113b00fb36ab08fc680a3628e18

  - runs: |
      export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
      PERL_MM_USE_DEFAULT=1 perl -I. Makefile.PL INSTALLDIRS=vendor
      make

  - runs: |
      make DESTDIR="${{targets.destdir}}" install
      find "${{targets.destdir}}" \( -name perllocal.pod -o -name .packlist \) -delete

  - uses: strip

subpackages:
  - name: perl-net-snmp-doc
    pipeline:
      - uses: split/manpages
    description: perl-net-snmp manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: gitpan/Net-SNMP
    strip-prefix: gitpan_version/
    tag-filter-prefix: gitpan_version/
    use-tag: true

test:
  pipeline:
    - uses: test/no-docs
