package:
  name: perl-string-formatter
  version: "1.235"
  epoch: 0
  description: "Build sprintf-like functions of your own"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - perl
      - perl-params-util
      - perl-sub-exporter
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-params-util
      - perl-sub-exporter

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/String-Formatter-${{package.version}}.tar.gz
      expected-sha256: 08236a913b911ce652cf08598e7c07d2df3f369fc47bf401a485a504a1660783

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: String::Formatter

update:
  enabled: true
  release-monitor:
    identifier: 12557
