package:
  name: perl-devel-overloadinfo
  version: "0.008"
  epoch: 0
  description: "Introspect overloaded operators"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-mro-compat
      - perl-package-stash

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-mro-compat
      - perl-package-stash
      - perl-test-fatal

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/I/IL/ILMARI/Devel-OverloadInfo-${{package.version}}.tar.gz
      expected-sha256: 91347d3a0b9a269180a3ea0e0d43f12c55dec3ddb974642f0e19093f907543d4

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Devel::OverloadInfo

update:
  enabled: true
  release-monitor:
    identifier: 12461
