package:
  name: perl-lwp-protocol-https
  version: "6.15"
  epoch: 1
  description: Provide https support for LWP::UserAgent
  copyright:
    - license: Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl-io-socket-ssl
      - perl-libwww
      - perl-net-http
  resources:
    cpu: "2"
    memory: 4Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libwww-perl/LWP-Protocol-https.git
      tag: v${{package.version}}
      expected-commit: fb24c7bbb2eb6a2cf764bf2686ef55b8e75380ef

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: ${{package.name}} docs
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - name: Smoke test
      runs: echo "use LWP::Protocol::https;" | perl
    - runs: |
        OUTPUT="$(mktemp)"
        perl <<'EOF' | tee "${OUTPUT}"
        use Data::Dumper;
        use LWP::UserAgent;

        $ua = LWP::UserAgent->new(ssl_opts => { verify_hostname => 1 });
        $res = $ua->get("https://www.example.com");

        $ua = LWP::UserAgent->new(
            ssl_opts => {
                SSL_ca_path     => '/etc/ssl/certs',
                verify_hostname => 1,
            }
        );
        print Dumper($ua);
        EOF

        grep -E -e "user-agent.*libwww-perl/[[:digit:]]*\.[[:digit:]]*" "${OUTPUT}"
        grep -F "HTTP::Cookies" "${OUTPUT}"
