package:
  name: perl-term-encoding
  version: "0.03"
  epoch: 0
  description: "Detect encoding of the current terminal"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - build-base
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/miyagawa/Term-Encoding
      tag: ${{package.version}}
      expected-commit: 27a2119821cd7eac09d00e82434eca8497f42578

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Term::Encoding

update:
  enabled: true
  github:
    identifier: miyagawa/Term-Encoding
    use-tag: true
