package:
  name: perl-moo
  version: "2.005005"
  epoch: 0
  description: "Minimalist Object Orientation (with Moose compatibility)"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-class-method-modifiers
      - perl-role-tiny
      - perl-sub-quote
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-class-method-modifiers
      - perl-role-tiny
      - perl-sub-quote

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/moose/Moo
      tag: v${{package.version}}
      expected-commit: 96cff3525cafb80630e0708863c0f332e6511185

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test TEST_FILES='t/*.t'

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Moo

update:
  enabled: true
  ignore-regex-patterns:
    - _
  github:
    identifier: moose/Moo
    use-tag: true
    tag-filter-prefix: v
    strip-prefix: v
