package:
  name: perl-io-socket-ssl
  version: "2.098"
  epoch: 0
  description: Nearly transparent SSL encapsulation for IO::Socket::INET
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - ca-certificates
      - perl
      - perl-mozilla-ca
      - perl-net-ssleay

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/noxxi/p5-io-socket-ssl
      tag: ${{package.version}}
      expected-commit: a589993ec972126fb9e9f93a137833b025f3b885

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-io-socket-ssl-doc
    pipeline:
      - uses: split/manpages
    description: perl-io-socket-ssl manpages
    test:
      pipeline:
        - uses: test/docs

test:
  environment:
    contents:
      packages:
        - ca-certificates
        - perl
        - perl-mozilla-ca
        - perl-net-ssleay
  pipeline:
    - name: Test
      runs: |
        cat <<EOF > socket-ssl.pl
        use strict;
        use warnings;

        eval {
          require IO::Socket::SSL;
          IO::Socket::SSL->import();
        };
        if (\$@) {
            print "Failed to load Socket::SSL\n";
            exit 1;
        }
        EOF

        perl socket-ssl.pl

update:
  enabled: true
  github:
    identifier: noxxi/p5-io-socket-ssl
    use-tag: true
