package:
  name: perl-test-subcalls
  version: "1.10"
  epoch: 1
  description: "Track the number of times subs are called"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-hook-lexwrap
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-dist-zilla
      - perl-hook-lexwrap

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/karenetheridge/Test-SubCalls
      tag: v${{package.version}}
      expected-commit: 06e1407950168e8ef92b9816083e20561d86d044

  - uses: perl/dzil

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Test::SubCalls

update:
  enabled: true
  github:
    identifier: karenetheridge/Test-SubCalls
    strip-prefix: v
    tag-filter-prefix: v
    use-tag: true
