package:
  name: perl-devel-findperl
  version: "0.016"
  epoch: 0
  description: "Find the path to your perl"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - build-base
      - perl

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/L/LE/LEONT/Devel-FindPerl-${{package.version}}.tar.gz
      expected-sha256: 43a2bf2f787a3f1b881179063162b2aa3e7cb044f6e5e76ec6466ae90a861138

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - name: Smoke test
      runs: |
        expected_perl="$(command -v perl)"
        cat >test.pl <<EOF
        use Devel::FindPerl qw(find_perl_interpreter);
        use Test::More tests => 1;
        ok(find_perl_interpreter() eq $expected_perl, 'Smoke test passed');
        EOF

update:
  enabled: true
  release-monitor:
    identifier: 2830
