package:
  name: perl-class-load-xs
  version: "0.10"
  epoch: 0
  description: "XS implementation of parts of Class::Load"
  copyright:
    - license: Artistic-2.0
  dependencies:
    runtime:
      - perl
      - perl-class-load
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl-class-load
      - perl-dev
      - perl-module-implementation
      - perl-test-fatal
      - perl-test-needs

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Class-Load-XS-${{package.version}}.tar.gz
      expected-sha256: 5bc22cf536ebfd2564c5bdaf42f0d8a4cee3d1930fc8b44b7d4a42038622add1

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Class::Load Class::Load::XS

update:
  enabled: true
  release-monitor:
    identifier: 11928
