package:
  name: perl-ppi
  version: "1.285"
  epoch: 0
  description: "Object representation of a Perl document"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-clone
      - perl-params-util
      - perl-safe-isa
      - perl-task-weaken
      - perl-yaml-pp
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-class-inspector
      - perl-clone
      - perl-dist-zilla
      - perl-params-util
      - perl-safe-isa
      - perl-task-weaken
      - perl-test-nowarnings
      - perl-test-object
      - perl-test-subcalls
      - perl-yaml-pp

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Perl-Critic/PPI
      tag: v${{package.version}}
      expected-commit: 884e89f1e1675cca2b9b23fd631da2f1dcc998d2

  - uses: perl/dzil

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: PPI

update:
  enabled: true
  github:
    identifier: Perl-Critic/PPI
    strip-prefix: v
    tag-filter-prefix: v
    use-tag: true
