package:
  name: perl-date-format
  version: "2.35"
  epoch: 0 # go/wolfi-rsc/perl-date-format
  description: Perl - Date formating subroutines
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/atoomic/perl-TimeDate
      tag: v${{package.version}}
      expected-commit: 080fe0d3fd9d79046db3c61e60ffe64ff02e1adb

  - runs: |
      PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-date-format-doc
    pipeline:
      - uses: split/manpages
    description: perl-date-format manpages
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - runs: perl -e "use Date::Format"
    - uses: test/no-docs

update:
  enabled: true
  ignore-regex-patterns:
    - _
  github:
    identifier: atoomic/perl-TimeDate
    strip-prefix: v
    tag-filter-prefix: v
    use-tag: true
