package:
  name: perl-sub-uplevel
  version: "0.2800"
  epoch: 2
  description: Apparently run a function in a higher stack frame
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
  resources:
    cpu: "2"
    memory: 4Gi

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Sub-Uplevel-${{package.version}}.tar.gz
      expected-sha256: b4f3f63b80f680a421332d8851ddbe5a8e72fcaa74d5d1d98f3c8cc4a3ece293

  - uses: perl/make

  - uses: autoconf/make

  - runs: make test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  release-monitor:
    identifier: 11903

test:
  pipeline:
    - name: Smoke test
      runs: |
        set -euo pipefail
        perl -e 'use Sub::Uplevel; print "Sub::Uplevel loaded successfully\n"'
