package:
  name: perl-sub-uplevel
  version: "0.2800"
  epoch: 3
  description: Apparently run a function in a higher stack frame
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
  resources:
    cpu: "2"
    memory: 4Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Perl-Toolchain-Gang/Sub-Uplevel
      tag: release-${{package.version}}
      expected-commit: 571c2bca8fd2feb59bdf102b38bd0f6d970278cb

  - uses: perl/make

  - uses: autoconf/make

  - runs: make test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: Perl-Toolchain-Gang/Sub-Uplevel
    strip-prefix: release-
    use-tag: true
    tag-filter-prefix: release-

test:
  pipeline:
    - name: Smoke test
      runs: |
        set -euo pipefail
        perl -e 'use Sub::Uplevel; print "Sub::Uplevel loaded successfully\n"'
