package:
  name: perl-getopt-long-descriptive
  version: "0.117"
  epoch: 0
  description: "Getopt::Long, but simpler and more powerful"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-params-validate
      - perl-sub-exporter
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-cpan-meta-check
      - perl-params-validate
      - perl-sub-exporter
      - perl-test-fatal
      - perl-test-warnings

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Getopt-Long-Descriptive-${{package.version}}.tar.gz
      expected-sha256: 18cba2392a0b7550bbc3d7c98c6fc5d81f6699d308e4a17e1a143ba4521005a3

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Getopt::Long::Descriptive

update:
  enabled: true
  release-monitor:
    identifier: 7110
