package:
  name: perl-dist-zilla
  version: "6.037"
  epoch: 0
  description: "Perl distribution builder"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-app-cmd
      - perl-config-ini
      - perl-config-mvp
      - perl-config-mvp-reader-ini
      - perl-cpan-uploader
      - perl-data-section
      - perl-datetime
      - perl-file-copy-recursive
      - perl-file-find-rule
      - perl-file-pushd
      - perl-file-sharedir
      - perl-file-sharedir-install
      - perl-json-maybexs
      - perl-log-dispatchouli
      - perl-moose
      - perl-moosex-lazyrequire
      - perl-moosex-role-parameterized
      - perl-moosex-setonce
      - perl-moosex-types
      - perl-moosex-types-perl
      - perl-path-tiny
      - perl-perl-prereqscanner
      - perl-ppi
      - perl-software-license
      - perl-sub-exporter
      - perl-term-encoding
      - perl-term-readkey
      - perl-term-ui
      - perl-test-deep
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl
      - perl-app-cmd
      - perl-config-ini
      - perl-config-mvp
      - perl-config-mvp-reader-ini
      - perl-cpan-meta-check
      - perl-cpan-uploader
      - perl-data-section
      - perl-datetime
      - perl-file-copy-recursive
      - perl-file-find-rule
      - perl-file-pushd
      - perl-file-sharedir
      - perl-file-sharedir-install
      - perl-json-maybexs
      - perl-log-dispatchouli
      - perl-moose
      - perl-moosex-lazyrequire
      - perl-moosex-role-parameterized
      - perl-moosex-setonce
      - perl-moosex-types
      - perl-moosex-types-perl
      - perl-path-tiny
      - perl-perl-prereqscanner
      - perl-ppi
      - perl-software-license
      - perl-sub-exporter
      - perl-term-encoding
      - perl-term-readkey
      - perl-term-ui
      - perl-test-deep
      - perl-test-failwarnings
      - perl-test-fatal
      - perl-test-file-sharedir

pipeline:
  - uses: fetch
    with:
      uri: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Dist-Zilla-${{package.version}}.tar.gz
      expected-sha256: 8c90db44bf09b11041761528edafb821669c87c154a757dd470608545a7dc75e

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make
    with:
      opts: test

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  environment:
    contents:
      packages:
        - make
  pipeline:
    - uses: test/tw/ver-check
      with:
        bins: dzil
    - uses: test/tw/help-check
      with:
        bins: dzil
    - uses: test/no-docs
    - name: Smoke test
      runs: |
        set -euo pipefail
        mkdir $HOME/.dzil
        cat >$HOME/.dzil/config.ini <<'EOF'
        [%User]
        name  = Wolfi User
        email = wolfi@example.com

        [%Rights]
        license_class    = Perl_5
        copyright_holder = Wolfi User
        EOF
        dzil new Wolfi::Test
        echo '# ABSTRACT: test module' >>Wolfi-Test/lib/Wolfi/Test.pm
        cd Wolfi-Test
        dzil test

update:
  enabled: true
  release-monitor:
    identifier: 5898
