package:
  name: perl-params-validate
  version: "1.31"
  epoch: 0
  description: "Validate method/function parameters"
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl
      - perl-module-implementation
  resources:
    cpu: "2"
    memory: 4Gi

environment:
  contents:
    packages:
      - build-base
      - perl-dev
      - perl-module-build
      - perl-module-implementation
      - perl-test-fatal
      - perl-test-requires

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/houseabsolute/Params-Validate
      tag: v${{package.version}}
      expected-commit: 7443735de1fb4d445e75a13ed8d890f366bed686

  - name: Build and test
    runs: |
      # Not using perl pipeline since it doesn't use Makefile.PL
      export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
      perl Build.PL --installdirs=vendor
      perl Build
      perl Build test

  - runs: |
      perl Build install --destdir=${{targets.destdir}}

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/alldocs
    description: Documentation for ${{package.name}}
    test:
      pipeline:
        - uses: test/docs

test:
  pipeline:
    - uses: test/no-docs
    - uses: test/perl-module-check
      with:
        modules: Params::Validate

update:
  enabled: true
  github:
    identifier: houseabsolute/Params-Validate
    use-tag: true
    tag-filter-prefix: v
    strip-prefix: v
