package:
  name: podinfo
  version: "6.11.2"
  epoch: 0 # go/wolfi-rsc/podinfo
  description: Podinfo is a tiny web application made with Go
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates
      - curl
      - netcat-openbsd
  resources:
    cpu: "1"
    memory: 6Gi
  test-resources:
    cpu: "1"
    memory: 2Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/stefanprodan/podinfo
      tag: ${{package.version}}
      expected-commit: b501abd1f0f2acf49c39f2d9cd47b460578d87f0

  - uses: go/build
    with:
      packages: ./cmd/podinfo
      output: podinfo
      go-package: go-1.26

  - runs: |
      mkdir -p ${{targets.contextdir}}/home/app
      cp -r ui ${{targets.contextdir}}/home/app/ui

subpackages:
  - name: podinfo-compat
    description: Compat package to add podinfo binary symlink
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/home/app
          ln -sf ../../usr/bin/podinfo ${{targets.contextdir}}/home/app/podinfo
          mkdir -p ${{targets.contextdir}}/usr/local/bin
          ln -sf ../../bin/podcli ${{targets.contextdir}}/usr/local/bin/podcli
    test:
      environment:
        contents:
          packages:
            - podinfo
            - podcli
      pipeline:
        - uses: test/tw/symlink-check

  - name: podcli
    description: CLI for podinfo
    dependencies:
      runtime:
        - podinfo
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/podcli
          output: podcli
          go-package: go-1.26
    test:
      pipeline:
        - uses: test/tw/ver-check
          with:
            bins: podcli
            version: ${{package.version}}

update:
  enabled: true
  github:
    identifier: stefanprodan/podinfo

test:
  environment:
    contents:
      packages:
        - wait-for-it
        - podinfo-compat
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: podinfo
        version: ${{package.version}}
    - name: Check application responds to --help command
      runs: /home/app/podinfo --help
    - name: Check UI file present
      runs: stat /home/app/ui/vue.html
    - name: Check API and UI
      uses: test/daemon-check-output
      working-directory: /home/app
      with:
        start: /home/app/podinfo
        timeout: 30
        expected_output: |
          Starting podinfo
          Starting HTTP Server
        post: |
          #!/bin/sh -e
          wait-for-it localhost:9898 --timeout=60
          curl -fsSL localhost:9898 | grep -F "greetings from podinfo"
          curl -fsSL -H "Accept: text/html" -A "Mozilla/5.0" localhost:9898 | grep -F "<html>"
