package:
  name: promxy
  version: "0.0.93"
  epoch: 17 # CVE-2026-33814
  description: An aggregating proxy to enable HA prometheus.
  copyright:
    - license: MIT
  dependencies:
    provides:
      # REMOVE_POST_USRMERGE - https://github.com/orgs/wolfi-dev/discussions/40270
      - promxy-compat=${{package.full-version}}
    runtime:
      - ca-certificates-bundle
      - merged-bin
      - wolfi-baselayout
  resources:
    cpu: "3"
    memory: 9Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jacksontj/promxy
      tag: v${{package.version}}
      expected-commit: 920021379e4e92044b1a0b17e32ee8124980cbfe

  - uses: bump
    with:
      deps: |-
        golang.org/x/net@v0.53.0
        golang.org/x/crypto@v0.45.0
        google.golang.org/grpc@v1.79.3
        github.com/docker/docker@v25.0.6+incompatible
        go.opentelemetry.io/otel@v1.41.0

  - uses: go/build
    with:
      packages: ./cmd/promxy
      tags: netgo,builtinassets
      output: promxy
      ldflags: |
        -X github.com/prometheus/common/version.Version=${{package.version}}
        -X github.com/prometheus/common/version.Revision=$(git rev-parse HEAD)
        -X github.com/prometheus/common/version.Branch=$(git branch --show-current)
        -X github.com/prometheus/common/version.BuildUser=melange
        -X github.com/prometheus/common/version.BuildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
      go-package: go-1.26

  - uses: go/build
    with:
      packages: ./cmd/remote_write_exporter
      output: remote_write_exporter
      go-package: go-1.26

update:
  enabled: true
  github:
    identifier: jacksontj/promxy
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
        - wait-for-it
  pipeline:
    - uses: test/tw/ver-check
      with:
        bins: promxy
        version: ${{package.version}}
    - uses: test/tw/help-check
      with:
        bins: remote_write_exporter
    - name: "start daemon on localhost"
      uses: test/daemon-check-output
      with:
        setup: |
          curl -sLO --retry 3 https://raw.githubusercontent.com/jacksontj/promxy/refs/heads/master/cmd/promxy/config.yaml
        start: "promxy --config config.yaml --log-level debug"
        timeout: 30
        expected_output: |
          promxy starting
        post: |
          wait-for-it -t 10 --strict localhost:8082 -- echo "Server is up"
          curl -s http://localhost:8082/metrics | grep -qi "prometheus_ready 1"

environment:
  contents:
    packages:
      - go-1.26
