package:
  name: pulumi-language-dotnet
  version: "3.103.1"
  epoch: 0 # GHSA-3xc5-wrhm-f963
  description: Pulumi Language SDK for Dotnet
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "1"
    memory: 7Gi

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f541a66a7671e934b8b041d7138b40ed4f125a40
      repository: https://github.com/pulumi/pulumi-dotnet.git
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        go.opentelemetry.io/otel/sdk@v1.43.0
        github.com/go-git/go-git/v5@v5.18.0
      modroot: |-
        integration_tests
        pulumi-language-dotnet

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.51.0
      modroot: sdk/Pulumi.Automation.Tests/Data/testproj

  - uses: go/build
    with:
      ldflags: -X github.com/pulumi/pulumi-language-dotnet/pkg/version.Version=v${{package.version}}
      modroot: pulumi-language-dotnet
      output: pulumi-language-dotnet
      packages: .

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-dotnet
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: pulumi-language-dotnet
