package:
  name: py3-pyjwt
  version: "2.13.0"
  epoch: 2
  description: JSON Web Token implementation in Python
  copyright:
    - license: MIT
  dependencies:
    provider-priority: "0"
  resources:
    cpu: "1"
    memory: 6Gi
  test-resources:
    cpu: "1"
    memory: 2Gi

data:
  - name: py-versions
    items:
      "3.10": "310"
      "3.11": "311"
      "3.12": "312"
      "3.13": "313"

vars:
  pypi-package: pyjwt
  import: jwt

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-supported-pip
      - py3-supported-setuptools
      - py3-supported-setuptools-scm
      - py3-supported-typing-extensions
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jpadilla/pyjwt
      tag: ${{package.version}}
      expected-commit: 7144e4534c34810f4525dc4578a32addd8212cff

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    pipeline:
      - name: Python Build
        uses: py/pip-build-install
        with:
          python: python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-typing-extensions
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    test:
      pipeline:
        - uses: test/tw/pip-check
        - name: Import Test
          uses: python/import
          with:
            import: ${{vars.import}}

update:
  enabled: true
  github:
    identifier: jpadilla/pyjwt

test:
  pipeline:
    - uses: test/tw/pip-check
    - name: Import Test
      uses: python/import
      with:
        import: ${{vars.import}}
