package:
  name: py3-typer-0.25
  version: "0.25.1"
  epoch: 0
  description: Typer, build great CLIs. Easy to code. Based on Python type hints.
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0
  resources:
    cpu: "1"
    memory: 1Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

vars:
  pypi-package: typer-0.25
  import: typer

environment:
  contents:
    packages:
      - py3-supported-build-base-dev
      - py3-supported-pdm-backend

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fastapi/typer.git
      tag: ${{package.version}}
      expected-commit: cfcc2ef9f948bcce67897a6c7e689d39da690bf9

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.import}} ${{package.version}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      runtime:
        - py${{range.key}}-annotated-doc
        - py${{range.key}}-click
        - py${{range.key}}-rich
        - py${{range.key}}-shellingham
        - py${{range.key}}-typing-extensions
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - name: "remove usr/bin executables; this is a library-only stream"
        runs: |
          rm -rf "${{targets.contextdir}}"/usr/bin
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}

update:
  enabled: true
  git:
    tag-filter-prefix: 0.25.

test:
  pipeline:
    - uses: test/tw/byproductpackage
