package:
  name: py3-backports.zstd
  version: 1.6.0
  epoch: 1 # go/wolfi-rsc/py3-backports.zstd
  description: Backport of CPython zstd module
  copyright:
    - license: PSF-2.0
  dependencies:
    provider-priority: 0
  resources:
    cpu: "2"
    memory: 6Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

vars:
  pypi-package: backports.zstd

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - build-base
      - py3-supported-pip
      - py3-supported-python-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7e15b44429444fc7e62516d263815141048fd3ee
      repository: https://github.com/rogdham/backports.zstd
      tag: v${{package.version}}
      recurse-submodules: true

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage

test:
  pipeline:
    - uses: python/import
      with:
        import: ${{vars.pypi-package}}

update:
  enabled: true
  git:
    strip-prefix: v
