package:
  name: py3-pycares
  version: 5.0.1
  epoch: 0
  description: Happy Eyeballs for pre-resolved hosts
  copyright:
    - license: PSF-2.0
  dependencies:
    provider-priority: 0
  resources:
    cpu: "5"
    memory: 7Gi

vars:
  pypi-package: pycares

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - build-base
      - c-ares-dev
      - cmake
      - py3-supported-build-base-dev
      - py3-supported-cffi
      - py3-supported-pip
  environment:
    PYCARES_USE_SYSTEM_LIB: 1

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/saghul/pycares
      tag: v${{package.version}}
      expected-commit: bb0074791dc103361e04eb0e9b2efc7e114b30c6

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-cffi
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/tw/pip-check
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import pycares

update:
  enabled: true
  github:
    identifier: saghul/pycares
    strip-prefix: v
    tag-filter-prefix: v
    use-tag: true
