package:
  name: py3-python-discovery
  version: "1.2.1"
  epoch: 0
  description: python-discovery finds the right Python version in your system
  copyright:
    - license: MIT

vars:
  pypi-package: python-discovery
  import: python_discovery

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-filelock
      - py3-supported-hatch-vcs
      - py3-supported-platformdirs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tox-dev/python-discovery
      expected-commit: 38eac12168b1837423b6c46ed5cdac4e30544f5d
      tag: ${{package.version}}

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      runtime:
        - py${{range.key}}-filelock
        - py${{range.key}}-platformdirs
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage

update:
  enabled: true
  github:
    identifier: tox-dev/python-discovery

test:
  pipeline:
    - uses: test/tw/byproductpackage
