package:
  name: py3.14-hatchling
  version: "1.29.0"
  epoch: 1
  description: Modern, extensible Python build backend
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py${{vars.py-version}}-packaging
      - py${{vars.py-version}}-pathspec
      - py${{vars.py-version}}-pluggy
      - py${{vars.py-version}}-tomli
      - py${{vars.py-version}}-trove-classifiers

vars:
  pypi-package: hatchling
  import: hatchling
  py-version: "3.14"

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py${{vars.py-version}}-build
      - py${{vars.py-version}}-installer
      - py${{vars.py-version}}-pathspec
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-pluggy
      - py${{vars.py-version}}-tomli
      - py${{vars.py-version}}-trove-classifiers
      - py${{vars.py-version}}-wheel
      - python-${{vars.py-version}}-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1a74daa6f554e2ec89f2641288e44ed39e5507cc
      repository: https://github.com/pypa/hatch
      tag: hatchling-v${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}
    working-directory: backend

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: ${{vars.import}}

update:
  enabled: true
  github:
    identifier: pypa/hatch
    strip-prefix: hatchling-v
    tag-filter: hatchling-v
