package:
  name: py3.14-flit-scm
  version: 1.7.0
  epoch: 1
  description: A PEP 518 build backend that uses setuptools_scm and flit_core
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py${{vars.py-version}}-flit-core
      - py${{vars.py-version}}-setuptools
      - py${{vars.py-version}}-setuptools-scm
      - py${{vars.py-version}}-tomli

vars:
  pypi-package: flit-scm
  import: flit_scm
  py-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py${{vars.py-version}}-flit-core
      - py${{vars.py-version}}-packaging
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-setuptools
      - py${{vars.py-version}}-setuptools-scm
      - py${{vars.py-version}}-tomli
      - py${{vars.py-version}}-wheel
      - python-${{vars.py-version}}-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/WillDaSilva/flit_scm.git
      expected-commit: 27ac37a0eabb46433b53b109a61576d4b712ddc0
      tag: ${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: ${{vars.import}}

update:
  enabled: true
  release-monitor:
    identifier: 250223
