package:
  name: py3.14-more-itertools
  version: "10.8.0"
  epoch: 0
  description: more routines for operating on iterables, beyond itertools
  copyright:
    - license: MIT

vars:
  pypi-package: more-itertools
  py-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.py-version}}-flit-core
      - py${{vars.py-version}}-pip
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/more-itertools/more-itertools.git
      tag: v${{package.version}}
      expected-commit: 8c1a6ef241b51ff055e89219f050ccf4f15f37f6

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: more_itertools

update:
  enabled: true
  github:
    identifier: more-itertools/more-itertools
    strip-prefix: v
