package:
  name: py3.14-hyperlink
  version: 21.0.0
  epoch: 1
  description: A featureful, immutable, and correct URL for Python.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py${{vars.python-version}}-idna
  resources:
    cpu: "2"
    memory: 5Gi

vars:
  python-version: 3.14
  pypi-package: hyperlink
  import: hyperlink

environment:
  contents:
    packages:
      - py${{vars.python-version}}-pip
      - python-${{vars.python-version}}-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-hyper/hyperlink
      tag: v${{package.version}}
      expected-commit: eae9223fafccfc4b32f8309bfe2b6817c3a88331

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}

update:
  enabled: true
  github:
    identifier: python-hyper/hyperlink
    use-tag: true
    strip-prefix: v
