package:
  name: py3.14-appnope
  version: "1.0.0"
  epoch: 0
  description: Disable App Nap on macOS >= 10.9
  copyright:
    - license: BSD-3-Clause
  resources:
    cpu: "3"
    memory: 4Gi

vars:
  pypi-package: appnope
  import: appnope
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-hatchling

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 3b529deea89a216e52a28ad6ac132613496822e9
      repository: https://github.com/minrk/appnope
      tag: ${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: minrk/appnope
    use-tag: true

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
