package:
  name: py3.14-trove-classifiers
  version: "2026.9.21.13"
  epoch: 0
  description: Canonical source for classifiers on PyPI (pypi.org).
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py${{vars.python-version}}-zipp

vars:
  pypi-package: trove-classifiers
  import: trove_classifiers
  python-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py${{vars.python-version}}-calver
      - py${{vars.python-version}}-pip
      - py${{vars.python-version}}-setuptools-scm
      - py${{vars.python-version}}-wheel
      - python-${{vars.python-version}}-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/trove-classifiers
      expected-commit: bc832553ebe6114e7682f09bc59bda6552da37cd
      tag: ${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        import: ${{vars.import}}

update:
  enabled: true
  github:
    identifier: pypa/trove-classifiers
