package:
  name: py3.14-cryptography
  version: "48.0.1"
  epoch: 0 # go/wolfi-rsc/py3.14-cryptography
  description: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
  copyright:
    - license: Apache-2.0 OR BSD-3-Clause
  dependencies:
    runtime:
      - openssl-provider-legacy
      - py3.14-cffi
      - py3.14-typing-extensions
  resources:
    cpu: "2"
    memory: 7Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

vars:
  py-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - maturin
      - openssl-dev
      - openssl-provider-legacy
      - py${{vars.py-version}}-cffi
      - py${{vars.py-version}}-maturin
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-setuptools
      - python-${{vars.py-version}}-base-dev
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pyca/cryptography/
      tag: ${{package.version}}
      expected-commit: de987ce48ccfeb1abca41efa23b2bf73ec704f74

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - uses: strip

test:
  environment:
    contents:
      packages:
        - openssl-provider-legacy
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        imports: |
          import cryptography
          import cryptography.hazmat.primitives.ciphers

update:
  enabled: true
  github:
    identifier: pyca/cryptography
    use-tag: true
