package:
  name: py3.14-psycopg
  version: "3.3.5"
  epoch: 0 # go/wolfi-rsc/py3.14-psycopg
  description: PostgreSQL database adapter for Python
  copyright:
    - license: LGPL-3.0-only
  dependencies:
    runtime:
      - libpq
      - py${{vars.python-version}}-typing-extensions
      - py${{vars.python-version}}-tzdata
  resources:
    cpu: "1"
    memory: 1Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

vars:
  pypi-package: psycopg
  import: psycopg
  python-version: "3.14"
  # The postgres version to run tests against
  postgres-version: '18'

environment:
  contents:
    packages:
      - busybox
      - py${{vars.python-version}}-pip
      - py${{vars.python-version}}-setuptools
      - py${{vars.python-version}}-wheel
      - python-${{vars.python-version}}-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/psycopg/psycopg
      tag: ${{package.version}}
      expected-commit: ea542c9534cc9841d50450e0c156b549cc6c805a

  - uses: py/pip-build-install
    working-directory: psycopg
    with:
      python: python${{vars.python-version}}

test:
  environment:
    contents:
      packages:
        - glibc-locales
        - libpq-${{vars.postgres-version}}
        - postgresql-${{vars.postgres-version}}
        - postgresql-${{vars.postgres-version}}-client
        - shadow
        - sudo-rs
    environment:
      PGDATA: /tmp/test_db
      PGUSER: wolfi
  pipeline:
    - uses: test/tw/pip-check
    - name: "Test database creation"
      runs: |
        useradd $PGUSER
        sudo -u $PGUSER initdb -D /tmp/test_db
        sudo -u $PGUSER pg_ctl -D /tmp/test_db -l /tmp/logfile start
        sudo -u $PGUSER createdb testdb
        psql -lqt | cut -d \| -f 1 | grep -qw testdb
    - name: "Test psycopg"
      runs: |
        cat <<'EOF' >> /tmp/test.py
        import psycopg

        def main():
            conn = psycopg.connect(dbname="testdb", user="wolfi")
            cursor = conn.cursor()

            try:
                # Create Table
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS example_table (
                        id SERIAL PRIMARY KEY,
                        message TEXT
                    )
                """)

                # Insert value
                cursor.execute("INSERT INTO example_table (message) VALUES (%s)", ("Hello Wolfy!",))
                conn.commit()

                # Select and print
                cursor.execute("SELECT message FROM example_table")
                result = cursor.fetchone()
                message = result[0].decode("utf-8")
                print("Message retrieved from database:", message)

            except Exception as e:
                print("Error:", e)

            finally:
                cursor.close()
                conn.close()

        if __name__ == "__main__":
            main()
        EOF

        python${{vars.python-version}} /tmp/test.py

update:
  enabled: true
  ignore-regex-patterns:
    - pool-*
    - 3.0.dev*
  github:
    identifier: psycopg/psycopg
    use-tag: true
