package:
  name: py3.14-sphinxcontrib-serializinghtml
  version: 2.0.0
  epoch: 0
  description: sphinxcontrib-serializinghtml is a sphinx extension which outputs "serialized" HTML files (json and pickle)
  copyright:
    - license: BSD-2-Clause
  resources:
    cpu: "2"
    memory: 4Gi

vars:
  pypi-package: sphinxcontrib-serializinghtml
  import: sphinxcontrib.serializinghtml
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-flit-core

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sphinx-doc/sphinxcontrib-serializinghtml
      expected-commit: f0f3b15b2e6bb47570d605ebd5687643d7a85b9d
      tag: ${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinxcontrib-serializinghtml

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          # import ${{vars.import}} # AVOID_DEP_CYCLE(sphinx)
