package:
  name: py3.14-astroid
  version: "4.3.1"
  epoch: 0
  description: A common base representation of python source code for pylint and other projects
  copyright:
    - license: LGPL-2.1-or-later
  dependencies:
    runtime:
      - py${{vars.python-version}}-typing-extensions

vars:
  pypi-package: astroid
  import: astroid
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pylint-dev/astroid
      tag: v${{package.version}}
      expected-commit: 4ea15d44c0e092296760c5bbaf4b3d1996a96779

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: pylint-dev/astroid
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
