package:
  name: py3.14-pkgconfig
  version: "1.6.0"
  epoch: 0
  description: Interface Python with pkg-config
  copyright:
    - license: MIT
  resources:
    cpu: "3"
    memory: 6Gi

vars:
  pypi-package: pkgconfig
  python-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.python-version}}-pip
      - py${{vars.python-version}}-poetry-core
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/matze/pkgconfig
      tag: v${{package.version}}
      expected-commit: 463480d0a0af629fed927b89ddcf2d406b22e337

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: matze/pkgconfig
    strip-prefix: v
    tag-filter-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        import: ${{vars.pypi-package}}
