package:
  name: py3.14-maturin
  version: "1.13.1"
  epoch: 3 # go/wolfi-rsc/py3.14-maturin
  description: Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
  copyright:
    - license: MIT OR Apache-2.0
  dependencies:
    runtime:
      - py3.14-tomli
  resources:
    memory: 9Gi
    cpu: "2"
  test-resources:
    cpu: "1"
    memory: 1Gi

vars:
  py-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-setuptools
      - py${{vars.py-version}}-setuptools-rust
      - py${{vars.py-version}}-wheel
      - python-${{vars.py-version}}-base-dev
      - rust-1.94

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b27b7e126148f373573fb029b05367dc62a5a0e6
      repository: https://github.com/pyo3/maturin
      tag: v${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: maturin

update:
  enabled: true
  ignore-regex-patterns:
    - beta
  github:
    identifier: pyo3/maturin
    strip-prefix: v
