package:
  name: py3.14-virtualenv
  version: "21.5.1"
  epoch: 0
  description: Virtual Python Environment builder
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py${{vars.python-version}}-distlib
      - py${{vars.python-version}}-filelock
      - py${{vars.python-version}}-importlib-metadata
      - py${{vars.python-version}}-platformdirs
      - py${{vars.python-version}}-python-discovery

vars:
  python-version: 3.14
  pypi-package: virtualenv

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py${{vars.python-version}}-hatch-vcs
      - py${{vars.python-version}}-hatchling
      - py${{vars.python-version}}-pip
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/virtualenv
      tag: ${{package.version}}
      expected-commit: e1db75c64ff11daa1574df5d1bf565b46ae6ec6e

  - uses: py/pip-build-install

  - uses: strip

test:
  pipeline:
    - runs: |
        virtualenv -h
        virtualenv --version
        virtualenv --help
    - uses: python/import
      with:
        import: ${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: pypa/virtualenv
    use-tag: true
