package:
  name: py3.14-azure-core
  version: "1.41.0"
  epoch: 0 # go/wolfi-rsc/py3-azure-core
  description: Microsoft Azure Core Library for Python
  copyright:
    - license: MIT
  resources:
    cpu: "5"
    memory: 8Gi
  dependencies:
    runtime:
      - py${{vars.python-version}}-requests
      - py${{vars.python-version}}-six
      - py${{vars.python-version}}-typing-extensions

vars:
  pypi-package: azure-core
  import: azure.core
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-pip

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d32e9734264a0d7dd8daceba6effc3514a8fffbd
      repository: https://github.com/Azure/azure-sdk-for-python
      tag: azure-core_${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}
    working-directory: sdk/core/azure-core

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}

update:
  enabled: true
  github:
    identifier: Azure/azure-sdk-for-python
    strip-prefix: azure-core_
    tag-filter: azure-core_
    use-tag: true
