package:
  name: py3.14-llhttp
  version: "9.3.0.0"
  epoch: 0
  description: llhttp in python
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 1Gi

vars:
  pypi-package: llhttp
  import: llhttp
  python-version: "3.14"

environment:
  contents:
    packages:
      - glibc-2.44-dev
      - py${{vars.python-version}}-build-base-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pallas/pyllhttp
      tag: v${{package.version}}
      expected-commit: 57b8568373583f239c03643bc8ec5b490ebad94b

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: pallas/pyllhttp
    use-tag: true
    tag-filter-prefix: v
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
