package:
  name: py3.14-boolean.py
  version: "5.0"
  epoch: 0
  description: Define boolean algebras, create and parse boolean expressions and create custom boolean DSL.
  copyright:
    - license: BSD-2-Clause
  resources:
    cpu: "2"
    memory: 5Gi

vars:
  pypi-package: boolean.py
  import: boolean
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bastikr/boolean.py
      tag: v${{package.version}}
      expected-commit: 8a443837e68dc027004294fb17fe1857cf783410

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  ignore-regex-patterns:
    - .*dev.*
  enabled: true
  github:
    identifier: bastikr/boolean.py
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
