package:
  name: py3.14-click-default-group
  version: "1.2.4"
  epoch: 0
  description: Extends click.Group to invoke a command without explicit subcommand name
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py${{vars.python-version}}-click
  resources:
    cpu: "2"
    memory: 4Gi

vars:
  pypi-package: click-default-group
  import: click_default_group
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-flit-core

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/click-contrib/click-default-group
      tag: v${{package.version}}
      expected-commit: 429c066978162c2cfabb14ea287aa6131413c324

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
