package:
  name: py3.14-logfmter
  version: "0.0.12"
  epoch: 0
  description: A Python package which supports global logfmt formatted logging.
  copyright:
    - license: MIT
  resources:
    cpu: "2"
    memory: 1Gi

vars:
  pypi-package: logfmter
  import: logfmter
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jteppinette/python-logfmter
      expected-commit: 587cb7f742eb4603b593182c8fb1e35e4a5f2368
      tag: v${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: jteppinette/python-logfmter
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
