package:
  name: py3.14-deprecated
  version: "3.0.0"
  epoch: 0
  description: Python @deprecated decorator to deprecate old python classes, functions or methods.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py${{vars.python-version}}-wrapt

vars:
  pypi-package: deprecated
  import: deprecated
  python-version: "3.14"

# deprecated 3.0.0 requires Python >= 3.12
environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.python-version}}-hatchling
      - py${{vars.python-version}}-pip
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 24b4b954c29e3783abab77a23e9f7cca1ca66491
      repository: https://github.com/tantale/deprecated
      tag: v${{package.version}}

  - name: Python Build
    uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

update:
  enabled: true
  github:
    identifier: tantale/deprecated
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - name: Import Test
      uses: python/import
      with:
        import: ${{vars.import}}
        python: python${{vars.python-version}}
