package:
  name: py3.14-terminado
  version: 0.18.1
  epoch: 0
  description: Tornado websocket backend for the Xterm.js Javascript terminal emulator library.
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - py${{vars.python-version}}-ptyprocess
      - py${{vars.python-version}}-tornado

vars:
  pypi-package: terminado
  import: terminado
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-hatchling

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 12b33b275e12e22cc3f772836d13043cb774ebe3
      repository: https://github.com/jupyter/terminado
      tag: v${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: jupyter/terminado
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
