package:
  name: py3.14-mdit-py-plugins
  version: "0.6.1"
  epoch: 0
  description: Collection of plugins for markdown-it-py
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py${{vars.python-version}}-markdown-it-py
  resources:
    cpu: "2"
    memory: 1Gi

vars:
  pypi-package: mdit-py-plugins
  import: mdit_py_plugins
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-flit-core

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/executablebooks/mdit-py-plugins
      expected-commit: da70e05b7630c38047d1921ef21d1aadc34c1ea9
      tag: v${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: executablebooks/mdit-py-plugins
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
