package:
  name: py3.14-tzlocal
  version: "5.4.4"
  epoch: 0
  description: tzinfo object for the local timezone
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py${{vars.python-version}}-tzdata
  resources:
    cpu: "3"
    memory: 5Gi

vars:
  pypi-package: tzlocal
  import: tzlocal
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/regebro/tzlocal
      tag: ${{package.version}}
      expected-commit: 42dfd052b5254e574dc9537c97ae50816ea74ece

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: regebro/tzlocal
    use-tag: true

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
