package:
  name: py3.14-pycparser
  version: "3.00"
  epoch: 5
  description: C parser in Python
  copyright:
    - license: BSD-3-Clause
  resources:
    cpu: "1"
    memory: 2Gi

vars:
  py-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.py-version}}-installer
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-pytest
      - py${{vars.py-version}}-setuptools
      - py${{vars.py-version}}-wheel
      - python-${{vars.py-version}}-base
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/eliben/pycparser
      tag: release_v${{package.version}}
      expected-commit: 77de509f0268f44ee587b5a4d9f0d680e269fcae

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - runs: |
      python${{vars.py-version}} -m pytest tests/

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: pycparser

update:
  enabled: true
  ignore-regex-patterns:
    - release_*
    - 1.x_final
  github:
    identifier: eliben/pycparser
    strip-prefix: release_v
    use-tag: true
