package:
  name: py3.14-pybind11
  version: "3.1.0"
  epoch: 0
  description: Seamless operability between C++11 and Python
  copyright:
    - license: BSD-3-Clause
  resources:
    cpu: "1"
    memory: 5Gi

vars:
  pypi-package: pybind11
  python-version: "3.14"

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - py${{vars.python-version}}-build
      - py${{vars.python-version}}-pip
      - py${{vars.python-version}}-scikit-build-core
      - py${{vars.python-version}}-setuptools
      - py${{vars.python-version}}-wheel
      - python-${{vars.python-version}}-base-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pybind/pybind11
      tag: v${{package.version}}
      expected-commit: 97bf890db679505a14dfe547a5e77bb2bd05dc90

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

subpackages:
  - name: ${{package.name}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{vars.python-version}}
    dependencies:
      runtime:
        - ${{package.name}}=${{package.full-version}}
    pipeline:
      - uses: split/bin
    test:
      pipeline:
        - runs: |
            pybind11-config --pkgconfigdir | grep -F /usr/lib/python${{vars.python-version}}
            pybind11-config --includes | grep -F /usr/lib/python${{vars.python-version}}
            pybind11-config --cmakedir | grep -F /usr/lib/python${{vars.python-version}}

update:
  enabled: true
  github:
    identifier: pybind/pybind11
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - py${{vars.python-version}}-${{vars.pypi-package}}=${{package.full-version}}
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        import: ${{vars.pypi-package}}
