package:
  name: py3.14-lru-dict
  version: "1.5.0"
  epoch: 0
  description: An Dict like LRU container.
  copyright:
    - license: MIT
  resources:
    cpu: "8"
    memory: 7Gi

vars:
  pypi-package: lru-dict
  import: lru
  python-version: "3.14"

environment:
  contents:
    packages:
      - glibc-2.44-dev
      - py${{vars.python-version}}-build-base-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/amitdev/lru-dict
      tag: v${{package.version}}
      expected-commit: 6b2ee068bd6465b8e9c5c53b7fcfc948888f41c0

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: amitdev/lru-dict
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
