package:
  name: py3.14-bracex
  version: "3.0.1"
  epoch: 0
  description: Bash style brace expander.
  copyright:
    - license: MIT

vars:
  pypi-package: bracex
  import: bracex
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-gpep517
      - py${{vars.python-version}}-hatchling
      - py${{vars.python-version}}-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/facelessuser/bracex
      tag: ${{package.version}}
      expected-commit: d46a882b94f91429de387e2fdbcbc74dbf1b6126

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: facelessuser/bracex
    strip-suffix: .post1

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
