package:
  name: py3.14-pyperclip
  version: "1.11.0"
  epoch: 1
  description: A cross-platform clipboard module for Python. (Only handles plain text for now.)
  copyright:
    - license: BSD-3-Clause

vars:
  python-version: "3.14"
  pypi-package: pyperclip
  import: pyperclip

environment:
  contents:
    packages:
      - busybox
      - py${{vars.python-version}}-pip
      - python-${{vars.python-version}}

pipeline:
  - uses: fetch
    with:
      expected-sha256: 244035963e4428530d9e3a6101a1ef97209c6825edab1567beac148ccc1db1b6
      uri: https://files.pythonhosted.org/packages/source/p/pyperclip/pyperclip-${{package.version}}.tar.gz

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        import: ${{vars.import}}

update:
  enabled: true
  release-monitor:
    identifier: 19701
