package:
  name: py3.14-packaging
  version: "26.1"
  epoch: 0
  description: core utilities for python3 packaging
  copyright:
    - license: Apache-2.0 AND BSD-2-Clause
  dependencies:
    runtime:
      - py${{vars.py-version}}-pyparsing

vars:
  pypi-package: packaging
  py-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.py-version}}-flit-core
      - py${{vars.py-version}}-pip
      - python-${{vars.py-version}}-base
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/packaging.git
      tag: ${{package.version}}
      expected-commit: c1a88a3e035e8bfe47dbc957f4a2493e8a7b4f3c

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        imports: |
          import ${{vars.pypi-package}}

update:
  enabled: true
  ignore-regex-patterns:
    - a
    - b
    - rc
    - post
  github:
    identifier: pypa/packaging
