package:
  name: py3.14-google-resumable-media
  version: "2.11.0"
  epoch: 0
  description: Utilities for Google Media Downloads and Resumable Uploads
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py${{vars.python-version}}-google-crc32c

vars:
  pypi-package: google-resumable-media
  import: google.resumable_media
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d6bed5a3d4a9348f6aebb75b7ceb8d599a133c0a
      repository: https://github.com/googleapis/google-cloud-python
      tag: google-resumable-media-v${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}
      prevent-inclusion: testing
    working-directory: packages/google-resumable-media

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: googleapis/google-cloud-python
    strip-prefix: google-resumable-media-v
    use-tag: true
    tag-filter-prefix: google-resumable-media-v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
