package:
  name: py3.14-packageurl-python
  version: "0.17.6"
  epoch: 0
  description: Python library to parse and build "purl" aka. Package URLs. See https://github.com/package-url/purl-spec for details.
  copyright:
    - license: MIT

vars:
  pypi-package: packageurl-python
  import: packageurl
  python-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-build-base-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/package-url/packageurl-python
      expected-commit: 04b755ccc388d6a53bb5277d1f95de4baa727deb
      tag: v${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: package-url/packageurl-python
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
