package:
  name: py3.14-chardet
  version: "6.0.0"
  epoch: 0
  description: Universal encoding detector for Python 3
  copyright:
    - license: LGPL-2.1-or-later
  resources:
    cpu: "2"
    memory: 4Gi

vars:
  pypi-package: chardet
  import: chardet
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-hatch-vcs
      - py${{vars.python-version}}-hatchling

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8a4636b1d4ef21d11cc8190f6ff271670b9d20ee
      repository: https://github.com/chardet/chardet
      tag: ${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - name: move usr/bin executables for -bin
    runs: |
      mkdir -p ./cleanup/${{vars.python-version}}/
      mv ${{targets.contextdir}}/usr/bin ./cleanup/${{vars.python-version}}/

  - uses: strip

update:
  enabled: true
  # License changed in 7.0.0
  ignore-regex-patterns:
    - 7\..*
  github:
    identifier: chardet/chardet

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
