package:
  name: py3.14-cachetools
  version: "7.1.0"
  epoch: 0
  description: Extensible memoizing collections and decorators
  copyright:
    - license: MIT

vars:
  pypi-package: cachetools
  import: cachetools
  py-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-setuptools
      - py${{vars.py-version}}-wheel
      - python-${{vars.py-version}}-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tkem/cachetools/
      tag: v${{package.version}}
      expected-commit: 1ea3422e058ef8b6b7dc15beb9d44d8f7c195a62

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: ${{vars.import}}

update:
  enabled: true
  ignore-regex-patterns:
    - b\d+$
  git:
    strip-prefix: v
