package:
  name: py3.14-tinycss2
  version: "1.5.1"
  epoch: 0
  description: A tiny CSS parser
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py${{vars.python-version}}-webencodings

vars:
  pypi-package: tinycss2
  import: tinycss2
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-flit-core

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Kozea/tinycss2
      tag: v${{package.version}}
      expected-commit: f295a49711a4d348664bba7fb34113b3b4b78cb2

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: Kozea/tinycss2
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
