package:
  name: py3.14-semver
  version: "3.1.0"
  epoch: 0
  description: Python helper for Semantic Versioning (https://semver.org)
  copyright:
    - license: BSD-3-Clause

vars:
  pypi-package: semver
  python-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.python-version}}-pip
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 642d1bc8949d38cca7922df478d0f2c06513f99d
      repository: https://github.com/python-semver/python-semver
      tag: ${{package.version}}

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - name: "move usr/bin executables for -bin"
    runs: |
      mkdir -p ./cleanup/${{vars.python-version}}/
      mv ${{targets.contextdir}}/usr/bin ./cleanup/${{vars.python-version}}/

  - uses: strip

update:
  enabled: true
  github:
    identifier: python-semver/python-semver

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        import: ${{vars.pypi-package}}
