package:
  name: py3.14-pyproject-metadata
  version: "0.11.0"
  epoch: 0
  description: PEP 621 metadata parsing
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py${{vars.py-version}}-packaging

vars:
  import: pyproject_metadata
  pypi-package: pyproject-metadata
  py-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.py-version}}-flit-core
      - py${{vars.py-version}}-pip
      - python-${{vars.py-version}}-base
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/pyproject-metadata
      tag: ${{package.version}}
      expected-commit: 7c346cf35ef116c6ee634951191b09695aec4d83

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: ${{vars.import}}

update:
  enabled: true
  ignore-regex-patterns:
    - a
    - b
    - rc
    - post
  github:
    identifier: pypa/pyproject-metadata
    use-tag: true
