package:
  name: py3.14-configargparse
  version: "1.7.7"
  epoch: 0
  description: A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables.
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 5Gi

vars:
  pypi-package: configargparse
  import: configargparse
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bw2/ConfigArgParse
      tag: v${{package.version}}
      expected-commit: 04fb885605a3aaa165b71c8f72fd7bbbc93ca469

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: bw2/ConfigArgParse
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
