package:
  name: py3.14-certifi
  version: "2026.02.25"
  epoch: 2 # go/wolfi-rsc/py3.14-certifi
  description: Python3 package for providing Mozilla's CA Bundle
  copyright:
    - license: MPL-2.0
  resources:
    cpu: "1"
    memory: 2Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

vars:
  pypi-package: certifi
  py-version: "3.14"

# certifi uses a special versioning scheme where the version is a date like "2023.07.22". During the
# build process, the version is "normalized" (and importantly, changed) to a form like "2023.7.22",
# which creates problems with vulnerability scanners, since vulnerability data for certifi is filed
# using its actual version numbers (the "2023.07.22" form). This transform creates the "normalized"
# version, so that we can use it when needed to update the version string back to its original form in
# the Python package's metadata.
var-transforms:
  - from: ${{package.version}}
    match: ([0-9]{4})\.0*([0-9]{1,2})\.0*([0-9]{1,2})
    replace: $1.$2.$3
    to: normalized-package-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-setuptools
      - py${{vars.py-version}}-wheel
      - python-${{vars.py-version}}-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/certifi/python-certifi.git
      tag: ${{package.version}}
      expected-commit: 8571a4ba5205675107f9026d0008ad2d7a2778bf

  - uses: patch
    with:
      patches: use-alpine-system-certs.patch

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - runs: |
      sed -i 's/Version: ${{vars.normalized-package-version}}/Version: ${{package.version}}/' "${{targets.destdir}}"/usr/lib/python${{vars.py-version}}/site-packages/certifi-${{vars.normalized-package-version}}.dist-info/METADATA

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: ${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: certifi/python-certifi
    use-tag: true
