package:
  name: py3.14-requests
  version: "2.32.5"
  epoch: 0
  description: Python HTTP for Humans.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py${{vars.py-version}}-certifi
      - py${{vars.py-version}}-charset-normalizer
      - py${{vars.py-version}}-idna
      - py${{vars.py-version}}-urllib3

vars:
  pypi-package: requests
  py-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py${{vars.py-version}}-flit-core
      - py${{vars.py-version}}-pip
      - python-${{vars.py-version}}-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/psf/requests.git
      tag: v${{package.version}}
      expected-commit: b25c87d7cb8d6a18a37fa12442b5f883f9e41741

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: ${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: psf/requests
    strip-prefix: v
    tag-filter: v
