package:
  name: py3.14-pyproject-hooks
  version: 1.2.0
  epoch: 0
  description: A low-level library for calling build-backends in `pyproject.toml`-based project
  copyright:
    - license: MIT

vars:
  import: pyproject_hooks
  pypi-package: pyproject-hooks
  py-version: "3.14"

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py${{vars.py-version}}-flit-core
      - py${{vars.py-version}}-pip
      - python-${{vars.py-version}}-base
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/pyproject-hooks
      tag: v${{package.version}}
      expected-commit: 4b7c6d113fb89b755d762a88712c8a6873cddd47

  - uses: py/pip-build-install
    with:
      python: python${{vars.py-version}}

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        python: python${{vars.py-version}}
        import: ${{vars.import}}

update:
  enabled: true
  ignore-regex-patterns:
    - a
    - b
    - rc
    - post
  github:
    identifier: pypa/pyproject-hooks
    use-tag: true
    strip-prefix: v
