package:
  name: py3.14-hatch-jupyter-builder
  version: "0.10.0"
  epoch: 0
  description: A hatch plugin to help build Jupyter packages
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py${{vars.python-version}}-hatchling
  resources:
    cpu: "1"
    memory: 3Gi

vars:
  pypi-package: hatch-jupyter-builder
  import: hatch_jupyter_builder
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-hatchling

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jupyterlab/hatch-jupyter-builder
      tag: v${{package.version}}
      expected-commit: da3d0e99fcf19a13dd32c22d38675009314d7029

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - name: move usr/bin executables for -bin
    runs: |
      mkdir -p ./cleanup/${{vars.python-version}}/
      mv ${{targets.contextdir}}/usr/bin ./cleanup/${{vars.python-version}}/

  - uses: strip

update:
  enabled: true
  github:
    identifier: jupyterlab/hatch-jupyter-builder
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
