package:
  name: py3.13-conda-package-streaming
  version: "0.13.0"
  epoch: 0
  description: An efficient library to read from new and old format .conda and .tar.bz2 conda packages.
  copyright:
    - license: BSD-3-Clause

vars:
  pypi-package: conda-package-streaming
  import: conda_package_streaming
  python-version: '3.13'

environment:
  contents:
    packages:
      - busybox
      - py3-supported-flit-core
      - python-${{vars.python-version}}-base-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/conda/conda-package-streaming
      tag: v${{package.version}}
      expected-commit: f362d306cbc3e348b1661bbf45be38f426829326

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        import: ${{vars.import}}

update:
  enabled: true
  github:
    identifier: conda/conda-package-streaming
    strip-prefix: v
