package:
  name: py3.14-pymysql
  version: "1.2.3"
  epoch: 0
  description: Pure Python MySQL Driver
  copyright:
    - license: MIT
  resources:
    cpu: "2"
    memory: 5Gi

vars:
  pypi-package: pymysql
  import: pymysql
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base
      - py${{vars.python-version}}-gpep517

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/PyMySQL/PyMySQL
      tag: v${{package.version}}
      expected-commit: c990e86083c26493f3285b1e047902994c4b1811

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - pymysql-*
  github:
    identifier: PyMySQL/PyMySQL
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: test/populated-etc-passwd
      with:
        content: |
          # import of pymysql users 'getuser' which requires either USER set in environment
          # or population of /etc/passwd.  This pipeline's modification lives in bwrap runner
          # to the next import test.  It is not necessary in docker runner.
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
