package:
  name: py3.14-idna
  version: "3.19"
  epoch: 0
  description: Internationalized Domain Names in Applications (IDNA)
  copyright:
    - license: BSD-3-Clause

vars:
  pypi-package: idna
  import: idna
  python-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py${{vars.python-version}}-flit-core
      - py${{vars.python-version}}-pip
      - python-${{vars.python-version}}-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kjd/idna.git
      tag: v${{package.version}}
      expected-commit: 03a9a11dd8aecd4fea742cabe20f4d3d9ed82abb

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

test:
  pipeline:
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        import: ${{vars.import}}

update:
  enabled: true
  github:
    identifier: kjd/idna
    strip-prefix: v
    tag-filter-prefix: v
