package:
  name: py3.14-pip-tools
  version: "7.6.1"
  epoch: 0
  description: A set of command line tools to help you keep your pip-based packages fresh, even when you've pinned them.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py${{vars.python-version}}-build
      - py${{vars.python-version}}-click
      - py${{vars.python-version}}-pip-base

vars:
  pypi-package: pip-tools
  import: piptools
  python-version: "3.14"

environment:
  contents:
    packages:
      - py${{vars.python-version}}-build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jazzband/pip-tools
      tag: v${{package.version}}
      expected-commit: 5bc5ded0b685637d6dffb926c00829220b4c6834

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - name: move usr/bin executables for -bin
    runs: |
      mkdir -p ./cleanup/${{vars.python-version}}/
      mv ${{targets.contextdir}}/usr/bin ./cleanup/${{vars.python-version}}/

  - uses: strip

update:
  enabled: true
  github:
    identifier: jazzband/pip-tools
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        imports: |
          import ${{vars.import}}
