package:
  name: py3.14-wrapt
  version: "2.5.0"
  epoch: 0
  description: Module for decorators, wrappers and monkey patching.
  copyright:
    - license: BSD-2-Clause
  dependencies:
  resources:
    cpu: "1"
  test-resources:
    cpu: "1"
    memory: 1Gi

vars:
  module_name: wrapt
  pypi-package: wrapt
  python-version: "3.14"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.python-version}}-pip
      - py${{vars.python-version}}-setuptools
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GrahamDumpleton/wrapt
      tag: ${{package.version}}
      expected-commit: 6c0f913b93927925dd27ea7191524e9e69ff4771

  - name: Python Build
    uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

update:
  enabled: true
  github:
    identifier: GrahamDumpleton/wrapt
    strip-prefix: wrapt-

test:
  pipeline:
    - uses: test/tw/pip-check
    - name: Import Test
      uses: python/import
      with:
        import: ${{vars.module_name}}
        python: python${{vars.python-version}}
