package:
  name: pylint
  version: "4.0.6"
  epoch: 0 # fix runtime deps and add pip-check/import tests
  description: A static code analyser for Python 2 and 3
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - py${{vars.python-version}}-astroid
      - py${{vars.python-version}}-dill
      - py${{vars.python-version}}-isort
      - py${{vars.python-version}}-mccabe
      - py${{vars.python-version}}-platformdirs
      - py${{vars.python-version}}-tomlkit
      - python-${{vars.python-version}}-base
  resources:
    cpu: "1"
    memory: 5Gi

vars:
  python-version: 3.13

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py${{vars.python-version}}-build-base
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pylint-dev/pylint
      tag: v${{package.version}}
      expected-commit: 8a396357098337ba8be714fffdf2d00947a9778c

  - uses: py/pip-build-install
    with:
      python: python${{vars.python-version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: pylint-dev/pylint
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -euo pipefail
        pylint --version | grep ${{package.version}}
        pylint --help
        pylint-config --version
        pyreverse --version
        pyreverse --help
        symilar --help
    - uses: test/tw/pip-check
    - uses: python/import
      with:
        python: python${{vars.python-version}}
        import: pylint
