package:
  name: rancher-ui-2.10
  version: "2.10.3"
  epoch: 0
  description: Rancher UI
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - git
      - node-gyp
      - nodejs-22
      - npm
      - perl
      - py3.10-gyp-next-bin
      - python-3.10
      - yarn
  environment:
    CI_BRANCH: ${{package.version}}
    CI_BUILD_TAG: ${{package.version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/ui
      tag: v${{package.version}}
      expected-commit: b7670e7ae50a63e95feb0926ef2744d46dcab2a1
      recurse-submodules: true

  - runs: |
      PYTHON=/usr/bin/python3 yarn install
      # Add a Yarn resolutions entry to force "node-sass" to version "8.0.0"
      jq '.resolutions += [{"node-sass": "8.0.0"}]' package.json > tmp.json && mv tmp.json package.json
      # Reinstall dependencies so that the new resolution takes effect,
      # ensuring that node-sass 8.0.0 (which uses a Python3-friendly node-gyp) is used.
      yarn install
      ./scripts/update-dependencies
      yarn build-static -f -v ${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: rancher/ui
    strip-prefix: v
    tag-filter: v2.10.
    use-tag: true
