#nolint:git-checkout-must-use-github-updates,valid-pipeline-git-checkout-tag
package:
  name: rancher-kontainer-driver-metadata-2.14
  version: "0_git20260629"
  epoch: 0 # go/wolfi-rsc/rancher-kontainer-driver-metadata-2.14
  description: Complete container management platform - kontainer driver metadata
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - rancher-kontainer-driver-metadata=${{package.full-version}}
  resources:
    cpu: "1"
    memory: 1Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/kontainer-driver-metadata
      branch: release-v2.14
      expected-commit: 6911e584067946f43d3e812670891f112de7f19c

  - runs: |
      mkdir -p ${{targets.contextdir}}/var/lib/rancher-data/driver-metadata
      install -Dm644 data/data.json ${{targets.contextdir}}/var/lib/rancher-data/driver-metadata/data.json

test:
  pipeline:
    - uses: test/tw/contains-files
      with:
        dir: /var/lib/rancher-data/driver-metadata/

update:
  enabled: true
  git: {}
  schedule:
    period: daily
    reason: Commit at head of branch moves frequently
