package:
  name: rekor
  version: "1.5.1"
  epoch: 12 # GHSA-pmwq-pjrm-6p5r
  description: Software Supply Chain Transparency Log
  copyright:
    - license: Apache-2.0
  checks:
    disabled:
      - empty
  resources:
    cpu: "2"
    memory: 8Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - busybox
      - git
      - go-1.26

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/rekor
      tag: v${{package.version}}
      expected-commit: bb573aab48ad294657cb4f1e8e0dabe1d2a77f69

  - uses: bump
    with:
      deps: |-
        golang.org/x/net@v0.53.0
        google.golang.org/grpc@v1.79.3
        github.com/go-jose/go-jose/v4@v4.1.4
        go.opentelemetry.io/otel/sdk@v1.43.0
        github.com/aws/aws-sdk-go-v2/service/s3@v1.97.3
        golang.org/x/crypto@v0.50.0
        github.com/in-toto/in-toto-golang@v0.11.0

subpackages:
  - name: ${{package.name}}-server
    pipeline:
      - uses: go/build
        with:
          modroot: .
          packages: ./cmd/rekor-server
          output: rekor-server
          go-package: go-1.26
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: rekor-server
            expect-contains: "Rekor fulfills the signature transparency role"

  - name: ${{package.name}}-cli
    pipeline:
      - uses: go/build
        with:
          modroot: .
          packages: ./cmd/rekor-cli
          output: rekor-cli
          go-package: go-1.26
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: rekor-cli
            expect-contains: "Rekor command line interface tool"

  - name: ${{package.name}}-backfill-index
    pipeline:
      - uses: go/build
        with:
          modroot: .
          packages: ./cmd/backfill-index
          output: backfill-index
          go-package: go-1.26
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: backfill-index
            expect-contains: "Usage of backfill-index:"

update:
  enabled: true
  github:
    identifier: sigstore/rekor
    strip-prefix: v

test:
  pipeline:
    - uses: test/emptypackage
