package:
  name: rootlesskit
  version: "3.0.2"
  epoch: 0 # GO-2026-5856
  description: RootlessKit is a Linux-native implementation of "fake root" using user_namespaces(7).
  copyright:
    - license: Apache-2.0
  dependencies:
    # Let's ensure that we have config. This gets the default, but can also
    # be overridden by users.
    runtime:
      - rootlesskit-config
  resources:
    cpu: "1"
    memory: 5Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rootless-containers/rootlesskit
      expected-commit: 19f94521be524ae7b61e380a814d2aa0a3ef40a9
      tag: v${{package.version}}

  - uses: go/build
    with:
      output: rootlesskit
      packages: ./cmd/rootlesskit
      go-package: go-1.26

  - uses: go/build
    with:
      output: rootlessctl
      packages: ./cmd/rootlessctl
      go-package: go-1.26

  - uses: go/build
    with:
      output: rootlesskit-docker-proxy
      packages: ./cmd/rootlesskit-docker-proxy
      go-package: go-1.26

  - uses: strip

subpackages:
  - name: "rootlesskit-config-nonroot"
    description: Rootlesskit config for nonroot user
    dependencies:
      runtime:
        - rootlesskit
      provides:
        - rootlesskit-config=${{package.full-version}}
    pipeline:
      # See https://rootlesscontaine.rs/getting-started/common/subuid/
      - runs: |
          mkdir -p ${{targets.destdir}}/etc
          echo "nonroot:100000:65536" > ${{targets.destdir}}/etc/subuid
          echo "nonroot:100000:65536" > ${{targets.destdir}}/etc/subgid
    test:
      pipeline:
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: rootlesskit-config
            real-pkg-name: ${{subpkg.name}}

update:
  enabled: true
  github:
    identifier: rootless-containers/rootlesskit
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - name: Test rootlesskit core functionality
      runs: |
        rootlesskit --version
        rootlessctl --version
        stat /usr/bin/rootlesskit-docker-proxy

environment:
  contents:
    packages:
      - go-1.26
