#nolint:valid-pipeline-git-checkout-tag
package:
  name: ruby3.4-validate_url
  version: 1.0.15
  epoch: 4 # go/wolfi-rsc/ruby3.4-validate_url
  description: Library for validating urls in Rails.
  dependencies:
    runtime:
      - ruby${{vars.rubyMM}}-activemodel
      - ruby${{vars.rubyMM}}-public_suffix
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  # validate_url stopped tagging releases after 1.0.5; pin master to the
  # commit corresponding to the current release.
  - uses: git-checkout
    with:
      repository: https://github.com/perfectline/validates_url
      branch: master
      expected-commit: 9c8a33558bba162fcc8c23732ba5b6e47fceaf86

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: validate_url

update:
  enabled: false

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

test:
  pipeline:
    - uses: test/tw/gem-check
