package:
  name: ruby3.2-ostruct
  version: 0.6.3
  epoch: 0
  description: An OpenStruct is a data structure, similar to a Hash, that allows the definition of arbitrary attributes with their accompanying values.
  copyright:
    - license: MIT AND Ruby

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d6302c72278d7ca01b4a2d7631e7b98e9aedee24
      repository: https://github.com/ruby/ostruct
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: ostruct

test:
  environment:
    contents:
      packages:
        - ruby-${{vars.rubyMM}}
  pipeline:
    - name: Verify that library loads
      runs: |
        ruby -e "require 'ostruct'; puts 'Successfully loaded ostruct library'"
    - name: Simple test
      runs: |
        ruby <<-EOF
        require "ostruct"

        person = OpenStruct.new
        person.name = "John Smith"
        person.age  = 70

        puts person.name      # => "John Smith"
        puts person.age       # => 70
        puts person.address   # => nil
        EOF

update:
  enabled: true
  git:
    strip-prefix: v
    tag-filter-prefix: v

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM
