package:
  name: ruby4.0-oj
  version: "3.17.1"
  epoch: 0 # go/wolfi-rsc/ruby4.0-oj
  description: The fastest JSON parser and object serializer.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-${{vars.rubyMM}}
  resources:
    cpu: "1"
    memory: 4Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

vars:
  gem: oj

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4587e87e23adc9a4163834dc8c9ba9d7206c6501
      repository: https://github.com/ohler55/oj
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: ohler55/oj
    strip-prefix: v
    use-tag: true

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

test:
  pipeline:
    - uses: test/tw/gem-check
      with:
        require: |
          oj
          oj/bag
          oj/easy_hash
          oj/error
          oj/json
          oj/mimic
          oj/saj
          oj/schandler
          oj/state
          oj/version
    - uses: test/tw/ldd-check
