package:
  name: ruby4.0-timeout
  version: "0.6.1"
  epoch: 0 # go/wolfi-rsc/ruby4.0-timeout
  description: Auto-terminate potentially long-running operations in Ruby.
  copyright:
    - license: Ruby
    - license: BSD-2-Clause
  resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 951e8025ec02cce2d1c9dc5712c1ab37e383bd54
      repository: https://github.com/ruby/timeout
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: timeout

update:
  enabled: true
  github:
    identifier: ruby/timeout
    strip-prefix: v

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM

test:
  pipeline:
    - uses: test/tw/gem-check
