package:
  name: ruby3.4-protocol-http
  version: "0.62.0"
  epoch: 0 # go/wolfi-rsc/ruby3.4-protocol-http
  description: Provides abstractions to handle HTTP protocols.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-${{vars.rubyMM}}
  resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

vars:
  gem: protocol-http

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d8b5f53ccb3ba4969cad8eadcbedd9ca831e4ba9
      repository: https://github.com/socketry/protocol-http
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/protocol-http
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - uses: test/tw/gem-check
      with:
        require: protocol/http
    - name: Test Functionality
      runs: |
        ruby -r 'protocol/http' -e '
        request = Protocol::HTTP::Request.new(nil, nil, "GET", "/")
        request.headers.add("content-type", "application/json")
        puts "Content-Type Header: " + request.headers["content-type"]
        ' | grep -F "Content-Type Header: application/json"

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM
