package:
  name: ruff
  version: "0.15.10"
  epoch: 0 # GHSA-xphw-cqx3-667j
  description: An extremely fast Python linter, written in Rust.
  copyright:
    - license: MIT
  resources:
    cpu: "19"
    memory: 24Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - clang-${{vars.clang-version}}
      - rust-1.94

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/astral-sh/ruff
      tag: ${{package.version}}
      expected-commit: 252f76102a618bff6537b6c53c316ca3837f4abf

  - uses: rust/cargobump

  - uses: cargo/build
    with:
      output: ruff

  - uses: strip

subpackages:
  - name: ruff-python-formatter
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          ls target/release/
          mv target/release/ruff_python_formatter ${{targets.subpkgdir}}/usr/bin/
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: ruff_python_formatter

update:
  enabled: true
  github:
    identifier: astral-sh/ruff

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: ruff
    - uses: test/tw/help-check
      with:
        bins: ruff
    - name: Lint a Python file
      runs: |
        echo 'print("Hello, world!")' > test.py
        ruff check test.py || exit 1
    - name: Lint with specific rules
      runs: |
        echo 'print("Hello, world!")' > test.py
        ruff check --select F401 test.py || exit 1

vars:
  clang-version: 22
