package:
  name: runc
  version: "1.4.2"
  epoch: 3 # CVE-2026-33814
  description: CLI tool for spawning and running containers according to the OCI specification
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "2"
    memory: 2Gi

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-1.26
      - go-md2man
      - libseccomp-dev
      - libtool

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/opencontainers/runc
      tag: v${{package.version}}
      expected-commit: c241c0bb5e60a8e8c1b2e53d4eca8d0068d8d57e

  - uses: bump
    with:
      deps: |-
        golang.org/x/net@v0.53.0
        golang.org/x/sys@v0.43.0

  - runs: |
      make COMMIT=$(git rev-parse HEAD)
      make man
      install -Dsm755 ./runc "${{targets.destdir}}"/usr/bin/runc
      install -Dm644 ./man/man8/* -t "${{targets.destdir}}"/usr/share/man/man8/

  - uses: strip

subpackages:
  - name: runc-doc
    pipeline:
      - uses: split/manpages
    description: runc manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: opencontainers/runc
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: runc
        version: ${{package.version}}
    - uses: test/tw/help-check
      with:
        bins: runc
    - name: "Test runc features"
      runs: |
        set -euo pipefail
        runc features | grep -F "seccomp"
    - name: "Verify runc binary"
      runs: |
        [ -x "$(command -v runc)" ]
    - name: "Check runc state command"
      runs: |
        runc state non_existent_container || [ $? -eq 1 ]
    - name: "Check runc spec command"
      runs: |
        runc spec --rootless
        [ -f config.json ]
