package:
  name: samply
  version: "0.13.1"
  epoch: 13
  description: "Command-line sampling profiler for macOS and Linux"
  copyright:
    - license: Apache-2.0 OR MIT
  resources:
    cpu: "9"
    memory: 10Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust-1.94
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mstange/samply
      expected-commit: da75c28f367454c621e690eeb4e44ec2ebb29a78
      tag: samply-v${{package.version}}

  - uses: bump

  - uses: rust/cargobump

  - uses: cargo/build
    with:
      output: samply

  - uses: strip

update:
  enabled: true
  github:
    identifier: mstange/samply
    strip-prefix: samply-v
    use-tag: true
    tag-filter-prefix: samply-v

test:
  environment:
    contents:
      packages:
        - jq
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: samply
    - uses: test/tw/ver-check
      with:
        bins: samply
    - name: Profile jq and check that profile.json is created
      runs: |
        samply record -s jq -h && jq -e . < ./profile.json
