package:
  name: secrets-store-csi-driver-provider-azure
  version: "1.8.1"
  epoch: 0
  description: Azure Key Vault provider for Secret Store CSI driver
  copyright:
    - license: MIT
  dependencies:
    provides:
      # REMOVE_POST_USRMERGE - https://github.com/orgs/wolfi-dev/discussions/40270
      - ${{package.name}}-compat=${{package.full-version}}
    runtime:
      - ca-certificates-bundle
      - merged-bin
      - tzdata
      - wolfi-baselayout
  resources:
    cpu: "1"
    memory: 5Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - go-1.26
      - make

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Azure/secrets-store-csi-driver-provider-azure
      tag: v${{package.version}}
      expected-commit: c07d0d69c6b317abe04deb8474c0069ce97d2ccb

  - uses: bump
    with:
      deps: |-
        golang.org/x/net@v0.53.0
        golang.org/x/crypto@v0.50.0
        golang.org/x/sys@v0.43.0

  - runs: |
      git fetch --depth=1 origin 70c5e747e418304295a9d40acc7eb6ec35f686af
      git checkout FETCH_HEAD -- \
        pkg/metrics/prometheus_exporter.go \
        pkg/metrics/stats_reporter.go \
        pkg/server/server.go

  - runs: |
      unset LDFLAGS
      make build ARCH=$(go env GOARCH)

  - runs: |
      install -Dm755 _output/*/secrets-store-csi-driver-provider-azure "${{targets.destdir}}"/usr/bin/secrets-store-csi-driver-provider-azure

  - uses: strip

update:
  enabled: true
  github:
    identifier: Azure/secrets-store-csi-driver-provider-azure
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: secrets-store-csi-driver-provider-azure
    - uses: test/tw/help-check
      with:
        bins: secrets-store-csi-driver-provider-azure
    - name: Run and test ${{package.name}}
      uses: test/daemon-check-output
      with:
        start: /usr/bin/${{package.name}}
        timeout: 30
        # LOL typo
        expected_output: |
          Starting Azure Key Vault Provider
          intializing metrics backend
          Listening for connections
          azure
