package:
  name: sonar-scanner-cli
  version: "8.0.1.6346"
  epoch: 5 # GHSA-qqpg-mvqg-649v
  description: Scanner CLI for SonarQube and SonarCloud
  copyright:
    - license: LGPL-3.0-or-later
  dependencies:
    runtime:
      - bash
  resources:
    cpu: "1"
    memory: 5Gi

environment:
  contents:
    packages:
      - maven
      - openjdk-17-default-jdk
      - wolfi-base
      - wolfi-baselayout
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SonarSource/sonar-scanner-cli
      tag: ${{package.version}}
      expected-commit: 57cc1f610bc251c6b01ac927c71971eab640ee02

  - uses: auth/maven

  - uses: bump

  - name: build
    runs: |
      mvn clean package
      install -d "${{targets.destdir}}"/usr/bin/sonarqube
      cp target/sonar-scanner-cli-*.jar "${{targets.destdir}}"/usr/bin/sonarqube/sonarscanner-cli.jar
      install -Dm755 sonar-scanner-cli "${{targets.destdir}}"/usr/bin/sonar-scanner-cli
      install -Dm755 sonar-scanner-cli-debug "${{targets.destdir}}"/usr/bin/sonar-scanner-cli-debug
      install -Dm644 src/main/assembly/conf/sonar-scanner.properties "${{targets.destdir}}"/opt/sonar-scanner/conf/sonar-scanner.properties

subpackages:
  - name: ${{package.name}}-compat
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - runs: |
          install -d "${{targets.subpkgdir}}"/opt/sonar-scanner/bin
          install -d "${{targets.subpkgdir}}"/opt/sonar-scanner/lib
          ln -s ../../../usr/bin/sonar-scanner-cli "${{targets.subpkgdir}}"/opt/sonar-scanner/bin/sonar-scanner-cli
          ln -s ../../../usr/bin/sonar-scanner-cli "${{targets.subpkgdir}}"/opt/sonar-scanner/bin/sonar-scanner
          ln -s ../../../usr/bin/sonar-scanner-cli-debug "${{targets.subpkgdir}}"/opt/sonar-scanner/bin/sonar-scanner-cli-debug
          ln -s ../../../usr/bin/sonarqube/sonarscanner-cli.jar "${{targets.subpkgdir}}"/opt/sonar-scanner/lib/sonar-scanner-cli-${{package.version}}.jar
    test:
      pipeline:
        - uses: test/tw/symlink-check
        - uses: test/tw/contains-files
          with:
            files: |
              /opt/sonar-scanner/bin/sonar-scanner-cli
              /opt/sonar-scanner/bin/sonar-scanner
              /opt/sonar-scanner/bin/sonar-scanner-cli-debug
              /opt/sonar-scanner/lib/sonar-scanner-cli-${{package.version}}.jar

update:
  enabled: true
  github:
    identifier: SonarSource/sonar-scanner-cli
    use-tag: true

test:
  environment:
    contents:
      packages:
        - openjdk-17-default-jvm
  pipeline:
    - uses: test/tw/ver-check
      with:
        bins: sonar-scanner-cli
        version: "8.0.1"
        version-flag: "--version"
    - uses: test/tw/contains-files
      with:
        files: |
          /usr/bin/sonar-scanner-cli
          /usr/bin/sonar-scanner-cli-debug
          /usr/bin/sonarqube/sonarscanner-cli.jar
          /opt/sonar-scanner/conf/sonar-scanner.properties
