package:
  name: src
  version: "7.4.0"
  epoch: 0 # toolchain rebuild for  go-1.26-1.26.4
  description: Sourcegraph CLI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git
  resources:
    cpu: "3"
    memory: 7Gi

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.26
      - libx11-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sourcegraph/src-cli
      expected-commit: 65413c2eb780bbad16cd497287a7ab791c88d4c5
      tag: ${{package.version}}

  - uses: bump
    with:
      deps: |-
        golang.org/x/net@v0.55.0
        github.com/jackc/pgx/v5@v5.9.2
        golang.org/x/crypto@v0.52.0
      modroot: |-
        lib
        .

  - uses: go/build
    with:
      go-package: go-1.26
      packages: ./cmd/src
      output: src
      ldflags: "-X github.com/sourcegraph/src-cli/internal/version.BuildTag=${{package.version}}"

update:
  enabled: true
  github:
    identifier: sourcegraph/src-cli

test:
  pipeline:
    - name: Verify src installation
      runs: |
        src version || exit 1
        src --help
    - name: Display src CLI help
      runs: |
        src -h || exit 1
