package:
  name: src
  version: "7.2.0"
  epoch: 0 # GHSA-mh2q-q3fh-2475
  description: Sourcegraph CLI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git
  resources:
    cpu: "3"
    memory: 7Gi

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.26
      - libx11-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sourcegraph/src-cli
      expected-commit: dfaa4dd216cf45a62bfda06fe7199abf37bebb19
      tag: ${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.51.0
        github.com/jackc/pgx/v5@v5.9.2
        go.opentelemetry.io/otel@v1.41.0
      modroot: lib
      tidy: false

  - uses: go/bump
    with:
      deps: |-
        github.com/go-jose/go-jose/v4@v4.1.4
        golang.org/x/net@v0.51.0
        github.com/jackc/pgx/v5@v5.9.2
        go.opentelemetry.io/otel@v1.41.0

  - uses: go/build
    with:
      go-package: go-1.26
      packages: ./cmd/src
      output: src
      ldflags: "-X github.com/sourcegraph/src-cli/internal/version.BuildTag=${{package.version}}"

update:
  enabled: true
  github:
    identifier: sourcegraph/src-cli

test:
  pipeline:
    - name: Verify src installation
      runs: |
        src version || exit 1
        src --help
    - name: Display src CLI help
      runs: |
        src -h || exit 1
