package:
  name: step
  version: "0.30.2"
  epoch: 0 # CVE-2026-25679
  description: A zero trust swiss army knife for working with X509, OAuth, JWT, OATH OTP, etc.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "1"
    memory: 5Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smallstep/cli
      tag: v${{package.version}}
      expected-commit: 8da21e8ece79447b000302b7d8053858fcfe8c91

  - uses: go/build
    with:
      packages: ./cmd/step
      output: step
      ldflags: -X main.Version=${{package.version}}

update:
  enabled: true
  github:
    identifier: smallstep/cli
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: step
        version: ${{package.version}}
    - uses: test/tw/help-check
      with:
        bins: step
    - name: Test JSON Web Keys (JWKs)
      runs: |
        # create JWKs
        step crypto jwk create pub.json key.json --no-password --insecure
        [ -f pub.json ]
        [ -f key.json ]

        # add the public key to a keyset
        step crypto jwk keyset add keys.json < pub.json
    - name: Test JSON Web Tokens (JWTs)
      runs: |
        set -euo pipefail
        echo "Creating and signing a JWT that expires in 2 minutes"
        JWT=$(step crypto jwt sign \
            --key key.json \
            --iss "issuer@example.com" \
            --aud "audience@example.com" \
            --sub "subject@example.com" \
            --exp $(( $(date +%s) + 120 )))

        echo "Verifying the JWT"
        echo "$JWT" | step crypto jwt verify --jwks keys.json --iss "issuer@example.com" --aud "audience@example.com"
    - name: Cleanup
      runs: |
        rm -f pub.json key.json keys.json
        unset JWT

environment:
  contents:
    packages:
      - go-1.25
