package:
  name: step-issuer
  version: "0.10.1"
  epoch: 0
  description: A certificate issuer for cert-manager using step certificates CA
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "2"
    memory: 6Gi
  test-resources:
    cpu: "1"
    memory: 3Gi

environment:
  environment:
    CGO_ENABLED: "0"
  contents:
    packages:
      - go-1.25

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smallstep/step-issuer
      tag: v${{package.version}}
      expected-commit: 9ee185ba7912627ef4c956faedaec672eadf8d8e

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.79.3

  - uses: go/build
    with:
      packages: ./
      output: step-issuer
      ldflags: -X "main.Version=${{package.version}}"

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    dependencies:
      runtime:
        - step-issuer
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}
          ln -sf usr/bin/step-issuer ${{targets.contextdir}}/manager
    description: Helm chart compatibility
    test:
      pipeline:
        - uses: test/tw/symlink-check

update:
  enabled: true
  github:
    identifier: smallstep/step-issuer
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
        - ca-certificates-bundle
  pipeline:
    - name: Run Help Command
      runs: |
        /usr/bin/step-issuer -h
        step-issuer --help
    - name: "Setup KWOK cluster"
      uses: test/kwok/cluster
    - name: "Install CRDs"
      runs: |
        kubectl apply -f https://raw.githubusercontent.com/smallstep/step-issuer/refs/heads/master/config/crd/bases/certmanager.step.sm_stepclusterissuers.yaml
        kubectl apply -f https://raw.githubusercontent.com/smallstep/step-issuer/refs/heads/master/config/crd/bases/certmanager.step.sm_stepissuers.yaml
    - name: "Functional Test"
      uses: test/daemon-check-output
      with:
        setup: |
          kubectl config view --minify --raw > /tmp/kubeconfig.yaml
        start: |
          step-issuer --logtostderr=true --zap-log-level=debug --disable-approval-check --metrics-bind-address=":8080" --kubeconfig=/tmp/kubeconfig.yaml
        timeout: 180
        expected_output: |
          starting manager
          Starting metrics server
          Starting Controller
          Starting workers
          Starting EventSource
        post: |
          if curl -sf http://localhost:8080/metrics | grep -q "controller_runtime_active_workers"; then
            echo "Metrics endpoint is up and exporting metrics"
          else
            echo " Metrics endpoint check failed"
            exit 1
          fi
