package:
  name: tealdeer
  version: "1.8.1"
  epoch: 6 # GHSA-82j2-j2ch-gfr8
  description: A very fast implementation of tldr in Rust.
  copyright:
    - license: Apache-2.0
    - license: MIT
  dependencies:
    provides:
      - tldr=${{package.full-version}}
  resources:
    cpu: "3"
    memory: 9Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cargo-auditable
      - rust-1.94

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tealdeer-rs/tealdeer
      tag: v${{package.version}}
      expected-commit: b3cd7b1c216656ea3416a86104363589157477dc

  - uses: rust/cargobump

  - name: Configure and Build
    uses: cargo/build
    with:
      modroot: .
      output: tldr

  - uses: strip

update:
  enabled: true
  github:
    identifier: tealdeer-rs/tealdeer
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/ver-check
      with:
        bins: tldr
    - uses: test/tw/help-check
      with:
        bins: tldr
    - name: do a tldr test
      runs: |
        tldr --update
        tldr strace
