package:
  name: temporal
  version: "1.7.0"
  epoch: 5 # CVE-2026-33814
  description: Command-line interface for running Temporal Server and interacting with Workflows, Activities, Namespaces, and other parts of Temporal
  copyright:
    - license: MIT
  resources:
    cpu: "3"
    memory: 12Gi
  test-resources:
    cpu: "1"
    memory: 1Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-1.26
      - wolfi-baselayout
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/temporalio/cli
      tag: v${{package.version}}
      expected-commit: 62fa8939b953445ccfcca9c896b7296279b6cd7a

  - uses: bump
    with:
      language: go
      packages: |-
        filippo.io/edwards25519@v1.1.1
        go.opentelemetry.io/otel/sdk@v1.43.0
        github.com/gomarkdown/markdown@v0.0.0-20260411013819-759bbc3e3207
        github.com/aws/aws-sdk-go-v2/service/lambda@v1.88.5
        github.com/apache/thrift@v0.23.0
        golang.org/x/net@v0.53.0
        golang.org/x/term@v0.42.0

  - uses: go/build
    with:
      packages: ./cmd/temporal
      output: temporal
      go-package: go-1.26

subpackages:
  - name: temporal-compat
    description: "Compat package for temporal"
    test:
      environment:
        contents:
          packages:
            # -compat packages can be satisfied by multiple source packages; install here for test only, not as a runtime dep
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf ../../bin/temporal "${{targets.contextdir}}"/usr/local/bin/temporal

update:
  enabled: true
  github:
    identifier: temporalio/cli
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - name: Check temporal version
      runs: |
        temporal --version
        temporal --help
    - name: Test workflow list command
      runs: |
        output=$(temporal workflow list --address 192.0.2.0:1234 2>&1 || true)
        echo "$output" | grep "failed reaching server"
