package:
  name: terraform-mcp-server
  version: "1.0.0"
  epoch: 0 # toolchain rebuild for  go-1.26-1.26.4
  description: Terraform MCP Server
  copyright:
    - license: MIT
  resources:
    cpu: "1"
    memory: 5Gi
  test-resources:
    cpu: "1"
    memory: 2Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/terraform-mcp-server
      expected-commit: 7075cf6e2c265bd45ae3210134d34b193cc75203
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/terraform-mcp-server
      ldflags: |
        -X  terraform-mcp-server/version.GitCommit=$(git rev-parse HEAD)
        -X  terraform-mcp-server/version.BuildDate=$(date -u -d "@$SOURCE_DATE_EPOCH" +"%Y-%m-%dT%H:%M:%SZ")
      output: terraform-mcp-server
      go-package: go-1.26

update:
  enabled: true
  ignore-regex-patterns:
    - rc
  github:
    identifier: hashicorp/terraform-mcp-server
    strip-prefix: v

test:
  pipeline:
    - name: version test
      runs: |
        terraform-mcp-server -v | grep ${{package.version}}

environment:
  contents:
    packages:
      - go-1.26
