package:
  name: terraform
  version: 1.5.7
  epoch: 45 # add go-package to go/build step
  copyright:
    - license: MPL-2.0
  resources:
    cpu: "4"
    memory: 10Gi

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/terraform
      tag: v${{package.version}}
      expected-commit: ee58ac1851c8a433005df9863ed47796a9f6b5e7

  - uses: go/bump
    with:
      deps: |-
        google.golang.org/protobuf@v1.33.0
        github.com/hashicorp/go-retryablehttp@v0.7.7
        github.com/hashicorp/go-getter@v1.7.5
        github.com/hashicorp/go-slug@v0.16.3
        golang.org/x/oauth2@v0.27.0
        github.com/golang-jwt/jwt/v4@v4.5.2
        golang.org/x/net@v0.38.0
        github.com/ulikunitz/xz@v0.5.14
        golang.org/x/crypto@v0.45.0
        google.golang.org/api@v0.155.0
        google.golang.org/grpc@v1.79.3

  - uses: go/build
    with:
      packages: .
      output: terraform
      go-package: go-1.25

subpackages:
  - name: terraform-compat
    description: Compat package for terraform
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf ../../bin/terraform "${{targets.subpkgdir}}"/usr/local/bin/terraform
    test:
      environment:
        contents:
          packages:
            # -compat packages can be satisfied by multiple source packages; install here for test only, not as a runtime dep
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check

  - name: terraform-local-provider-config
    description: Configure Terraform to use local providers
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/terraform/provider-mirror
          cat > "${{targets.subpkgdir}}"/terraform/.terraformrc <<EOF
          provider_installation {
            filesystem_mirror {
              path    = "/terraform/provider-mirror"
              include = ["*/*"]
            }
            direct {
              exclude = ["*/*"]
            }
          }
          EOF
    test:
      pipeline:
        - uses: test/tw/configpackage
          with:
            dir: /terraform/

update:
  enabled: false
  exclude-reason: "Last version before BUSL license change"

test:
  pipeline:
    - uses: test/tw/ldd-check
    - name: Terraform Initialization
      runs: |
        echo "provider \"local\" {}" > example.tf
        terraform init -input=false || exit 1
        terraform --version
        terraform --help
    - name: Terraform Plan Creation
      runs: |
        terraform plan -input=false -out=tfplan || exit 1
    - name: Terraform Apply Execution
      runs: |
        terraform apply -input=false tfplan || exit 1

environment:
  contents:
    packages:
      - go-1.25
