package:
  name: texinfo
  version: "7.3"
  epoch: 4
  description: "GNU documentation tool"
  copyright:
    - license: GPL-3.0-or-later
  dependencies:
    runtime:
      - perl
  resources:
    cpu: "1"
    memory: 4Gi
  test-resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - gawk
      - gettext
      - help2man
      - libtool
      - ncurses
      - ncurses-dev
      - perl
      - wolfi-baselayout
      - xz

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.savannah.gnu.org/git/texinfo.git
      tag: texinfo-${{package.version}}
      expected-commit: 3fa5d8f7081ab2e38c5590ef852e0732a858bc3f

  - runs: ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      rm -f "${{targets.destdir}}"/usr/share/info/dir

  - uses: strip

update:
  enabled: true
  git:
    tag-filter-prefix: texinfo-
    strip-prefix: texinfo-

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        info --version
        install-info --version
        makeinfo --version
        pdftexi2dvi --version
        pod2texi --version
        texi2any --version
        texi2dvi --version
        texi2pdf --version
        texindex --version
        info --help
        install-info --help
        makeinfo --help
        pdftexi2dvi --help
        pod2texi --help
        texi2any --help
        texi2dvi --help
        texi2pdf --help
        texindex --help

subpackages:
  - name: texinfo-doc
    description: texinfo documentation
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    test:
      pipeline:
        - uses: test/docs
