package:
  name: trivy
  version: "0.69.2"
  epoch: 0 # GHSA-9h8m-3fm2-qjrq
  description: Simple and comprehensive vulnerability scanner for containers
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "8"
    memory: 15Gi

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cfa322ed23f2e33ef1632ae3a5a8c7172f06a5c3
      repository: https://github.com/aquasecurity/trivy
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        github.com/go-git/go-git/v5@v5.16.5

  - uses: go/build
    with:
      experiments: jsonv2
      packages: ./cmd/trivy
      output: trivy
      ldflags: -X github.com/aquasecurity/trivy/pkg/version/app.ver=${{package.version}}

test:
  environment:
    contents:
      packages:
        - jq
  pipeline:
    - name: Check trivy version
      runs: |
        trivy version
        trivy version | grep '^Version: ${{package.version}}$'
        trivy --version
        trivy --help
    - name: Check trivy version as JSON
      runs: |
        trivy version -f json | jq -M
        [ "$(trivy version -f json 2>/dev/null | jq -r .Version)" == "${{package.version}}" ]

update:
  enabled: true
  github:
    identifier: aquasecurity/trivy
    strip-prefix: v
