package:
  name: trivy
  version: "0.69.4"
  epoch: 0 # GHSA-p436-gjf2-799p
  description: Simple and comprehensive vulnerability scanner for containers
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "8"
    memory: 15Gi
  test-resources:
    cpu: "1"
    memory: 3Gi

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1885610c6a34811c8296416ae69f568002ef11ec
      repository: https://github.com/aquasecurity/trivy
      tag: v${{package.version}}

  - uses: go/build
    with:
      experiments: jsonv2
      packages: ./cmd/trivy
      output: trivy
      ldflags: -X github.com/aquasecurity/trivy/pkg/version/app.ver=${{package.version}}

test:
  environment:
    contents:
      packages:
        - jq
  pipeline:
    - name: Check trivy version
      runs: |
        trivy version
        trivy version | grep '^Version: ${{package.version}}$'
        trivy --version
        trivy --help
    - name: Check trivy version as JSON
      runs: |
        trivy version -f json | jq -M
        [ "$(trivy version -f json 2>/dev/null | jq -r .Version)" == "${{package.version}}" ]

update:
  enabled: true
  github:
    identifier: aquasecurity/trivy
    strip-prefix: v

environment:
  contents:
    packages:
      - go-1.25
