package:
  name: typescript
  version: "7.0.2"
  epoch: 2 # CVE-2026-56851
  description: "TypeScript is a superset of JavaScript that compiles to clean JavaScript output."
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - curl
      - git
      - go-${{vars.go-version}}
      - nodejs-26
      - npm
      - wolfi-base

vars:
  go-version: 1.27

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/microsoft/TypeScript
      tag: v${{package.version}}
      expected-commit: 1e4744d68260a7cb91b62b12edc3f6a2187faaf1

  - uses: bump
    with:
      modroot: tsc
      deps: |-
        golang.org/x/text@v0.41.0

  - working-directory: tsc
    runs: |
      npm ci
      npx hereby native-preview:build-packages

      mkdir -p "${{targets.destdir}}"/usr/lib/node_modules/@typescript
      cp -r built/npm/typescript "${{targets.destdir}}"/usr/lib/node_modules/
      cp -r built/npm/typescript-linux-* "${{targets.destdir}}"/usr/lib/node_modules/@typescript

      mkdir -p "${{targets.destdir}}"/usr/bin
      plat=$(basename built/npm/typescript-linux-*)
      ln -s /usr/lib/node_modules/@typescript/$plat/lib/tsc "${{targets.destdir}}/usr/bin/tsc"

test:
  environment:
    contents:
      packages:
        - nodejs
  pipeline:
    - uses: test/tw/ver-check
      with:
        bins: tsc
        version: ${{package.version}}
    - uses: test/tw/help-check
      with:
        bins: tsc
    - runs: |
        set -euo pipefail
        cat <<EOF > hello.ts
         let message: string = 'Hello, Wolfi!';
         console.log(message);
        EOF

        tsc hello.ts
        node hello.js | grep "Wolfi"

update:
  enabled: true
  github:
    identifier: microsoft/TypeScript
    strip-prefix: v
    tag-filter: v
    use-tag: true
