package:
  name: uv
  version: "0.11.3"
  epoch: 1 # use cargo/build pipeline, rust-1.94, add ldd-check test
  description: An extremely fast Python package installer and resolver, written in Rust.
  copyright:
    - license: MIT
  resources:
    cpu: "12"
    memory: 19Gi
  test-resources:
    cpu: "1"
    memory: 3Gi

vars:
  build-pypi-package: uv-build
  build-module-name: uv_build
  clang-version: 22

data:
  - name: py-versions
    items:
      3.10: '310'
      3.11: '311'
      3.12: '312'
      3.13: '313'

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - clang-${{vars.clang-version}}
      - cmake
      - maturin
      - openssl-dev
      - perl
      - py3-supported-build-base
      - py3-supported-maturin
      - rust-1.94

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/astral-sh/uv
      tag: ${{package.version}}
      expected-commit: 45da18ac317f9abdf9313066907511b5aebc476b
      destination: uv

  - working-directory: uv
    uses: rust/cargobump

  - working-directory: uv
    uses: cargo/build
    with:
      output: uv

  - working-directory: uv
    uses: cargo/build
    with:
      output: uvx

  - uses: strip

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.build-pypi-package}}
    description: ${{vars.build-pypi-package}} installed for python${{range.key}}
    dependencies:
      provides:
        - py3-${{vars.build-pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
        working-directory: uv/crates/uv-build
      - name: move usr/bin executables for -bin
        runs: |
          mkdir -p ./cleanup/${{range.key}}/
          mv ${{targets.contextdir}}/usr/bin ./cleanup/${{range.key}}/
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.build-module-name}}

  - range: py-versions
    name: py${{range.key}}-${{vars.build-pypi-package}}-bin
    description: Executable binaries for ${{vars.build-pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.build-pypi-package}}-bin
      runtime:
        - py${{range.key}}-${{vars.build-pypi-package}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/
          mv ./cleanup/${{range.key}}/bin ${{targets.contextdir}}/usr/
    test:
      pipeline:
        - runs: |
            uv-build --help

  - name: py3-supported-${{vars.build-pypi-package}}
    description: meta package providing ${{vars.build-pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.build-pypi-package}}
        - py3.11-${{vars.build-pypi-package}}
        - py3.12-${{vars.build-pypi-package}}
        - py3.13-${{vars.build-pypi-package}}
    test:
      pipeline:
        - uses: test/metapackage

update:
  enabled: true
  github:
    identifier: astral-sh/uv

test:
  pipeline:
    - uses: test/tw/ldd-check
    - name: uv version and help
      runs: |
        uv --version | grep ${{package.version}}
        uvx --version | grep ${{package.version}}
        uv --help
        uvx --help
    - name: uv simple example
      runs: |
        uv init example
        cd example
        uv add ruff
        uv run ruff check
    - name: uv toolings
      runs: |
        uv tool install ruff
        uv venv
        uv python list
