package:
  name: victoriametrics
  version: "1.142.0"
  epoch: 0 # CVE-2026-32280
  description: VictoriaMetrics is a fast, cost-effective, and scalable monitoring solution and time series database designed for high performance and reliability. It supports both single-server and clustered installations, providing flexibility for various deployment needs, and integrates well with tools like Grafana for data visualization.
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "4"
    memory: 8Gi

data:
  - name: victoria-packages
    items:
      vmagent: vmagent is a tiny agent which helps you collect metrics from various sources, relabel and filter the collected metrics and store them in VictoriaMetrics or any other storage systems via Prometheus remote_write protocol or via VictoriaMetrics remote_write protocol.
      vmalert: vmalert executes a list of the given alerting or recording rules against configured -datasource.url compatible with Prometheus HTTP API.
      vmauth: vmauth is a simple auth proxy and router for VictoriaMetrics

environment:
  contents:
    packages:
      - go-1.25
      - nodejs-20
      - npm
  environment:
    GOTOOLCHAIN: local+auto

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 64ccd2ed44828d09cafc4a4c4587c62f122f63ce
      repository: https://github.com/VictoriaMetrics/VictoriaMetrics
      tag: v${{package.version}}

  - runs: |
      cp docs/victoriametrics/MetricsQL.md app/vmui/packages/vmui/src/assets/MetricsQL.md

  - working-directory: app/vmui/packages/vmui
    runs: |
      npm install
      npm run build

  - runs: |
      rm -rf app/vmselect/vmui/*
      mv app/vmui/packages/vmui/build/* app/vmselect/vmui/

  - uses: go/build
    with:
      packages: ./app/victoria-metrics
      output: victoria-metrics
      go-package: go-1.25
      ldflags: -X github.com/VictoriaMetrics/VictoriaMetrics/lib/buildinfo.Version=victoria-metrics-${{package.version}}-$(date -u -d "@${SOURCE_DATE_EPOCH:-$(date +%s)}" "+%Y-%m-%dT%H:%M:%SZ")-$(git rev-parse HEAD)

subpackages:
  - range: victoria-packages
    name: victoriametrics-${{range.key}}
    description: ${{range.value}}
    pipeline:
      - uses: go/build
        with:
          packages: ./app/${{range.key}}
          output: ${{range.key}}
          go-package: go-1.25
          ldflags: -X github.com/VictoriaMetrics/VictoriaMetrics/lib/buildinfo.Version=${{range.key}}-${{package.version}}-$(date -u -d "@${SOURCE_DATE_EPOCH:-$(date +%s)}" "+%Y-%m-%dT%H:%M:%SZ")-$(git rev-parse HEAD)
    test:
      pipeline:
        - uses: test/tw/help-check
          with:
            bins: ${{range.key}}
        - uses: test/tw/ver-check
          with:
            bins: ${{range.key}}
            version: ${{package.version}}

  - range: victoria-packages
    name: "victoriametrics-${{range.key}}-compat"
    description: Compatibility package to place binaries in the location expected by upstream Dockerfile
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf ./usr/bin/${{range.key}} ${{targets.contextdir}}/${{range.key}}
    test:
      environment:
        contents:
          packages:
            - victoriametrics-${{range.key}}
      pipeline:
        - uses: test/tw/symlink-check

  - name: victoriametrics-compat
    description: Compatibility package to place binaries in the location expected by upstream Dockerfile
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf ./usr/bin/victoria-metrics ${{targets.contextdir}}/victoria-metrics-prod
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/symlink-check

update:
  enabled: true
  github:
    identifier: VictoriaMetrics/VictoriaMetrics
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: victoria-metrics
    - uses: test/tw/ver-check
      with:
        bins: victoria-metrics
        version: ${{package.version}}
    - name: "Test victoria-metrics-prod"
      uses: test/daemon-check-output
      with:
        start: victoria-metrics -httpListenAddr=:8428
        post: |
          fail() { echo "FATAL: $*"; exit 1; }
          curl -L http://localhost:8428/vmui | grep -F "<title>vmui</title>" || fail "vmui page missing or unexpected"
          curl -L http://localhost:8428/metric-relabel-debug | grep -F "<title>Metric relabel debug</title>" || fail "relabel debug page missing or unexpected"
        expected_output: |
          started server at http://0.0.0.0:8428/
