package:
  name: wizer
  version: "11.0.3"
  epoch: 2 # GHSA-852m-cvvp-9p4w
  description: "The WebAssembly Pre-Initializer"
  copyright:
    - license: Apache-2.0
  resources:
    cpu: "7"
    memory: 12Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust-1.94
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bytecodealliance/wizer.git
      tag: v${{package.version}}
      expected-commit: 61301504fd49c18ddd61c672231f6b280f6c37db

  - uses: rust/cargobump

  - uses: cargo/build
    with:
      output: wizer
      opts: --release --all-features

  - uses: strip

update:
  enabled: true
  github:
    identifier: bytecodealliance/wizer
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/tw/help-check
      with:
        bins: wizer
