package:
  name: zola
  version: "0.22.1"
  epoch: 8 # GHSA-qg8r-f7x3-25f7
  description: A fast static site generator in a single binary with everything built-in
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/getzola/zola
      expected-commit: 29540e9897dbe8aca388b13f7bdf615985f6ca2c
      tag: v${{package.version}}

  - uses: rust/cargobump

  - name: Update internal imageproc workspace member version for GHSA-qg8r-f7x3-25f7
    runs: |
      sed -i 's/^version = "0\.1\.0"$/version = "0.23.1"/' components/imageproc/Cargo.toml

  - name: Configure and build
    uses: cargo/build
    with:
      output: zola

  - uses: strip

update:
  enabled: true
  github:
    identifier: getzola/zola
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ver-check
      with:
        bins: zola
    - uses: test/tw/help-check
      with:
        bins: zola
