package:
  name: zola
  version: "0.23.3"
  epoch: 1 # rust: 1.96->1.97
  description: A fast static site generator in a single binary with everything built-in
  copyright:
    - license: MIT

vars:
  rust-version: "1.97"

environment:
  contents:
    packages:
      - rust-${{vars.rust-version}}

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/getzola/zola
      expected-commit: 7fe17abff2f3c05177be6833a2dc9483ab507e52
      tag: v${{package.version}}

  - name: Update internal imageproc workspace member version for GHSA-qg8r-f7x3-25f7
    runs: |
      sed -i 's/^version = "0\.1\.0"$/version = "0.23.1"/' components/imageproc/Cargo.toml

  - name: Configure and build
    uses: cargo/build
    with:
      output: zola

  - uses: strip

update:
  enabled: true
  github:
    identifier: getzola/zola
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - uses: test/tw/ver-check
      with:
        bins: zola
    - uses: test/tw/help-check
      with:
        bins: zola
