package:
  name: ztunnel-1.29
  version: "1.29.0"
  epoch: 0 # GHSA-r6v5-fh4h-64xc
  description: The `ztunnel` component of istio ambient mesh.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - ztunnel=${{package.full-version}}
    runtime:
      - ca-certificates-bundle
      - iptables-nft
      - libmnl
      - libnetfilter_conntrack
      - libnfnetlink
  resources:
    cpu: "9"
    memory: 16Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - clang
      - cmake
      - protoc
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/ztunnel
      tag: ${{package.version}}
      expected-commit: 4225e92aa753b1bdba800fe975f03e131f8cc257

  - name: Downgrade pingora-pool to 0.4.0
    runs: |
      # This is necessary because we need to bump lru to version 0.16,
      # and pingora-pool comes locked at version 0.6.0, which depends
      # on lru version 0.14.  While the ideal solution here would be to
      # bump pingora-pool to version 0.7.0, ztunnel 1.29 doesn't build
      # with it.  Here's a summary of the situation:
      #
      # - pingora-pool 0.7.0 => ztunnel fails to build.
      # - pingora-pool 0.6.0 => locked to lru 0.14.
      # - pingora-pool 0.5.0 => likewise.
      # - pingora-pool 0.4.0 => accepts "lru=0"
      #
      # This means that we have to downgrade to pingora-pool 0.4.0 to
      # be able to upgrade to lru 0.16.
      cargo add pingora-pool@'=0.4.0'

  - uses: rust/cargobump

  - runs: |
      export ZTUNNEL_BUILD_buildStatus=clean
      export ZTUNNEL_BUILD_buildGitRevision=$(git rev-parse HEAD)
      export ZTUNNEL_BUILD_buildVersion=$(git describe --tags --abbrev=0)
      cargo auditable build --release
      mkdir -p ${{targets.destdir}}/usr/bin
      cp out/rust/release/ztunnel ${{targets.destdir}}/usr/bin/ztunnel

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: Compat package for ztunnel
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/local/bin
          ln -sf /usr/bin/ztunnel "${{targets.contextdir}}"/usr/local/bin/ztunnel
    dependencies:
      provides:
        - ztunnel-compat=${{package.full-version}}
    test:
      pipeline:
        - uses: test/virtualpackage
          with:
            virtual-pkg-name: ztunnel-compat
            real-pkg-name: ${{subpkg.name}}

update:
  enabled: true
  ignore-regex-patterns:
    - '-rc'
    - '-beta'
  github:
    identifier: istio/ztunnel
    tag-filter-prefix: 1.29.
    use-tag: true

test:
  pipeline:
    - name: Version information tests
      runs: |
        VERSION_OUTPUT=$(ztunnel version)
        echo "$VERSION_OUTPUT" | grep "Version"
        echo "$VERSION_OUTPUT" | grep "BuildStatus"
        echo "$VERSION_OUTPUT" | grep ${{package.version}}
    - name: Command structure tests
      runs: |
        set -e
        ztunnel help | grep "Commands:"
        ztunnel help proxy | grep "Start the ztunnel proxy"
        ztunnel help version | grep "Print the version"
