#!/sbin/openrc-run
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-dns/pdns/files/pdns,v 1.10 2007/05/07 20:19:18 swegener Exp $

name=pdns-recursor
daemon=/usr/sbin/pdns_recursor
recursor_control=/usr/bin/rec_control

extra_started_commands="dump reload"

depend() {
	need net
	after firewall entropy
}

start_pre() {
	# Set up default socket-dir
	checkpath --directory --owner recursor:recursor --mode 0775 /var/run/pdns-recursor
}

start() {
	ebegin "Starting PowerDNS recursor"
	${daemon}
	eend $?
}

stop() {
	ebegin "Stopping PowerDNS recursor"
	${recursor_control} quit &>/dev/null
	eend $?
}
