#!/sbin/openrc-run
# Copyright 2020-2021 Laurent Bercot for Alpine Linux
# Distributed under the terms of the ISC License.
#
name="utmpd"
description="utmps daemon for the utmp service"

command=/bin/s6-ipcserver
command_args="/run/utmps/.utmpd-socket utmps-utmpd"
command_user=utmp
command_background=yes
directory=/run/utmps
pidfile=/run/utmps/utmpd.pid

depend() {
	need utmp-prepare
	after bootmisc
	before networking
}

start_pre() {
	checkpath -d -o utmp:utmp -m 0755 /run/utmps
}