#!/usr/bin/python3
import os, sys
wrapper = sys.argv[1]
fname = sys.argv[2]
majmin = sys.argv[3]

assert f"/usr/bin/python{majmin}" == sys.executable
assert majmin == "%s.%s" % (sys.version_info.major, sys.version_info.minor)
assert os.path.basename(sys.argv[0]) == os.path.basename(fname)
assert len(sys.argv) == 4, f"expected 4 args found {sys.argv}"

print(f"PASS: {wrapper} wrapped {sys.executable} successfully")
