#!/bin/sh -e
input="$1"
outf="$2"
d=$(dirname "$0")
tmpl="$d/env-script.tmpl"

[ -f "$tmpl" ] ||
    { echo "no '${tmpl##*/}' in dir '$d/'"; exit 1; }

mkdir -p "${outf%/*}"
sed "s,ENV_NAME,$input,g" "$tmpl" > "$outf"

chmod 755 "$outf"
