#!/sbin/openrc-run

: ${OPTS:="-LSwd -Lf /dev/null"}

pidfile="/run/${SVCNAME}.pid"
command="/usr/sbin/${SVCNAME}"
command_args="-f -p ${pidfile} ${OPTS}"
command_background="yes"
required_files="/etc/snmp/${SVCNAME}.conf"
extra_started_commands="reload"

depend() {
        use logger
        need net
        after firewall
}

reload() {
        ebegin "Reloading ${SVCNAME}"
        start-stop-daemon --signal HUP --pidfile ${pidfile} --name ${SVCNAME}
        eend $?
}