# System-wide .zprofile file for zsh(1) - sourced only for login shells.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

# Source /etc/profile to the current shell.
if [ -f /etc/profile ]; then
	emulate sh -c 'source /etc/profile'
fi

# vim: set ft=zsh ts=4:
