#!/bin/busybox sh
set -e
set -x

PATH=/usr/bin:/usr/sbin:/sbin:/bin

# Default is 777 which creates problems
chmod 0755 /

mount -t proc proc -o nodev,nosuid,hidepid=2 /proc
mount -t devtmpfs -o nosuid,noexec devtmpfs /dev
mount -t sysfs sys -o nodev,nosuid,noexec /sys

# Fetch settings from cmdline
DNS="$(tr ' ' '\n' < /proc/cmdline | grep "dns=" | cut -d'=' -f2-)"
HOSTNAME="$(tr ' ' '\n' < /proc/cmdline | grep "hostname=" | cut -d'=' -f2-)"
SSHKEY="$(tr ' ' '\n' < /proc/cmdline | grep "sshkey=" | cut -d'=' -f2- | base64 -d)"

if [ -z "${SSHKEY}" ]; then
	echo "Missing default mount for ssh keys"
	exit 1
fi

# We can ignore this fail, if we use a kernel with kvm_guest.config, we won't need this
# and network will work anyway
# If this fails and we won't have network, the ifconfig command will fail anyway.
# Also we load cpu accelleration drivers in case those are needed.
depmod -a || :
sort -u /sys/devices/system/cpu/modalias | xargs -n1 modprobe 2>/dev/null || :
sort -u /sys/devices/pci*/*/virtio*/modalias | xargs -n1 modprobe 2>/dev/null || :
# modprobe 9p if absent
if ! grep -q 9p /proc/filesystems; then
	modprobe virtio
	modprobe virtio_blk
	modprobe virtio_gpu
	modprobe virtio_net
	modprobe virtio_pci
	modprobe virtio_pci_legacy_dev
	modprobe virtio_pci_modern_dev
	modprobe virtio_pmem
	modprobe virtio_ring
	modprobe virtio_rng
	modprobe virtio_scsi
	modprobe 9pnet_virtio
	modprobe 9pnet
	modprobe 9p
fi

# If we have an external disk, we want to perform builds in that
if [ -e /dev/vda ]; then
	grep -q ext4 /proc/filesystems || modprobe ext4
	mkfs.ext4 -O ^has_journal /dev/vda
	mkdir -p /mount
	mount -o nobarrier,noatime,nodiratime,nobh,barrier=0 -t ext4 /dev/vda /mount
	# Extract build environment in /mount
	time tar -xpf /dev/vdb -m -k --ignore-zeros --record-size=64K --numeric-owner -C /mount/
	mkdir -p /mount/mnt
	# ensure permissions are correct for sshd's ChrootDirectory
	chown root:root /mount
	chmod 0755 /mount
fi

# Fix home permissions from cpio command
if grep -q build /etc/passwd; then
	mkdir -p /mount/home/build
	chown -R build:build /mount/home/build
fi

# Set default hard limit of open file descriptors to match systemd init
# behavior. The pam_limit module uses the settings in /proc/1/limit as
# its default values.
if [ -f /proc/sys/fs/nr_open ] ; then
	nofile_limit=$(ulimit -H -n)
	kernel_max_limit=$(cat /proc/sys/fs/nr_open)
	# ensure that we are increasing the hard limit
	if [[ "${kernel_max_limit}" =~ ^[0-9]+$ ]] &&
		[ "${nofile_limit}" -lt "${kernel_max_limit}" ] ; then

		ulimit -H -n "$kernel_max_limit"
	fi
fi

# Setup default mountpoint for 9p shared dir
mount -t 9p \
	-o trans=virtio \
	-o version=9p2000.L \
	-o security_model=mapped-xattr \
	-o posixacl=on \
	-o msize=104857600 \
	defaultshare /mount/mnt/

mount -t proc proc -o nodev,nosuid,hidepid=2 /mount/proc
mount -t devtmpfs -o nosuid,noexec devtmpfs /mount/dev
mount -t sysfs sys -o nodev,nosuid,noexec /mount/sys
mount -t cgroup2 -o nsdelegate,memory_recursiveprot,nosuid,nodev,noexec cgroup2 /mount/sys/fs/cgroup
mount -t tmpfs -o nodev,nosuid tmpfs /mount/tmp

# Fix /dev/fd
ln -s /proc/kcore /mount/dev/core
ln -s /proc/self/fd /mount/dev/fd
ln -s /proc/self/fd/0 /mount/dev/stdin
ln -s /proc/self/fd/1 /mount/dev/stdout
ln -s /proc/self/fd/2 /mount/dev/stderr

# Setup tty/pty
mkdir /mount/dev/pts
mount -t devpts devpts -o noexec,nosuid,newinstance,ptmxmode=0666,mode=0620,gid=tty /mount/dev/pts/
mount --bind /mount/dev/pts/ptmx /mount/dev/ptmx

# ldconfig is run to prime ld.so.cache for glibc packages which require it.
chroot /mount /bin/sh -c "[ -x /sbin/ldconfig ] && /sbin/ldconfig /lib /usr/lib /usr/lib64"

# Setup default network
interface_name="$(ip -o link show | grep 'BROADCAST,MULTICAST' | head -n 1 | cut -d':' -f2 | tr -d ' ')"
ip link set lo up
ip link set "${interface_name:-"eth0"}" up
ip addr add 10.0.2.15/24 dev "${interface_name:-"eth0"}"
ip route add default via 10.0.2.2 dev "${interface_name:-"eth0"}"

hostname "${HOSTNAME:-"wolfi-vm"}"
echo "${HOSTNAME:-"wolfi-vm"}" > /mount/etc/hostname
echo "127.0.0.1 ${HOSTNAME:-"wolfi-vm"}" >> /mount/etc/hosts
echo "nameserver ${DNS:-"10.0.2.3"}" > /mount/etc/resolv.conf

##############
# Entrypoint #
##############
# Setup SSH keys for external access
mkdir -p -m 0700 /root/.ssh/ /home/build/.ssh/
echo "${SSHKEY}" > /root/.ssh/authorized_keys
echo "${SSHKEY}" > /home/build/.ssh/authorized_keys
chmod 0400 /root/.ssh/authorized_keys /home/build/.ssh/authorized_keys
if grep -q build /etc/passwd; then
	chown -R build:build /home/build/.ssh/
fi

# Setting up Chroot and accept env AcceptEnv
# Order here is important! ChrootDirectory must be the first!
echo "ChrootDirectory /mount" > /etc/ssh/sshd_config
echo "AcceptEnv *" >> /etc/ssh/sshd_config
echo "AddressFamily inet" >> /etc/ssh/sshd_config
echo "UseDNS no" >> /etc/ssh/sshd_config
ssh-keygen -A -a 1
exec /usr/sbin/sshd -D -e
