#!/bin/busybox sh
set -e

PATH=/usr/bin:/usr/sbin:/sbin:/bin

# Default is 777 which creates problems
chmod 0755 /

mount -t proc proc -o nodev,nosuid,hidepid=2 /proc
# Fetch settings from cmdline
DNS="$(tr ' ' '\n' < /proc/cmdline | grep "dns=" | cut -d'=' -f2-)"
SSHKEY="$(tr ' ' '\n' < /proc/cmdline | grep "sshkey=" | cut -d'=' -f2- | base64 -d)"

# TODO(mattmoor): Check for debug logging and enable "set -x"

mount -t devtmpfs -o nosuid,noexec devtmpfs /dev
mount -t sysfs sys -o nodev,nosuid,noexec /sys
mount -t tmpfs tmpfs /tmp
mount -t tmpfs -o mode=1777 tmpfs /run
mkdir -p -m 0755 /dev/shm
mount -t tmpfs -o mode=1777 tmpfs /dev/shm

# Setup tty/pty
mkdir /dev/pts
mount -t devpts devpts -o noexec,nosuid,newinstance,ptmxmode=0666,mode=0620,gid=tty /dev/pts/
mount --bind /dev/pts/ptmx /dev/ptmx

if [ -z "${SSHKEY}" ]; then
	echo "Missing default mount for ssh keys"
	exit 1
fi

# Rest of modules will be taken care by systemd afterwards.
# modprobe 9p if absent we need to setup our defaultshare
if ! grep -q 9p /proc/filesystems; then
	modprobe 9pnet_virtio
	modprobe 9pnet
	modprobe 9p
fi

# TODO: move this to systemd unit.
# If we have an external disk, we want to perform builds in that
if [ -e /dev/vda ]; then
	grep -q xfs /proc/filesystems || modprobe xfs
	mkfs.xfs -q \
		-f \
		-b size=4096 \
		-s size=4096 \
		-d agcount=8 \
		-i size=512 \
		-l size=64m,lazy-count=1 \
		/dev/vda
	mkdir -p /mount
	mount -o noatime,nodiratime,logbufs=8,logbsize=256k -t xfs /dev/vda /mount
	# Extract build environment in /mount
	tar --xattrs --xattrs-include='*' -xpf /dev/vdb -m -k --ignore-zeros \
		--record-size=64K --numeric-owner -C /mount/
	mkdir -p /mount/mnt
	# ensure permissions are correct for sshd's ChrootDirectory
	chown root:root /mount
	chmod 0755 /mount

	# Make /home/build world writeable under /mount
	chmod 0777 /mount/home/build
fi

# TODO: move this to mount unit.
# Setup default mountpoint for 9p shared dir
mount -t 9p \
	-o trans=virtio \
	-o version=9p2000.L \
	-o security_model=mapped-xattr \
	-o posixacl=on \
	-o msize=104857600 \
	defaultshare /mount/mnt/

# TODO: move this to systemd unit that starts before sshd.service.
##########################
# Chroot directory setup #
##########################

# Allow the user we are running as to copy things to the shared dir
chmod 0777 /mount/mnt

mount --rbind /dev /mount/dev
mount --rbind /proc /mount/proc
mount --rbind /sys /mount/sys
mount --rbind /tmp /mount/tmp
mount -t tmpfs -o mode=1777 tmpfs /mount/run

mount -t cgroup2 -o nsdelegate,memory_recursiveprot,nosuid,nodev,noexec cgroup2 /mount/sys/fs/cgroup
mkdir -p /mount/dev/pts
mount -t devpts devpts -o noexec,nosuid,newinstance,ptmxmode=0666,mode=0620,gid=tty /mount/dev/pts/
mount --bind /mount/dev/pts/ptmx /mount/dev/ptmx
# Tell software that we're acting more like a container than a full VM
touch /mount/.dockerenv

# ldconfig is run to prime ld.so.cache for glibc packages which require it.
chroot /mount /bin/sh -c "[ -x /sbin/ldconfig ] && /sbin/ldconfig /lib /usr/lib /usr/lib64"
# inject DNS inside the chroot
echo "nameserver ${DNS:-"10.0.2.3"}" > /mount/etc/resolv.conf

# Setup SSH keys for external access
mkdir -p -m 0700 /root/.ssh/
echo "${SSHKEY}" > /root/.ssh/authorized_keys
chmod 0400 /root/.ssh/authorized_keys

# Copy the user/group files from the guest filesystem to the host
# and make sure that all the users that have /bin/sh as their shell
# have their home directory created and the ssh key copied there.
cp /mount/etc/passwd /etc/passwd
cp /mount/etc/group /etc/group
for i in $(awk -F: '$7 == "/bin/sh" {print $1}' /etc/passwd); do
	home="$(grep "^$i:" /etc/passwd | cut -d':' -f6)"
	group="$(grep "^$i:" /etc/passwd | cut -d':' -f4)"
	mkdir -p "$home/.ssh"
	echo "${SSHKEY}" > "/home/$i/.ssh/authorized_keys"
	chmod 0400 "/home/$i/.ssh/authorized_keys"
	chown -R "$i":"$group" "$home"
done

#################
# Systemd setup #
#################
#
# Mask units not needed inside build environment
systemctl mask proc-sys-fs-binfmt_misc.automount
systemctl mask systemd-nsresourced.socket

##############
# Entrypoint #
##############
exec /usr/lib/systemd/systemd
